// This file is generated by rust-protobuf 3.2.0. Do not edit
// .proto file is parsed by protoc --rust-out=...
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `cs_gameevents.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_2_0;

#[derive(PartialEq,Clone,Default,Debug)]
// @@protoc_insertion_point(message:CMsgTEPlayerAnimEvent)
pub struct CMsgTEPlayerAnimEvent {
    // message fields
    // @@protoc_insertion_point(field:CMsgTEPlayerAnimEvent.player)
    pub player: ::std::option::Option<u32>,
    // @@protoc_insertion_point(field:CMsgTEPlayerAnimEvent.event)
    pub event: ::std::option::Option<u32>,
    // @@protoc_insertion_point(field:CMsgTEPlayerAnimEvent.data)
    pub data: ::std::option::Option<i32>,
    // special fields
    // @@protoc_insertion_point(special_field:CMsgTEPlayerAnimEvent.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a CMsgTEPlayerAnimEvent {
    fn default() -> &'a CMsgTEPlayerAnimEvent {
        <CMsgTEPlayerAnimEvent as ::protobuf::Message>::default_instance()
    }
}

impl CMsgTEPlayerAnimEvent {
    pub fn new() -> CMsgTEPlayerAnimEvent {
        ::std::default::Default::default()
    }

    // optional fixed32 player = 1;

    pub fn player(&self) -> u32 {
        self.player.unwrap_or(16777215u32)
    }

    pub fn clear_player(&mut self) {
        self.player = ::std::option::Option::None;
    }

    pub fn has_player(&self) -> bool {
        self.player.is_some()
    }

    // Param is passed by value, moved
    pub fn set_player(&mut self, v: u32) {
        self.player = ::std::option::Option::Some(v);
    }

    // optional uint32 event = 2;

    pub fn event(&self) -> u32 {
        self.event.unwrap_or(0)
    }

    pub fn clear_event(&mut self) {
        self.event = ::std::option::Option::None;
    }

    pub fn has_event(&self) -> bool {
        self.event.is_some()
    }

    // Param is passed by value, moved
    pub fn set_event(&mut self, v: u32) {
        self.event = ::std::option::Option::Some(v);
    }

    // optional int32 data = 3;

    pub fn data(&self) -> i32 {
        self.data.unwrap_or(0)
    }

    pub fn clear_data(&mut self) {
        self.data = ::std::option::Option::None;
    }

    pub fn has_data(&self) -> bool {
        self.data.is_some()
    }

    // Param is passed by value, moved
    pub fn set_data(&mut self, v: i32) {
        self.data = ::std::option::Option::Some(v);
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(3);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "player",
            |m: &CMsgTEPlayerAnimEvent| { &m.player },
            |m: &mut CMsgTEPlayerAnimEvent| { &mut m.player },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "event",
            |m: &CMsgTEPlayerAnimEvent| { &m.event },
            |m: &mut CMsgTEPlayerAnimEvent| { &mut m.event },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "data",
            |m: &CMsgTEPlayerAnimEvent| { &m.data },
            |m: &mut CMsgTEPlayerAnimEvent| { &mut m.data },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<CMsgTEPlayerAnimEvent>(
            "CMsgTEPlayerAnimEvent",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for CMsgTEPlayerAnimEvent {
    const NAME: &'static str = "CMsgTEPlayerAnimEvent";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                13 => {
                    self.player = ::std::option::Option::Some(is.read_fixed32()?);
                },
                16 => {
                    self.event = ::std::option::Option::Some(is.read_uint32()?);
                },
                24 => {
                    self.data = ::std::option::Option::Some(is.read_int32()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let Some(v) = self.player {
            my_size += 1 + 4;
        }
        if let Some(v) = self.event {
            my_size += ::protobuf::rt::uint32_size(2, v);
        }
        if let Some(v) = self.data {
            my_size += ::protobuf::rt::int32_size(3, v);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if let Some(v) = self.player {
            os.write_fixed32(1, v)?;
        }
        if let Some(v) = self.event {
            os.write_uint32(2, v)?;
        }
        if let Some(v) = self.data {
            os.write_int32(3, v)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> CMsgTEPlayerAnimEvent {
        CMsgTEPlayerAnimEvent::new()
    }

    fn clear(&mut self) {
        self.player = ::std::option::Option::None;
        self.event = ::std::option::Option::None;
        self.data = ::std::option::Option::None;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static CMsgTEPlayerAnimEvent {
        static instance: CMsgTEPlayerAnimEvent = CMsgTEPlayerAnimEvent {
            player: ::std::option::Option::None,
            event: ::std::option::Option::None,
            data: ::std::option::Option::None,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for CMsgTEPlayerAnimEvent {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("CMsgTEPlayerAnimEvent").unwrap()).clone()
    }
}

impl ::std::fmt::Display for CMsgTEPlayerAnimEvent {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for CMsgTEPlayerAnimEvent {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

#[derive(PartialEq,Clone,Default,Debug)]
// @@protoc_insertion_point(message:CMsgTERadioIcon)
pub struct CMsgTERadioIcon {
    // message fields
    // @@protoc_insertion_point(field:CMsgTERadioIcon.player)
    pub player: ::std::option::Option<u32>,
    // special fields
    // @@protoc_insertion_point(special_field:CMsgTERadioIcon.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a CMsgTERadioIcon {
    fn default() -> &'a CMsgTERadioIcon {
        <CMsgTERadioIcon as ::protobuf::Message>::default_instance()
    }
}

impl CMsgTERadioIcon {
    pub fn new() -> CMsgTERadioIcon {
        ::std::default::Default::default()
    }

    // optional fixed32 player = 1;

    pub fn player(&self) -> u32 {
        self.player.unwrap_or(16777215u32)
    }

    pub fn clear_player(&mut self) {
        self.player = ::std::option::Option::None;
    }

    pub fn has_player(&self) -> bool {
        self.player.is_some()
    }

    // Param is passed by value, moved
    pub fn set_player(&mut self, v: u32) {
        self.player = ::std::option::Option::Some(v);
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(1);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "player",
            |m: &CMsgTERadioIcon| { &m.player },
            |m: &mut CMsgTERadioIcon| { &mut m.player },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<CMsgTERadioIcon>(
            "CMsgTERadioIcon",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for CMsgTERadioIcon {
    const NAME: &'static str = "CMsgTERadioIcon";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                13 => {
                    self.player = ::std::option::Option::Some(is.read_fixed32()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let Some(v) = self.player {
            my_size += 1 + 4;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if let Some(v) = self.player {
            os.write_fixed32(1, v)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> CMsgTERadioIcon {
        CMsgTERadioIcon::new()
    }

    fn clear(&mut self) {
        self.player = ::std::option::Option::None;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static CMsgTERadioIcon {
        static instance: CMsgTERadioIcon = CMsgTERadioIcon {
            player: ::std::option::Option::None,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for CMsgTERadioIcon {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("CMsgTERadioIcon").unwrap()).clone()
    }
}

impl ::std::fmt::Display for CMsgTERadioIcon {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for CMsgTERadioIcon {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

#[derive(PartialEq,Clone,Default,Debug)]
// @@protoc_insertion_point(message:CMsgTEFireBullets)
pub struct CMsgTEFireBullets {
    // message fields
    // @@protoc_insertion_point(field:CMsgTEFireBullets.origin)
    pub origin: ::protobuf::MessageField<super::networkbasetypes::CMsgVector>,
    // @@protoc_insertion_point(field:CMsgTEFireBullets.angles)
    pub angles: ::protobuf::MessageField<super::networkbasetypes::CMsgQAngle>,
    // @@protoc_insertion_point(field:CMsgTEFireBullets.weapon_id)
    pub weapon_id: ::std::option::Option<u32>,
    // @@protoc_insertion_point(field:CMsgTEFireBullets.mode)
    pub mode: ::std::option::Option<u32>,
    // @@protoc_insertion_point(field:CMsgTEFireBullets.seed)
    pub seed: ::std::option::Option<u32>,
    // @@protoc_insertion_point(field:CMsgTEFireBullets.player)
    pub player: ::std::option::Option<u32>,
    // @@protoc_insertion_point(field:CMsgTEFireBullets.inaccuracy)
    pub inaccuracy: ::std::option::Option<f32>,
    // @@protoc_insertion_point(field:CMsgTEFireBullets.recoil_index)
    pub recoil_index: ::std::option::Option<f32>,
    // @@protoc_insertion_point(field:CMsgTEFireBullets.spread)
    pub spread: ::std::option::Option<f32>,
    // @@protoc_insertion_point(field:CMsgTEFireBullets.sound_type)
    pub sound_type: ::std::option::Option<i32>,
    // @@protoc_insertion_point(field:CMsgTEFireBullets.item_def_index)
    pub item_def_index: ::std::option::Option<u32>,
    // @@protoc_insertion_point(field:CMsgTEFireBullets.sound_dsp_effect)
    pub sound_dsp_effect: ::std::option::Option<u32>,
    // special fields
    // @@protoc_insertion_point(special_field:CMsgTEFireBullets.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a CMsgTEFireBullets {
    fn default() -> &'a CMsgTEFireBullets {
        <CMsgTEFireBullets as ::protobuf::Message>::default_instance()
    }
}

impl CMsgTEFireBullets {
    pub fn new() -> CMsgTEFireBullets {
        ::std::default::Default::default()
    }

    // optional uint32 weapon_id = 3;

    pub fn weapon_id(&self) -> u32 {
        self.weapon_id.unwrap_or(16777215u32)
    }

    pub fn clear_weapon_id(&mut self) {
        self.weapon_id = ::std::option::Option::None;
    }

    pub fn has_weapon_id(&self) -> bool {
        self.weapon_id.is_some()
    }

    // Param is passed by value, moved
    pub fn set_weapon_id(&mut self, v: u32) {
        self.weapon_id = ::std::option::Option::Some(v);
    }

    // optional uint32 mode = 4;

    pub fn mode(&self) -> u32 {
        self.mode.unwrap_or(0)
    }

    pub fn clear_mode(&mut self) {
        self.mode = ::std::option::Option::None;
    }

    pub fn has_mode(&self) -> bool {
        self.mode.is_some()
    }

    // Param is passed by value, moved
    pub fn set_mode(&mut self, v: u32) {
        self.mode = ::std::option::Option::Some(v);
    }

    // optional uint32 seed = 5;

    pub fn seed(&self) -> u32 {
        self.seed.unwrap_or(0)
    }

    pub fn clear_seed(&mut self) {
        self.seed = ::std::option::Option::None;
    }

    pub fn has_seed(&self) -> bool {
        self.seed.is_some()
    }

    // Param is passed by value, moved
    pub fn set_seed(&mut self, v: u32) {
        self.seed = ::std::option::Option::Some(v);
    }

    // optional fixed32 player = 6;

    pub fn player(&self) -> u32 {
        self.player.unwrap_or(16777215u32)
    }

    pub fn clear_player(&mut self) {
        self.player = ::std::option::Option::None;
    }

    pub fn has_player(&self) -> bool {
        self.player.is_some()
    }

    // Param is passed by value, moved
    pub fn set_player(&mut self, v: u32) {
        self.player = ::std::option::Option::Some(v);
    }

    // optional float inaccuracy = 7;

    pub fn inaccuracy(&self) -> f32 {
        self.inaccuracy.unwrap_or(0.)
    }

    pub fn clear_inaccuracy(&mut self) {
        self.inaccuracy = ::std::option::Option::None;
    }

    pub fn has_inaccuracy(&self) -> bool {
        self.inaccuracy.is_some()
    }

    // Param is passed by value, moved
    pub fn set_inaccuracy(&mut self, v: f32) {
        self.inaccuracy = ::std::option::Option::Some(v);
    }

    // optional float recoil_index = 8;

    pub fn recoil_index(&self) -> f32 {
        self.recoil_index.unwrap_or(0.)
    }

    pub fn clear_recoil_index(&mut self) {
        self.recoil_index = ::std::option::Option::None;
    }

    pub fn has_recoil_index(&self) -> bool {
        self.recoil_index.is_some()
    }

    // Param is passed by value, moved
    pub fn set_recoil_index(&mut self, v: f32) {
        self.recoil_index = ::std::option::Option::Some(v);
    }

    // optional float spread = 9;

    pub fn spread(&self) -> f32 {
        self.spread.unwrap_or(0.)
    }

    pub fn clear_spread(&mut self) {
        self.spread = ::std::option::Option::None;
    }

    pub fn has_spread(&self) -> bool {
        self.spread.is_some()
    }

    // Param is passed by value, moved
    pub fn set_spread(&mut self, v: f32) {
        self.spread = ::std::option::Option::Some(v);
    }

    // optional int32 sound_type = 10;

    pub fn sound_type(&self) -> i32 {
        self.sound_type.unwrap_or(0)
    }

    pub fn clear_sound_type(&mut self) {
        self.sound_type = ::std::option::Option::None;
    }

    pub fn has_sound_type(&self) -> bool {
        self.sound_type.is_some()
    }

    // Param is passed by value, moved
    pub fn set_sound_type(&mut self, v: i32) {
        self.sound_type = ::std::option::Option::Some(v);
    }

    // optional uint32 item_def_index = 11;

    pub fn item_def_index(&self) -> u32 {
        self.item_def_index.unwrap_or(0)
    }

    pub fn clear_item_def_index(&mut self) {
        self.item_def_index = ::std::option::Option::None;
    }

    pub fn has_item_def_index(&self) -> bool {
        self.item_def_index.is_some()
    }

    // Param is passed by value, moved
    pub fn set_item_def_index(&mut self, v: u32) {
        self.item_def_index = ::std::option::Option::Some(v);
    }

    // optional fixed32 sound_dsp_effect = 12;

    pub fn sound_dsp_effect(&self) -> u32 {
        self.sound_dsp_effect.unwrap_or(0)
    }

    pub fn clear_sound_dsp_effect(&mut self) {
        self.sound_dsp_effect = ::std::option::Option::None;
    }

    pub fn has_sound_dsp_effect(&self) -> bool {
        self.sound_dsp_effect.is_some()
    }

    // Param is passed by value, moved
    pub fn set_sound_dsp_effect(&mut self, v: u32) {
        self.sound_dsp_effect = ::std::option::Option::Some(v);
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(12);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, super::networkbasetypes::CMsgVector>(
            "origin",
            |m: &CMsgTEFireBullets| { &m.origin },
            |m: &mut CMsgTEFireBullets| { &mut m.origin },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, super::networkbasetypes::CMsgQAngle>(
            "angles",
            |m: &CMsgTEFireBullets| { &m.angles },
            |m: &mut CMsgTEFireBullets| { &mut m.angles },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "weapon_id",
            |m: &CMsgTEFireBullets| { &m.weapon_id },
            |m: &mut CMsgTEFireBullets| { &mut m.weapon_id },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "mode",
            |m: &CMsgTEFireBullets| { &m.mode },
            |m: &mut CMsgTEFireBullets| { &mut m.mode },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "seed",
            |m: &CMsgTEFireBullets| { &m.seed },
            |m: &mut CMsgTEFireBullets| { &mut m.seed },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "player",
            |m: &CMsgTEFireBullets| { &m.player },
            |m: &mut CMsgTEFireBullets| { &mut m.player },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "inaccuracy",
            |m: &CMsgTEFireBullets| { &m.inaccuracy },
            |m: &mut CMsgTEFireBullets| { &mut m.inaccuracy },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "recoil_index",
            |m: &CMsgTEFireBullets| { &m.recoil_index },
            |m: &mut CMsgTEFireBullets| { &mut m.recoil_index },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "spread",
            |m: &CMsgTEFireBullets| { &m.spread },
            |m: &mut CMsgTEFireBullets| { &mut m.spread },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "sound_type",
            |m: &CMsgTEFireBullets| { &m.sound_type },
            |m: &mut CMsgTEFireBullets| { &mut m.sound_type },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "item_def_index",
            |m: &CMsgTEFireBullets| { &m.item_def_index },
            |m: &mut CMsgTEFireBullets| { &mut m.item_def_index },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "sound_dsp_effect",
            |m: &CMsgTEFireBullets| { &m.sound_dsp_effect },
            |m: &mut CMsgTEFireBullets| { &mut m.sound_dsp_effect },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<CMsgTEFireBullets>(
            "CMsgTEFireBullets",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for CMsgTEFireBullets {
    const NAME: &'static str = "CMsgTEFireBullets";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.origin)?;
                },
                18 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.angles)?;
                },
                24 => {
                    self.weapon_id = ::std::option::Option::Some(is.read_uint32()?);
                },
                32 => {
                    self.mode = ::std::option::Option::Some(is.read_uint32()?);
                },
                40 => {
                    self.seed = ::std::option::Option::Some(is.read_uint32()?);
                },
                53 => {
                    self.player = ::std::option::Option::Some(is.read_fixed32()?);
                },
                61 => {
                    self.inaccuracy = ::std::option::Option::Some(is.read_float()?);
                },
                69 => {
                    self.recoil_index = ::std::option::Option::Some(is.read_float()?);
                },
                77 => {
                    self.spread = ::std::option::Option::Some(is.read_float()?);
                },
                80 => {
                    self.sound_type = ::std::option::Option::Some(is.read_int32()?);
                },
                88 => {
                    self.item_def_index = ::std::option::Option::Some(is.read_uint32()?);
                },
                101 => {
                    self.sound_dsp_effect = ::std::option::Option::Some(is.read_fixed32()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let Some(v) = self.origin.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if let Some(v) = self.angles.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if let Some(v) = self.weapon_id {
            my_size += ::protobuf::rt::uint32_size(3, v);
        }
        if let Some(v) = self.mode {
            my_size += ::protobuf::rt::uint32_size(4, v);
        }
        if let Some(v) = self.seed {
            my_size += ::protobuf::rt::uint32_size(5, v);
        }
        if let Some(v) = self.player {
            my_size += 1 + 4;
        }
        if let Some(v) = self.inaccuracy {
            my_size += 1 + 4;
        }
        if let Some(v) = self.recoil_index {
            my_size += 1 + 4;
        }
        if let Some(v) = self.spread {
            my_size += 1 + 4;
        }
        if let Some(v) = self.sound_type {
            my_size += ::protobuf::rt::int32_size(10, v);
        }
        if let Some(v) = self.item_def_index {
            my_size += ::protobuf::rt::uint32_size(11, v);
        }
        if let Some(v) = self.sound_dsp_effect {
            my_size += 1 + 4;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if let Some(v) = self.origin.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(1, v, os)?;
        }
        if let Some(v) = self.angles.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(2, v, os)?;
        }
        if let Some(v) = self.weapon_id {
            os.write_uint32(3, v)?;
        }
        if let Some(v) = self.mode {
            os.write_uint32(4, v)?;
        }
        if let Some(v) = self.seed {
            os.write_uint32(5, v)?;
        }
        if let Some(v) = self.player {
            os.write_fixed32(6, v)?;
        }
        if let Some(v) = self.inaccuracy {
            os.write_float(7, v)?;
        }
        if let Some(v) = self.recoil_index {
            os.write_float(8, v)?;
        }
        if let Some(v) = self.spread {
            os.write_float(9, v)?;
        }
        if let Some(v) = self.sound_type {
            os.write_int32(10, v)?;
        }
        if let Some(v) = self.item_def_index {
            os.write_uint32(11, v)?;
        }
        if let Some(v) = self.sound_dsp_effect {
            os.write_fixed32(12, v)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> CMsgTEFireBullets {
        CMsgTEFireBullets::new()
    }

    fn clear(&mut self) {
        self.origin.clear();
        self.angles.clear();
        self.weapon_id = ::std::option::Option::None;
        self.mode = ::std::option::Option::None;
        self.seed = ::std::option::Option::None;
        self.player = ::std::option::Option::None;
        self.inaccuracy = ::std::option::Option::None;
        self.recoil_index = ::std::option::Option::None;
        self.spread = ::std::option::Option::None;
        self.sound_type = ::std::option::Option::None;
        self.item_def_index = ::std::option::Option::None;
        self.sound_dsp_effect = ::std::option::Option::None;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static CMsgTEFireBullets {
        static instance: CMsgTEFireBullets = CMsgTEFireBullets {
            origin: ::protobuf::MessageField::none(),
            angles: ::protobuf::MessageField::none(),
            weapon_id: ::std::option::Option::None,
            mode: ::std::option::Option::None,
            seed: ::std::option::Option::None,
            player: ::std::option::Option::None,
            inaccuracy: ::std::option::Option::None,
            recoil_index: ::std::option::Option::None,
            spread: ::std::option::Option::None,
            sound_type: ::std::option::Option::None,
            item_def_index: ::std::option::Option::None,
            sound_dsp_effect: ::std::option::Option::None,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for CMsgTEFireBullets {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("CMsgTEFireBullets").unwrap()).clone()
    }
}

impl ::std::fmt::Display for CMsgTEFireBullets {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for CMsgTEFireBullets {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

#[derive(Clone,Copy,PartialEq,Eq,Debug,Hash)]
// @@protoc_insertion_point(enum:ECsgoGameEvents)
pub enum ECsgoGameEvents {
    // @@protoc_insertion_point(enum_value:ECsgoGameEvents.GE_PlayerAnimEventId)
    GE_PlayerAnimEventId = 450,
    // @@protoc_insertion_point(enum_value:ECsgoGameEvents.GE_RadioIconEventId)
    GE_RadioIconEventId = 451,
    // @@protoc_insertion_point(enum_value:ECsgoGameEvents.GE_FireBulletsId)
    GE_FireBulletsId = 452,
}

impl ::protobuf::Enum for ECsgoGameEvents {
    const NAME: &'static str = "ECsgoGameEvents";

    fn value(&self) -> i32 {
        *self as i32
    }

    fn from_i32(value: i32) -> ::std::option::Option<ECsgoGameEvents> {
        match value {
            450 => ::std::option::Option::Some(ECsgoGameEvents::GE_PlayerAnimEventId),
            451 => ::std::option::Option::Some(ECsgoGameEvents::GE_RadioIconEventId),
            452 => ::std::option::Option::Some(ECsgoGameEvents::GE_FireBulletsId),
            _ => ::std::option::Option::None
        }
    }

    const VALUES: &'static [ECsgoGameEvents] = &[
        ECsgoGameEvents::GE_PlayerAnimEventId,
        ECsgoGameEvents::GE_RadioIconEventId,
        ECsgoGameEvents::GE_FireBulletsId,
    ];
}

impl ::protobuf::EnumFull for ECsgoGameEvents {
    fn enum_descriptor() -> ::protobuf::reflect::EnumDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::EnumDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().enum_by_package_relative_name("ECsgoGameEvents").unwrap()).clone()
    }

    fn descriptor(&self) -> ::protobuf::reflect::EnumValueDescriptor {
        let index = match self {
            ECsgoGameEvents::GE_PlayerAnimEventId => 0,
            ECsgoGameEvents::GE_RadioIconEventId => 1,
            ECsgoGameEvents::GE_FireBulletsId => 2,
        };
        Self::enum_descriptor().value_by_index(index)
    }
}

// Note, `Default` is implemented although default value is not 0
impl ::std::default::Default for ECsgoGameEvents {
    fn default() -> Self {
        ECsgoGameEvents::GE_PlayerAnimEventId
    }
}

impl ECsgoGameEvents {
    fn generated_enum_descriptor_data() -> ::protobuf::reflect::GeneratedEnumDescriptorData {
        ::protobuf::reflect::GeneratedEnumDescriptorData::new::<ECsgoGameEvents>("ECsgoGameEvents")
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x13cs_gameevents.proto\x1a\x16networkbasetypes.proto\"c\n\x15CMsgTEPl\
    ayerAnimEvent\x12\x20\n\x06player\x18\x01\x20\x01(\x07:\x0816777215R\x06\
    player\x12\x14\n\x05event\x18\x02\x20\x01(\rR\x05event\x12\x12\n\x04data\
    \x18\x03\x20\x01(\x05R\x04data\"3\n\x0fCMsgTERadioIcon\x12\x20\n\x06play\
    er\x18\x01\x20\x01(\x07:\x0816777215R\x06player\"\x98\x03\n\x11CMsgTEFir\
    eBullets\x12#\n\x06origin\x18\x01\x20\x01(\x0b2\x0b.CMsgVectorR\x06origi\
    n\x12#\n\x06angles\x18\x02\x20\x01(\x0b2\x0b.CMsgQAngleR\x06angles\x12%\
    \n\tweapon_id\x18\x03\x20\x01(\r:\x0816777215R\x08weaponId\x12\x12\n\x04\
    mode\x18\x04\x20\x01(\rR\x04mode\x12\x12\n\x04seed\x18\x05\x20\x01(\rR\
    \x04seed\x12\x20\n\x06player\x18\x06\x20\x01(\x07:\x0816777215R\x06playe\
    r\x12\x1e\n\ninaccuracy\x18\x07\x20\x01(\x02R\ninaccuracy\x12!\n\x0creco\
    il_index\x18\x08\x20\x01(\x02R\x0brecoilIndex\x12\x16\n\x06spread\x18\t\
    \x20\x01(\x02R\x06spread\x12\x1d\n\nsound_type\x18\n\x20\x01(\x05R\tsoun\
    dType\x12$\n\x0eitem_def_index\x18\x0b\x20\x01(\rR\x0citemDefIndex\x12(\
    \n\x10sound_dsp_effect\x18\x0c\x20\x01(\x07R\x0esoundDspEffect*]\n\x0fEC\
    sgoGameEvents\x12\x19\n\x14GE_PlayerAnimEventId\x10\xc2\x03\x12\x18\n\
    \x13GE_RadioIconEventId\x10\xc3\x03\x12\x15\n\x10GE_FireBulletsId\x10\
    \xc4\x03J\xae\x0b\n\x06\x12\x04\0\0\x1f\x01\n\t\n\x02\x03\0\x12\x03\0\0\
    \x20\n\n\n\x02\x05\0\x12\x04\x02\0\x06\x01\n\n\n\x03\x05\0\x01\x12\x03\
    \x02\x05\x14\n\x0b\n\x04\x05\0\x02\0\x12\x03\x03\x08#\n\x0c\n\x05\x05\0\
    \x02\0\x01\x12\x03\x03\x08\x1c\n\x0c\n\x05\x05\0\x02\0\x02\x12\x03\x03\
    \x1f\"\n\x0b\n\x04\x05\0\x02\x01\x12\x03\x04\x08\"\n\x0c\n\x05\x05\0\x02\
    \x01\x01\x12\x03\x04\x08\x1b\n\x0c\n\x05\x05\0\x02\x01\x02\x12\x03\x04\
    \x1e!\n\x0b\n\x04\x05\0\x02\x02\x12\x03\x05\x08\x1f\n\x0c\n\x05\x05\0\
    \x02\x02\x01\x12\x03\x05\x08\x18\n\x0c\n\x05\x05\0\x02\x02\x02\x12\x03\
    \x05\x1b\x1e\n\n\n\x02\x04\0\x12\x04\x08\0\x0c\x01\n\n\n\x03\x04\0\x01\
    \x12\x03\x08\x08\x1d\n\x0b\n\x04\x04\0\x02\0\x12\x03\t\x089\n\x0c\n\x05\
    \x04\0\x02\0\x04\x12\x03\t\x08\x10\n\x0c\n\x05\x04\0\x02\0\x05\x12\x03\t\
    \x11\x18\n\x0c\n\x05\x04\0\x02\0\x01\x12\x03\t\x19\x1f\n\x0c\n\x05\x04\0\
    \x02\0\x03\x12\x03\t\"#\n\x0c\n\x05\x04\0\x02\0\x08\x12\x03\t$8\n\x0c\n\
    \x05\x04\0\x02\0\x07\x12\x03\t/7\n\x0b\n\x04\x04\0\x02\x01\x12\x03\n\x08\
    \"\n\x0c\n\x05\x04\0\x02\x01\x04\x12\x03\n\x08\x10\n\x0c\n\x05\x04\0\x02\
    \x01\x05\x12\x03\n\x11\x17\n\x0c\n\x05\x04\0\x02\x01\x01\x12\x03\n\x18\
    \x1d\n\x0c\n\x05\x04\0\x02\x01\x03\x12\x03\n\x20!\n\x0b\n\x04\x04\0\x02\
    \x02\x12\x03\x0b\x08\x20\n\x0c\n\x05\x04\0\x02\x02\x04\x12\x03\x0b\x08\
    \x10\n\x0c\n\x05\x04\0\x02\x02\x05\x12\x03\x0b\x11\x16\n\x0c\n\x05\x04\0\
    \x02\x02\x01\x12\x03\x0b\x17\x1b\n\x0c\n\x05\x04\0\x02\x02\x03\x12\x03\
    \x0b\x1e\x1f\n\n\n\x02\x04\x01\x12\x04\x0e\0\x10\x01\n\n\n\x03\x04\x01\
    \x01\x12\x03\x0e\x08\x17\n\x0b\n\x04\x04\x01\x02\0\x12\x03\x0f\x089\n\
    \x0c\n\x05\x04\x01\x02\0\x04\x12\x03\x0f\x08\x10\n\x0c\n\x05\x04\x01\x02\
    \0\x05\x12\x03\x0f\x11\x18\n\x0c\n\x05\x04\x01\x02\0\x01\x12\x03\x0f\x19\
    \x1f\n\x0c\n\x05\x04\x01\x02\0\x03\x12\x03\x0f\"#\n\x0c\n\x05\x04\x01\
    \x02\0\x08\x12\x03\x0f$8\n\x0c\n\x05\x04\x01\x02\0\x07\x12\x03\x0f/7\n\n\
    \n\x02\x04\x02\x12\x04\x12\0\x1f\x01\n\n\n\x03\x04\x02\x01\x12\x03\x12\
    \x08\x19\n\x0b\n\x04\x04\x02\x02\0\x12\x03\x13\x08(\n\x0c\n\x05\x04\x02\
    \x02\0\x04\x12\x03\x13\x08\x10\n\x0c\n\x05\x04\x02\x02\0\x06\x12\x03\x13\
    \x11\x1c\n\x0c\n\x05\x04\x02\x02\0\x01\x12\x03\x13\x1d#\n\x0c\n\x05\x04\
    \x02\x02\0\x03\x12\x03\x13&'\n\x0b\n\x04\x04\x02\x02\x01\x12\x03\x14\x08\
    (\n\x0c\n\x05\x04\x02\x02\x01\x04\x12\x03\x14\x08\x10\n\x0c\n\x05\x04\
    \x02\x02\x01\x06\x12\x03\x14\x11\x1c\n\x0c\n\x05\x04\x02\x02\x01\x01\x12\
    \x03\x14\x1d#\n\x0c\n\x05\x04\x02\x02\x01\x03\x12\x03\x14&'\n\x0b\n\x04\
    \x04\x02\x02\x02\x12\x03\x15\x08;\n\x0c\n\x05\x04\x02\x02\x02\x04\x12\
    \x03\x15\x08\x10\n\x0c\n\x05\x04\x02\x02\x02\x05\x12\x03\x15\x11\x17\n\
    \x0c\n\x05\x04\x02\x02\x02\x01\x12\x03\x15\x18!\n\x0c\n\x05\x04\x02\x02\
    \x02\x03\x12\x03\x15$%\n\x0c\n\x05\x04\x02\x02\x02\x08\x12\x03\x15&:\n\
    \x0c\n\x05\x04\x02\x02\x02\x07\x12\x03\x1519\n\x0b\n\x04\x04\x02\x02\x03\
    \x12\x03\x16\x08!\n\x0c\n\x05\x04\x02\x02\x03\x04\x12\x03\x16\x08\x10\n\
    \x0c\n\x05\x04\x02\x02\x03\x05\x12\x03\x16\x11\x17\n\x0c\n\x05\x04\x02\
    \x02\x03\x01\x12\x03\x16\x18\x1c\n\x0c\n\x05\x04\x02\x02\x03\x03\x12\x03\
    \x16\x1f\x20\n\x0b\n\x04\x04\x02\x02\x04\x12\x03\x17\x08!\n\x0c\n\x05\
    \x04\x02\x02\x04\x04\x12\x03\x17\x08\x10\n\x0c\n\x05\x04\x02\x02\x04\x05\
    \x12\x03\x17\x11\x17\n\x0c\n\x05\x04\x02\x02\x04\x01\x12\x03\x17\x18\x1c\
    \n\x0c\n\x05\x04\x02\x02\x04\x03\x12\x03\x17\x1f\x20\n\x0b\n\x04\x04\x02\
    \x02\x05\x12\x03\x18\x089\n\x0c\n\x05\x04\x02\x02\x05\x04\x12\x03\x18\
    \x08\x10\n\x0c\n\x05\x04\x02\x02\x05\x05\x12\x03\x18\x11\x18\n\x0c\n\x05\
    \x04\x02\x02\x05\x01\x12\x03\x18\x19\x1f\n\x0c\n\x05\x04\x02\x02\x05\x03\
    \x12\x03\x18\"#\n\x0c\n\x05\x04\x02\x02\x05\x08\x12\x03\x18$8\n\x0c\n\
    \x05\x04\x02\x02\x05\x07\x12\x03\x18/7\n\x0b\n\x04\x04\x02\x02\x06\x12\
    \x03\x19\x08&\n\x0c\n\x05\x04\x02\x02\x06\x04\x12\x03\x19\x08\x10\n\x0c\
    \n\x05\x04\x02\x02\x06\x05\x12\x03\x19\x11\x16\n\x0c\n\x05\x04\x02\x02\
    \x06\x01\x12\x03\x19\x17!\n\x0c\n\x05\x04\x02\x02\x06\x03\x12\x03\x19$%\
    \n\x0b\n\x04\x04\x02\x02\x07\x12\x03\x1a\x08(\n\x0c\n\x05\x04\x02\x02\
    \x07\x04\x12\x03\x1a\x08\x10\n\x0c\n\x05\x04\x02\x02\x07\x05\x12\x03\x1a\
    \x11\x16\n\x0c\n\x05\x04\x02\x02\x07\x01\x12\x03\x1a\x17#\n\x0c\n\x05\
    \x04\x02\x02\x07\x03\x12\x03\x1a&'\n\x0b\n\x04\x04\x02\x02\x08\x12\x03\
    \x1b\x08\"\n\x0c\n\x05\x04\x02\x02\x08\x04\x12\x03\x1b\x08\x10\n\x0c\n\
    \x05\x04\x02\x02\x08\x05\x12\x03\x1b\x11\x16\n\x0c\n\x05\x04\x02\x02\x08\
    \x01\x12\x03\x1b\x17\x1d\n\x0c\n\x05\x04\x02\x02\x08\x03\x12\x03\x1b\x20\
    !\n\x0b\n\x04\x04\x02\x02\t\x12\x03\x1c\x08'\n\x0c\n\x05\x04\x02\x02\t\
    \x04\x12\x03\x1c\x08\x10\n\x0c\n\x05\x04\x02\x02\t\x05\x12\x03\x1c\x11\
    \x16\n\x0c\n\x05\x04\x02\x02\t\x01\x12\x03\x1c\x17!\n\x0c\n\x05\x04\x02\
    \x02\t\x03\x12\x03\x1c$&\n\x0b\n\x04\x04\x02\x02\n\x12\x03\x1d\x08,\n\
    \x0c\n\x05\x04\x02\x02\n\x04\x12\x03\x1d\x08\x10\n\x0c\n\x05\x04\x02\x02\
    \n\x05\x12\x03\x1d\x11\x17\n\x0c\n\x05\x04\x02\x02\n\x01\x12\x03\x1d\x18\
    &\n\x0c\n\x05\x04\x02\x02\n\x03\x12\x03\x1d)+\n\x0b\n\x04\x04\x02\x02\
    \x0b\x12\x03\x1e\x08/\n\x0c\n\x05\x04\x02\x02\x0b\x04\x12\x03\x1e\x08\
    \x10\n\x0c\n\x05\x04\x02\x02\x0b\x05\x12\x03\x1e\x11\x18\n\x0c\n\x05\x04\
    \x02\x02\x0b\x01\x12\x03\x1e\x19)\n\x0c\n\x05\x04\x02\x02\x0b\x03\x12\
    \x03\x1e,.\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(1);
            deps.push(super::networkbasetypes::file_descriptor().clone());
            let mut messages = ::std::vec::Vec::with_capacity(3);
            messages.push(CMsgTEPlayerAnimEvent::generated_message_descriptor_data());
            messages.push(CMsgTERadioIcon::generated_message_descriptor_data());
            messages.push(CMsgTEFireBullets::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(1);
            enums.push(ECsgoGameEvents::generated_enum_descriptor_data());
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
