// This file is generated by rust-protobuf 3.2.0. Do not edit
// .proto file is parsed by protoc --rust-out=...
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `network_connection.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_2_0;

#[derive(Clone,Copy,PartialEq,Eq,Debug,Hash)]
// @@protoc_insertion_point(enum:ENetworkDisconnectionReason)
pub enum ENetworkDisconnectionReason {
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_INVALID)
    NETWORK_DISCONNECT_INVALID = 0,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_SHUTDOWN)
    NETWORK_DISCONNECT_SHUTDOWN = 1,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_DISCONNECT_BY_USER)
    NETWORK_DISCONNECT_DISCONNECT_BY_USER = 2,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_DISCONNECT_BY_SERVER)
    NETWORK_DISCONNECT_DISCONNECT_BY_SERVER = 3,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_LOST)
    NETWORK_DISCONNECT_LOST = 4,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_OVERFLOW)
    NETWORK_DISCONNECT_OVERFLOW = 5,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_STEAM_BANNED)
    NETWORK_DISCONNECT_STEAM_BANNED = 6,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_STEAM_INUSE)
    NETWORK_DISCONNECT_STEAM_INUSE = 7,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_STEAM_TICKET)
    NETWORK_DISCONNECT_STEAM_TICKET = 8,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_STEAM_LOGON)
    NETWORK_DISCONNECT_STEAM_LOGON = 9,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_STEAM_AUTHCANCELLED)
    NETWORK_DISCONNECT_STEAM_AUTHCANCELLED = 10,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_STEAM_AUTHALREADYUSED)
    NETWORK_DISCONNECT_STEAM_AUTHALREADYUSED = 11,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_STEAM_AUTHINVALID)
    NETWORK_DISCONNECT_STEAM_AUTHINVALID = 12,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_STEAM_VACBANSTATE)
    NETWORK_DISCONNECT_STEAM_VACBANSTATE = 13,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_STEAM_LOGGED_IN_ELSEWHERE)
    NETWORK_DISCONNECT_STEAM_LOGGED_IN_ELSEWHERE = 14,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_STEAM_VAC_CHECK_TIMEDOUT)
    NETWORK_DISCONNECT_STEAM_VAC_CHECK_TIMEDOUT = 15,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_STEAM_DROPPED)
    NETWORK_DISCONNECT_STEAM_DROPPED = 16,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_STEAM_OWNERSHIP)
    NETWORK_DISCONNECT_STEAM_OWNERSHIP = 17,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_SERVERINFO_OVERFLOW)
    NETWORK_DISCONNECT_SERVERINFO_OVERFLOW = 18,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_TICKMSG_OVERFLOW)
    NETWORK_DISCONNECT_TICKMSG_OVERFLOW = 19,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_STRINGTABLEMSG_OVERFLOW)
    NETWORK_DISCONNECT_STRINGTABLEMSG_OVERFLOW = 20,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_DELTAENTMSG_OVERFLOW)
    NETWORK_DISCONNECT_DELTAENTMSG_OVERFLOW = 21,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_TEMPENTMSG_OVERFLOW)
    NETWORK_DISCONNECT_TEMPENTMSG_OVERFLOW = 22,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_SOUNDSMSG_OVERFLOW)
    NETWORK_DISCONNECT_SOUNDSMSG_OVERFLOW = 23,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_SNAPSHOTOVERFLOW)
    NETWORK_DISCONNECT_SNAPSHOTOVERFLOW = 24,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_SNAPSHOTERROR)
    NETWORK_DISCONNECT_SNAPSHOTERROR = 25,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_RELIABLEOVERFLOW)
    NETWORK_DISCONNECT_RELIABLEOVERFLOW = 26,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_BADDELTATICK)
    NETWORK_DISCONNECT_BADDELTATICK = 27,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_NOMORESPLITS)
    NETWORK_DISCONNECT_NOMORESPLITS = 28,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_TIMEDOUT)
    NETWORK_DISCONNECT_TIMEDOUT = 29,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_DISCONNECTED)
    NETWORK_DISCONNECT_DISCONNECTED = 30,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_LEAVINGSPLIT)
    NETWORK_DISCONNECT_LEAVINGSPLIT = 31,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_DIFFERENTCLASSTABLES)
    NETWORK_DISCONNECT_DIFFERENTCLASSTABLES = 32,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_BADRELAYPASSWORD)
    NETWORK_DISCONNECT_BADRELAYPASSWORD = 33,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_BADSPECTATORPASSWORD)
    NETWORK_DISCONNECT_BADSPECTATORPASSWORD = 34,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_HLTVRESTRICTED)
    NETWORK_DISCONNECT_HLTVRESTRICTED = 35,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_NOSPECTATORS)
    NETWORK_DISCONNECT_NOSPECTATORS = 36,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_HLTVUNAVAILABLE)
    NETWORK_DISCONNECT_HLTVUNAVAILABLE = 37,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_HLTVSTOP)
    NETWORK_DISCONNECT_HLTVSTOP = 38,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_KICKED)
    NETWORK_DISCONNECT_KICKED = 39,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_BANADDED)
    NETWORK_DISCONNECT_BANADDED = 40,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_KICKBANADDED)
    NETWORK_DISCONNECT_KICKBANADDED = 41,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_HLTVDIRECT)
    NETWORK_DISCONNECT_HLTVDIRECT = 42,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_PURESERVER_CLIENTEXTRA)
    NETWORK_DISCONNECT_PURESERVER_CLIENTEXTRA = 43,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_PURESERVER_MISMATCH)
    NETWORK_DISCONNECT_PURESERVER_MISMATCH = 44,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_USERCMD)
    NETWORK_DISCONNECT_USERCMD = 45,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_REJECTED_BY_GAME)
    NETWORK_DISCONNECT_REJECTED_BY_GAME = 46,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_MESSAGE_PARSE_ERROR)
    NETWORK_DISCONNECT_MESSAGE_PARSE_ERROR = 47,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_INVALID_MESSAGE_ERROR)
    NETWORK_DISCONNECT_INVALID_MESSAGE_ERROR = 48,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_BAD_SERVER_PASSWORD)
    NETWORK_DISCONNECT_BAD_SERVER_PASSWORD = 49,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_DIRECT_CONNECT_RESERVATION)
    NETWORK_DISCONNECT_DIRECT_CONNECT_RESERVATION = 50,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_CONNECTION_FAILURE)
    NETWORK_DISCONNECT_CONNECTION_FAILURE = 51,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_NO_PEER_GROUP_HANDLERS)
    NETWORK_DISCONNECT_NO_PEER_GROUP_HANDLERS = 52,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_RECONNECTION)
    NETWORK_DISCONNECT_RECONNECTION = 53,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_LOOPSHUTDOWN)
    NETWORK_DISCONNECT_LOOPSHUTDOWN = 54,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_LOOPDEACTIVATE)
    NETWORK_DISCONNECT_LOOPDEACTIVATE = 55,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_HOST_ENDGAME)
    NETWORK_DISCONNECT_HOST_ENDGAME = 56,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_LOOP_LEVELLOAD_ACTIVATE)
    NETWORK_DISCONNECT_LOOP_LEVELLOAD_ACTIVATE = 57,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_CREATE_SERVER_FAILED)
    NETWORK_DISCONNECT_CREATE_SERVER_FAILED = 58,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_EXITING)
    NETWORK_DISCONNECT_EXITING = 59,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_REQUEST_HOSTSTATE_IDLE)
    NETWORK_DISCONNECT_REQUEST_HOSTSTATE_IDLE = 60,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_REQUEST_HOSTSTATE_HLTVRELAY)
    NETWORK_DISCONNECT_REQUEST_HOSTSTATE_HLTVRELAY = 61,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_CLIENT_CONSISTENCY_FAIL)
    NETWORK_DISCONNECT_CLIENT_CONSISTENCY_FAIL = 62,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_CLIENT_UNABLE_TO_CRC_MAP)
    NETWORK_DISCONNECT_CLIENT_UNABLE_TO_CRC_MAP = 63,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_CLIENT_NO_MAP)
    NETWORK_DISCONNECT_CLIENT_NO_MAP = 64,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_CLIENT_DIFFERENT_MAP)
    NETWORK_DISCONNECT_CLIENT_DIFFERENT_MAP = 65,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_SERVER_REQUIRES_STEAM)
    NETWORK_DISCONNECT_SERVER_REQUIRES_STEAM = 66,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_STEAM_DENY_MISC)
    NETWORK_DISCONNECT_STEAM_DENY_MISC = 67,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_STEAM_DENY_BAD_ANTI_CHEAT)
    NETWORK_DISCONNECT_STEAM_DENY_BAD_ANTI_CHEAT = 68,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_SERVER_SHUTDOWN)
    NETWORK_DISCONNECT_SERVER_SHUTDOWN = 69,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_SPLITPACKET_SEND_OVERFLOW)
    NETWORK_DISCONNECT_SPLITPACKET_SEND_OVERFLOW = 70,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_REPLAY_INCOMPATIBLE)
    NETWORK_DISCONNECT_REPLAY_INCOMPATIBLE = 71,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_CONNECT_REQUEST_TIMEDOUT)
    NETWORK_DISCONNECT_CONNECT_REQUEST_TIMEDOUT = 72,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_SERVER_INCOMPATIBLE)
    NETWORK_DISCONNECT_SERVER_INCOMPATIBLE = 73,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_LOCALPROBLEM_MANYRELAYS)
    NETWORK_DISCONNECT_LOCALPROBLEM_MANYRELAYS = 74,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_LOCALPROBLEM_HOSTEDSERVERPRIMARYRELAY)
    NETWORK_DISCONNECT_LOCALPROBLEM_HOSTEDSERVERPRIMARYRELAY = 75,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_LOCALPROBLEM_NETWORKCONFIG)
    NETWORK_DISCONNECT_LOCALPROBLEM_NETWORKCONFIG = 76,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_LOCALPROBLEM_OTHER)
    NETWORK_DISCONNECT_LOCALPROBLEM_OTHER = 77,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_REMOTE_TIMEOUT)
    NETWORK_DISCONNECT_REMOTE_TIMEOUT = 79,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_REMOTE_TIMEOUT_CONNECTING)
    NETWORK_DISCONNECT_REMOTE_TIMEOUT_CONNECTING = 80,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_REMOTE_OTHER)
    NETWORK_DISCONNECT_REMOTE_OTHER = 81,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_REMOTE_BADCRYPT)
    NETWORK_DISCONNECT_REMOTE_BADCRYPT = 82,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_REMOTE_CERTNOTTRUSTED)
    NETWORK_DISCONNECT_REMOTE_CERTNOTTRUSTED = 83,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_UNUSUAL)
    NETWORK_DISCONNECT_UNUSUAL = 84,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_INTERNAL_ERROR)
    NETWORK_DISCONNECT_INTERNAL_ERROR = 85,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_REJECT_BADCHALLENGE)
    NETWORK_DISCONNECT_REJECT_BADCHALLENGE = 128,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_REJECT_NOLOBBY)
    NETWORK_DISCONNECT_REJECT_NOLOBBY = 129,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_REJECT_BACKGROUND_MAP)
    NETWORK_DISCONNECT_REJECT_BACKGROUND_MAP = 130,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_REJECT_SINGLE_PLAYER)
    NETWORK_DISCONNECT_REJECT_SINGLE_PLAYER = 131,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_REJECT_HIDDEN_GAME)
    NETWORK_DISCONNECT_REJECT_HIDDEN_GAME = 132,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_REJECT_LANRESTRICT)
    NETWORK_DISCONNECT_REJECT_LANRESTRICT = 133,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_REJECT_BADPASSWORD)
    NETWORK_DISCONNECT_REJECT_BADPASSWORD = 134,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_REJECT_SERVERFULL)
    NETWORK_DISCONNECT_REJECT_SERVERFULL = 135,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_REJECT_INVALIDRESERVATION)
    NETWORK_DISCONNECT_REJECT_INVALIDRESERVATION = 136,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_REJECT_FAILEDCHANNEL)
    NETWORK_DISCONNECT_REJECT_FAILEDCHANNEL = 137,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_REJECT_CONNECT_FROM_LOBBY)
    NETWORK_DISCONNECT_REJECT_CONNECT_FROM_LOBBY = 138,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_REJECT_RESERVED_FOR_LOBBY)
    NETWORK_DISCONNECT_REJECT_RESERVED_FOR_LOBBY = 139,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_REJECT_INVALIDKEYLENGTH)
    NETWORK_DISCONNECT_REJECT_INVALIDKEYLENGTH = 140,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_REJECT_OLDPROTOCOL)
    NETWORK_DISCONNECT_REJECT_OLDPROTOCOL = 141,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_REJECT_NEWPROTOCOL)
    NETWORK_DISCONNECT_REJECT_NEWPROTOCOL = 142,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_REJECT_INVALIDCONNECTION)
    NETWORK_DISCONNECT_REJECT_INVALIDCONNECTION = 143,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_REJECT_INVALIDCERTLEN)
    NETWORK_DISCONNECT_REJECT_INVALIDCERTLEN = 144,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_REJECT_INVALIDSTEAMCERTLEN)
    NETWORK_DISCONNECT_REJECT_INVALIDSTEAMCERTLEN = 145,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_REJECT_STEAM)
    NETWORK_DISCONNECT_REJECT_STEAM = 146,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_REJECT_SERVERAUTHDISABLED)
    NETWORK_DISCONNECT_REJECT_SERVERAUTHDISABLED = 147,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_REJECT_SERVERCDKEYAUTHINVALID)
    NETWORK_DISCONNECT_REJECT_SERVERCDKEYAUTHINVALID = 148,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_REJECT_BANNED)
    NETWORK_DISCONNECT_REJECT_BANNED = 149,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_KICKED_TEAMKILLING)
    NETWORK_DISCONNECT_KICKED_TEAMKILLING = 150,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_KICKED_TK_START)
    NETWORK_DISCONNECT_KICKED_TK_START = 151,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_KICKED_UNTRUSTEDACCOUNT)
    NETWORK_DISCONNECT_KICKED_UNTRUSTEDACCOUNT = 152,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_KICKED_CONVICTEDACCOUNT)
    NETWORK_DISCONNECT_KICKED_CONVICTEDACCOUNT = 153,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_KICKED_COMPETITIVECOOLDOWN)
    NETWORK_DISCONNECT_KICKED_COMPETITIVECOOLDOWN = 154,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_KICKED_TEAMHURTING)
    NETWORK_DISCONNECT_KICKED_TEAMHURTING = 155,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_KICKED_HOSTAGEKILLING)
    NETWORK_DISCONNECT_KICKED_HOSTAGEKILLING = 156,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_KICKED_VOTEDOFF)
    NETWORK_DISCONNECT_KICKED_VOTEDOFF = 157,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_KICKED_IDLE)
    NETWORK_DISCONNECT_KICKED_IDLE = 158,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_KICKED_SUICIDE)
    NETWORK_DISCONNECT_KICKED_SUICIDE = 159,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_KICKED_NOSTEAMLOGIN)
    NETWORK_DISCONNECT_KICKED_NOSTEAMLOGIN = 160,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_KICKED_NOSTEAMTICKET)
    NETWORK_DISCONNECT_KICKED_NOSTEAMTICKET = 161,
}

impl ::protobuf::Enum for ENetworkDisconnectionReason {
    const NAME: &'static str = "ENetworkDisconnectionReason";

    fn value(&self) -> i32 {
        *self as i32
    }

    fn from_i32(value: i32) -> ::std::option::Option<ENetworkDisconnectionReason> {
        match value {
            0 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_INVALID),
            1 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_SHUTDOWN),
            2 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_DISCONNECT_BY_USER),
            3 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_DISCONNECT_BY_SERVER),
            4 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_LOST),
            5 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_OVERFLOW),
            6 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_STEAM_BANNED),
            7 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_STEAM_INUSE),
            8 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_STEAM_TICKET),
            9 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_STEAM_LOGON),
            10 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_STEAM_AUTHCANCELLED),
            11 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_STEAM_AUTHALREADYUSED),
            12 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_STEAM_AUTHINVALID),
            13 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_STEAM_VACBANSTATE),
            14 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_STEAM_LOGGED_IN_ELSEWHERE),
            15 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_STEAM_VAC_CHECK_TIMEDOUT),
            16 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_STEAM_DROPPED),
            17 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_STEAM_OWNERSHIP),
            18 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_SERVERINFO_OVERFLOW),
            19 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_TICKMSG_OVERFLOW),
            20 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_STRINGTABLEMSG_OVERFLOW),
            21 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_DELTAENTMSG_OVERFLOW),
            22 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_TEMPENTMSG_OVERFLOW),
            23 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_SOUNDSMSG_OVERFLOW),
            24 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_SNAPSHOTOVERFLOW),
            25 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_SNAPSHOTERROR),
            26 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_RELIABLEOVERFLOW),
            27 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_BADDELTATICK),
            28 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_NOMORESPLITS),
            29 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_TIMEDOUT),
            30 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_DISCONNECTED),
            31 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_LEAVINGSPLIT),
            32 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_DIFFERENTCLASSTABLES),
            33 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_BADRELAYPASSWORD),
            34 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_BADSPECTATORPASSWORD),
            35 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_HLTVRESTRICTED),
            36 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_NOSPECTATORS),
            37 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_HLTVUNAVAILABLE),
            38 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_HLTVSTOP),
            39 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_KICKED),
            40 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_BANADDED),
            41 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_KICKBANADDED),
            42 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_HLTVDIRECT),
            43 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_PURESERVER_CLIENTEXTRA),
            44 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_PURESERVER_MISMATCH),
            45 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_USERCMD),
            46 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECTED_BY_GAME),
            47 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_MESSAGE_PARSE_ERROR),
            48 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_INVALID_MESSAGE_ERROR),
            49 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_BAD_SERVER_PASSWORD),
            50 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_DIRECT_CONNECT_RESERVATION),
            51 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_CONNECTION_FAILURE),
            52 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_NO_PEER_GROUP_HANDLERS),
            53 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_RECONNECTION),
            54 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_LOOPSHUTDOWN),
            55 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_LOOPDEACTIVATE),
            56 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_HOST_ENDGAME),
            57 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_LOOP_LEVELLOAD_ACTIVATE),
            58 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_CREATE_SERVER_FAILED),
            59 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_EXITING),
            60 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_REQUEST_HOSTSTATE_IDLE),
            61 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_REQUEST_HOSTSTATE_HLTVRELAY),
            62 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_CLIENT_CONSISTENCY_FAIL),
            63 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_CLIENT_UNABLE_TO_CRC_MAP),
            64 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_CLIENT_NO_MAP),
            65 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_CLIENT_DIFFERENT_MAP),
            66 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_SERVER_REQUIRES_STEAM),
            67 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_STEAM_DENY_MISC),
            68 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_STEAM_DENY_BAD_ANTI_CHEAT),
            69 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_SERVER_SHUTDOWN),
            70 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_SPLITPACKET_SEND_OVERFLOW),
            71 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_REPLAY_INCOMPATIBLE),
            72 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_CONNECT_REQUEST_TIMEDOUT),
            73 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_SERVER_INCOMPATIBLE),
            74 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_LOCALPROBLEM_MANYRELAYS),
            75 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_LOCALPROBLEM_HOSTEDSERVERPRIMARYRELAY),
            76 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_LOCALPROBLEM_NETWORKCONFIG),
            77 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_LOCALPROBLEM_OTHER),
            79 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_REMOTE_TIMEOUT),
            80 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_REMOTE_TIMEOUT_CONNECTING),
            81 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_REMOTE_OTHER),
            82 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_REMOTE_BADCRYPT),
            83 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_REMOTE_CERTNOTTRUSTED),
            84 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_UNUSUAL),
            85 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_INTERNAL_ERROR),
            128 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_BADCHALLENGE),
            129 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_NOLOBBY),
            130 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_BACKGROUND_MAP),
            131 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_SINGLE_PLAYER),
            132 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_HIDDEN_GAME),
            133 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_LANRESTRICT),
            134 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_BADPASSWORD),
            135 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_SERVERFULL),
            136 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_INVALIDRESERVATION),
            137 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_FAILEDCHANNEL),
            138 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_CONNECT_FROM_LOBBY),
            139 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_RESERVED_FOR_LOBBY),
            140 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_INVALIDKEYLENGTH),
            141 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_OLDPROTOCOL),
            142 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_NEWPROTOCOL),
            143 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_INVALIDCONNECTION),
            144 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_INVALIDCERTLEN),
            145 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_INVALIDSTEAMCERTLEN),
            146 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_STEAM),
            147 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_SERVERAUTHDISABLED),
            148 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_SERVERCDKEYAUTHINVALID),
            149 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_BANNED),
            150 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_KICKED_TEAMKILLING),
            151 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_KICKED_TK_START),
            152 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_KICKED_UNTRUSTEDACCOUNT),
            153 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_KICKED_CONVICTEDACCOUNT),
            154 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_KICKED_COMPETITIVECOOLDOWN),
            155 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_KICKED_TEAMHURTING),
            156 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_KICKED_HOSTAGEKILLING),
            157 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_KICKED_VOTEDOFF),
            158 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_KICKED_IDLE),
            159 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_KICKED_SUICIDE),
            160 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_KICKED_NOSTEAMLOGIN),
            161 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_KICKED_NOSTEAMTICKET),
            _ => ::std::option::Option::None
        }
    }

    const VALUES: &'static [ENetworkDisconnectionReason] = &[
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_INVALID,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_SHUTDOWN,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_DISCONNECT_BY_USER,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_DISCONNECT_BY_SERVER,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_LOST,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_OVERFLOW,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_STEAM_BANNED,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_STEAM_INUSE,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_STEAM_TICKET,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_STEAM_LOGON,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_STEAM_AUTHCANCELLED,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_STEAM_AUTHALREADYUSED,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_STEAM_AUTHINVALID,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_STEAM_VACBANSTATE,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_STEAM_LOGGED_IN_ELSEWHERE,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_STEAM_VAC_CHECK_TIMEDOUT,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_STEAM_DROPPED,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_STEAM_OWNERSHIP,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_SERVERINFO_OVERFLOW,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_TICKMSG_OVERFLOW,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_STRINGTABLEMSG_OVERFLOW,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_DELTAENTMSG_OVERFLOW,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_TEMPENTMSG_OVERFLOW,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_SOUNDSMSG_OVERFLOW,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_SNAPSHOTOVERFLOW,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_SNAPSHOTERROR,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_RELIABLEOVERFLOW,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_BADDELTATICK,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_NOMORESPLITS,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_TIMEDOUT,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_DISCONNECTED,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_LEAVINGSPLIT,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_DIFFERENTCLASSTABLES,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_BADRELAYPASSWORD,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_BADSPECTATORPASSWORD,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_HLTVRESTRICTED,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_NOSPECTATORS,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_HLTVUNAVAILABLE,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_HLTVSTOP,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_KICKED,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_BANADDED,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_KICKBANADDED,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_HLTVDIRECT,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_PURESERVER_CLIENTEXTRA,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_PURESERVER_MISMATCH,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_USERCMD,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECTED_BY_GAME,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_MESSAGE_PARSE_ERROR,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_INVALID_MESSAGE_ERROR,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_BAD_SERVER_PASSWORD,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_DIRECT_CONNECT_RESERVATION,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_CONNECTION_FAILURE,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_NO_PEER_GROUP_HANDLERS,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_RECONNECTION,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_LOOPSHUTDOWN,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_LOOPDEACTIVATE,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_HOST_ENDGAME,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_LOOP_LEVELLOAD_ACTIVATE,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_CREATE_SERVER_FAILED,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_EXITING,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_REQUEST_HOSTSTATE_IDLE,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_REQUEST_HOSTSTATE_HLTVRELAY,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_CLIENT_CONSISTENCY_FAIL,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_CLIENT_UNABLE_TO_CRC_MAP,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_CLIENT_NO_MAP,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_CLIENT_DIFFERENT_MAP,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_SERVER_REQUIRES_STEAM,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_STEAM_DENY_MISC,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_STEAM_DENY_BAD_ANTI_CHEAT,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_SERVER_SHUTDOWN,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_SPLITPACKET_SEND_OVERFLOW,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_REPLAY_INCOMPATIBLE,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_CONNECT_REQUEST_TIMEDOUT,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_SERVER_INCOMPATIBLE,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_LOCALPROBLEM_MANYRELAYS,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_LOCALPROBLEM_HOSTEDSERVERPRIMARYRELAY,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_LOCALPROBLEM_NETWORKCONFIG,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_LOCALPROBLEM_OTHER,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_REMOTE_TIMEOUT,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_REMOTE_TIMEOUT_CONNECTING,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_REMOTE_OTHER,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_REMOTE_BADCRYPT,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_REMOTE_CERTNOTTRUSTED,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_UNUSUAL,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_INTERNAL_ERROR,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_BADCHALLENGE,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_NOLOBBY,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_BACKGROUND_MAP,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_SINGLE_PLAYER,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_HIDDEN_GAME,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_LANRESTRICT,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_BADPASSWORD,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_SERVERFULL,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_INVALIDRESERVATION,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_FAILEDCHANNEL,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_CONNECT_FROM_LOBBY,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_RESERVED_FOR_LOBBY,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_INVALIDKEYLENGTH,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_OLDPROTOCOL,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_NEWPROTOCOL,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_INVALIDCONNECTION,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_INVALIDCERTLEN,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_INVALIDSTEAMCERTLEN,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_STEAM,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_SERVERAUTHDISABLED,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_SERVERCDKEYAUTHINVALID,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_BANNED,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_KICKED_TEAMKILLING,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_KICKED_TK_START,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_KICKED_UNTRUSTEDACCOUNT,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_KICKED_CONVICTEDACCOUNT,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_KICKED_COMPETITIVECOOLDOWN,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_KICKED_TEAMHURTING,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_KICKED_HOSTAGEKILLING,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_KICKED_VOTEDOFF,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_KICKED_IDLE,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_KICKED_SUICIDE,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_KICKED_NOSTEAMLOGIN,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_KICKED_NOSTEAMTICKET,
    ];
}

impl ::protobuf::EnumFull for ENetworkDisconnectionReason {
    fn enum_descriptor() -> ::protobuf::reflect::EnumDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::EnumDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().enum_by_package_relative_name("ENetworkDisconnectionReason").unwrap()).clone()
    }

    fn descriptor(&self) -> ::protobuf::reflect::EnumValueDescriptor {
        let index = match self {
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_INVALID => 0,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_SHUTDOWN => 1,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_DISCONNECT_BY_USER => 2,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_DISCONNECT_BY_SERVER => 3,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_LOST => 4,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_OVERFLOW => 5,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_STEAM_BANNED => 6,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_STEAM_INUSE => 7,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_STEAM_TICKET => 8,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_STEAM_LOGON => 9,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_STEAM_AUTHCANCELLED => 10,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_STEAM_AUTHALREADYUSED => 11,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_STEAM_AUTHINVALID => 12,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_STEAM_VACBANSTATE => 13,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_STEAM_LOGGED_IN_ELSEWHERE => 14,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_STEAM_VAC_CHECK_TIMEDOUT => 15,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_STEAM_DROPPED => 16,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_STEAM_OWNERSHIP => 17,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_SERVERINFO_OVERFLOW => 18,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_TICKMSG_OVERFLOW => 19,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_STRINGTABLEMSG_OVERFLOW => 20,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_DELTAENTMSG_OVERFLOW => 21,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_TEMPENTMSG_OVERFLOW => 22,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_SOUNDSMSG_OVERFLOW => 23,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_SNAPSHOTOVERFLOW => 24,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_SNAPSHOTERROR => 25,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_RELIABLEOVERFLOW => 26,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_BADDELTATICK => 27,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_NOMORESPLITS => 28,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_TIMEDOUT => 29,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_DISCONNECTED => 30,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_LEAVINGSPLIT => 31,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_DIFFERENTCLASSTABLES => 32,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_BADRELAYPASSWORD => 33,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_BADSPECTATORPASSWORD => 34,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_HLTVRESTRICTED => 35,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_NOSPECTATORS => 36,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_HLTVUNAVAILABLE => 37,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_HLTVSTOP => 38,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_KICKED => 39,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_BANADDED => 40,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_KICKBANADDED => 41,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_HLTVDIRECT => 42,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_PURESERVER_CLIENTEXTRA => 43,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_PURESERVER_MISMATCH => 44,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_USERCMD => 45,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECTED_BY_GAME => 46,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_MESSAGE_PARSE_ERROR => 47,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_INVALID_MESSAGE_ERROR => 48,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_BAD_SERVER_PASSWORD => 49,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_DIRECT_CONNECT_RESERVATION => 50,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_CONNECTION_FAILURE => 51,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_NO_PEER_GROUP_HANDLERS => 52,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_RECONNECTION => 53,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_LOOPSHUTDOWN => 54,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_LOOPDEACTIVATE => 55,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_HOST_ENDGAME => 56,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_LOOP_LEVELLOAD_ACTIVATE => 57,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_CREATE_SERVER_FAILED => 58,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_EXITING => 59,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_REQUEST_HOSTSTATE_IDLE => 60,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_REQUEST_HOSTSTATE_HLTVRELAY => 61,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_CLIENT_CONSISTENCY_FAIL => 62,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_CLIENT_UNABLE_TO_CRC_MAP => 63,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_CLIENT_NO_MAP => 64,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_CLIENT_DIFFERENT_MAP => 65,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_SERVER_REQUIRES_STEAM => 66,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_STEAM_DENY_MISC => 67,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_STEAM_DENY_BAD_ANTI_CHEAT => 68,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_SERVER_SHUTDOWN => 69,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_SPLITPACKET_SEND_OVERFLOW => 70,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_REPLAY_INCOMPATIBLE => 71,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_CONNECT_REQUEST_TIMEDOUT => 72,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_SERVER_INCOMPATIBLE => 73,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_LOCALPROBLEM_MANYRELAYS => 74,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_LOCALPROBLEM_HOSTEDSERVERPRIMARYRELAY => 75,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_LOCALPROBLEM_NETWORKCONFIG => 76,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_LOCALPROBLEM_OTHER => 77,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_REMOTE_TIMEOUT => 78,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_REMOTE_TIMEOUT_CONNECTING => 79,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_REMOTE_OTHER => 80,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_REMOTE_BADCRYPT => 81,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_REMOTE_CERTNOTTRUSTED => 82,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_UNUSUAL => 83,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_INTERNAL_ERROR => 84,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_BADCHALLENGE => 85,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_NOLOBBY => 86,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_BACKGROUND_MAP => 87,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_SINGLE_PLAYER => 88,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_HIDDEN_GAME => 89,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_LANRESTRICT => 90,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_BADPASSWORD => 91,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_SERVERFULL => 92,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_INVALIDRESERVATION => 93,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_FAILEDCHANNEL => 94,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_CONNECT_FROM_LOBBY => 95,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_RESERVED_FOR_LOBBY => 96,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_INVALIDKEYLENGTH => 97,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_OLDPROTOCOL => 98,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_NEWPROTOCOL => 99,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_INVALIDCONNECTION => 100,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_INVALIDCERTLEN => 101,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_INVALIDSTEAMCERTLEN => 102,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_STEAM => 103,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_SERVERAUTHDISABLED => 104,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_SERVERCDKEYAUTHINVALID => 105,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_BANNED => 106,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_KICKED_TEAMKILLING => 107,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_KICKED_TK_START => 108,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_KICKED_UNTRUSTEDACCOUNT => 109,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_KICKED_CONVICTEDACCOUNT => 110,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_KICKED_COMPETITIVECOOLDOWN => 111,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_KICKED_TEAMHURTING => 112,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_KICKED_HOSTAGEKILLING => 113,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_KICKED_VOTEDOFF => 114,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_KICKED_IDLE => 115,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_KICKED_SUICIDE => 116,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_KICKED_NOSTEAMLOGIN => 117,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_KICKED_NOSTEAMTICKET => 118,
        };
        Self::enum_descriptor().value_by_index(index)
    }
}

impl ::std::default::Default for ENetworkDisconnectionReason {
    fn default() -> Self {
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_INVALID
    }
}

impl ENetworkDisconnectionReason {
    fn generated_enum_descriptor_data() -> ::protobuf::reflect::GeneratedEnumDescriptorData {
        ::protobuf::reflect::GeneratedEnumDescriptorData::new::<ENetworkDisconnectionReason>("ENetworkDisconnectionReason")
    }
}

/// Extension fields
pub mod exts {

    pub const network_connection_token: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::EnumValueOptions, ::std::string::String> = ::protobuf::ext::ExtFieldOptional::new(50500, ::protobuf::descriptor::field_descriptor_proto::Type::TYPE_STRING);
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x18network_connection.proto\x1a\x20google/protobuf/descriptor.proto*\
    \xb2K\n\x1bENetworkDisconnectionReason\x12\x1e\n\x1aNETWORK_DISCONNECT_I\
    NVALID\x10\0\x12\x1f\n\x1bNETWORK_DISCONNECT_SHUTDOWN\x10\x01\x12F\n%NET\
    WORK_DISCONNECT_DISCONNECT_BY_USER\x10\x02\x1a\x1b\xa2\xd4\x18\x17#GameU\
    I_Disconnect_User\x12J\n'NETWORK_DISCONNECT_DISCONNECT_BY_SERVER\x10\x03\
    \x1a\x1d\xa2\xd4\x18\x19#GameUI_Disconnect_Server\x12B\n\x17NETWORK_DISC\
    ONNECT_LOST\x10\x04\x1a%\xa2\xd4\x18!#GameUI_Disconnect_ConnectionLost\
    \x12J\n\x1bNETWORK_DISCONNECT_OVERFLOW\x10\x05\x1a)\xa2\xd4\x18%#GameUI_\
    Disconnect_ConnectionOverflow\x12I\n\x1fNETWORK_DISCONNECT_STEAM_BANNED\
    \x10\x06\x1a$\xa2\xd4\x18\x20#GameUI_Disconnect_SteamIDBanned\x12G\n\x1e\
    NETWORK_DISCONNECT_STEAM_INUSE\x10\x07\x1a#\xa2\xd4\x18\x1f#GameUI_Disco\
    nnect_SteamIDInUse\x12G\n\x1fNETWORK_DISCONNECT_STEAM_TICKET\x10\x08\x1a\
    \"\xa2\xd4\x18\x1e#GameUI_Disconnect_SteamTicket\x12E\n\x1eNETWORK_DISCO\
    NNECT_STEAM_LOGON\x10\t\x1a!\xa2\xd4\x18\x1d#GameUI_Disconnect_SteamLogo\
    n\x12M\n&NETWORK_DISCONNECT_STEAM_AUTHCANCELLED\x10\n\x1a!\xa2\xd4\x18\
    \x1d#GameUI_Disconnect_SteamLogon\x12O\n(NETWORK_DISCONNECT_STEAM_AUTHAL\
    READYUSED\x10\x0b\x1a!\xa2\xd4\x18\x1d#GameUI_Disconnect_SteamLogon\x12K\
    \n$NETWORK_DISCONNECT_STEAM_AUTHINVALID\x10\x0c\x1a!\xa2\xd4\x18\x1d#Gam\
    eUI_Disconnect_SteamLogon\x12I\n$NETWORK_DISCONNECT_STEAM_VACBANSTATE\
    \x10\r\x1a\x1f\xa2\xd4\x18\x1b#GameUI_Disconnect_SteamVAC\x12S\n,NETWORK\
    _DISCONNECT_STEAM_LOGGED_IN_ELSEWHERE\x10\x0e\x1a!\xa2\xd4\x18\x1d#GameU\
    I_Disconnect_SteamInUse\x12T\n+NETWORK_DISCONNECT_STEAM_VAC_CHECK_TIMEDO\
    UT\x10\x0f\x1a#\xa2\xd4\x18\x1f#GameUI_Disconnect_SteamTimeOut\x12I\n\
    \x20NETWORK_DISCONNECT_STEAM_DROPPED\x10\x10\x1a#\xa2\xd4\x18\x1f#GameUI\
    _Disconnect_SteamDropped\x12M\n\"NETWORK_DISCONNECT_STEAM_OWNERSHIP\x10\
    \x11\x1a%\xa2\xd4\x18!#GameUI_Disconnect_SteamOwnership\x12U\n&NETWORK_D\
    ISCONNECT_SERVERINFO_OVERFLOW\x10\x12\x1a)\xa2\xd4\x18%#GameUI_Disconnec\
    t_ServerInfoOverflow\x12K\n#NETWORK_DISCONNECT_TICKMSG_OVERFLOW\x10\x13\
    \x1a\"\xa2\xd4\x18\x1e#GameUI_Disconnect_TickMessage\x12Y\n*NETWORK_DISC\
    ONNECT_STRINGTABLEMSG_OVERFLOW\x10\x14\x1a)\xa2\xd4\x18%#GameUI_Disconne\
    ct_StringTableMessage\x12S\n'NETWORK_DISCONNECT_DELTAENTMSG_OVERFLOW\x10\
    \x15\x1a&\xa2\xd4\x18\"#GameUI_Disconnect_DeltaEntMessage\x12Q\n&NETWORK\
    _DISCONNECT_TEMPENTMSG_OVERFLOW\x10\x16\x1a%\xa2\xd4\x18!#GameUI_Disconn\
    ect_TempEntMessage\x12O\n%NETWORK_DISCONNECT_SOUNDSMSG_OVERFLOW\x10\x17\
    \x1a$\xa2\xd4\x18\x20#GameUI_Disconnect_SoundsMessage\x12P\n#NETWORK_DIS\
    CONNECT_SNAPSHOTOVERFLOW\x10\x18\x1a'\xa2\xd4\x18##GameUI_Disconnect_Sna\
    pshotOverflow\x12J\n\x20NETWORK_DISCONNECT_SNAPSHOTERROR\x10\x19\x1a$\
    \xa2\xd4\x18\x20#GameUI_Disconnect_SnapshotError\x12P\n#NETWORK_DISCONNE\
    CT_RELIABLEOVERFLOW\x10\x1a\x1a'\xa2\xd4\x18##GameUI_Disconnect_Reliable\
    Overflow\x12N\n\x1fNETWORK_DISCONNECT_BADDELTATICK\x10\x1b\x1a)\xa2\xd4\
    \x18%#GameUI_Disconnect_BadClientDeltaTick\x12H\n\x1fNETWORK_DISCONNECT_\
    NOMORESPLITS\x10\x1c\x1a#\xa2\xd4\x18\x1f#GameUI_Disconnect_NoMoreSplits\
    \x12@\n\x1bNETWORK_DISCONNECT_TIMEDOUT\x10\x1d\x1a\x1f\xa2\xd4\x18\x1b#G\
    ameUI_Disconnect_TimedOut\x12H\n\x1fNETWORK_DISCONNECT_DISCONNECTED\x10\
    \x1e\x1a#\xa2\xd4\x18\x1f#GameUI_Disconnect_Disconnected\x12H\n\x1fNETWO\
    RK_DISCONNECT_LEAVINGSPLIT\x10\x1f\x1a#\xa2\xd4\x18\x1f#GameUI_Disconnec\
    t_LeavingSplit\x12X\n'NETWORK_DISCONNECT_DIFFERENTCLASSTABLES\x10\x20\
    \x1a+\xa2\xd4\x18'#GameUI_Disconnect_DifferentClassTables\x12P\n#NETWORK\
    _DISCONNECT_BADRELAYPASSWORD\x10!\x1a'\xa2\xd4\x18##GameUI_Disconnect_Ba\
    dRelayPassword\x12X\n'NETWORK_DISCONNECT_BADSPECTATORPASSWORD\x10\"\x1a+\
    \xa2\xd4\x18'#GameUI_Disconnect_BadSpectatorPassword\x12L\n!NETWORK_DISC\
    ONNECT_HLTVRESTRICTED\x10#\x1a%\xa2\xd4\x18!#GameUI_Disconnect_HLTVRestr\
    icted\x12H\n\x1fNETWORK_DISCONNECT_NOSPECTATORS\x10$\x1a#\xa2\xd4\x18\
    \x1f#GameUI_Disconnect_NoSpectators\x12N\n\"NETWORK_DISCONNECT_HLTVUNAVA\
    ILABLE\x10%\x1a&\xa2\xd4\x18\"#GameUI_Disconnect_HLTVUnavailable\x12@\n\
    \x1bNETWORK_DISCONNECT_HLTVSTOP\x10&\x1a\x1f\xa2\xd4\x18\x1b#GameUI_Disc\
    onnect_HLTVStop\x12<\n\x19NETWORK_DISCONNECT_KICKED\x10'\x1a\x1d\xa2\xd4\
    \x18\x19#GameUI_Disconnect_Kicked\x12@\n\x1bNETWORK_DISCONNECT_BANADDED\
    \x10(\x1a\x1f\xa2\xd4\x18\x1b#GameUI_Disconnect_BanAdded\x12H\n\x1fNETWO\
    RK_DISCONNECT_KICKBANADDED\x10)\x1a#\xa2\xd4\x18\x1f#GameUI_Disconnect_K\
    ickBanAdded\x12D\n\x1dNETWORK_DISCONNECT_HLTVDIRECT\x10*\x1a!\xa2\xd4\
    \x18\x1d#GameUI_Disconnect_HLTVDirect\x12\\\n)NETWORK_DISCONNECT_PURESER\
    VER_CLIENTEXTRA\x10+\x1a-\xa2\xd4\x18)#GameUI_Disconnect_PureServer_Clie\
    ntExtra\x12V\n&NETWORK_DISCONNECT_PURESERVER_MISMATCH\x10,\x1a*\xa2\xd4\
    \x18&#GameUI_Disconnect_PureServer_Mismatch\x12>\n\x1aNETWORK_DISCONNECT\
    _USERCMD\x10-\x1a\x1e\xa2\xd4\x18\x1a#GameUI_Disconnect_UserCmd\x12N\n#N\
    ETWORK_DISCONNECT_REJECTED_BY_GAME\x10.\x1a%\xa2\xd4\x18!#GameUI_Disconn\
    ect_RejectedByGame\x12T\n&NETWORK_DISCONNECT_MESSAGE_PARSE_ERROR\x10/\
    \x1a(\xa2\xd4\x18$#GameUI_Disconnect_MessageParseError\x12X\n(NETWORK_DI\
    SCONNECT_INVALID_MESSAGE_ERROR\x100\x1a*\xa2\xd4\x18&#GameUI_Disconnect_\
    InvalidMessageError\x12T\n&NETWORK_DISCONNECT_BAD_SERVER_PASSWORD\x101\
    \x1a(\xa2\xd4\x18$#GameUI_Disconnect_BadServerPassword\x121\n-NETWORK_DI\
    SCONNECT_DIRECT_CONNECT_RESERVATION\x102\x12S\n%NETWORK_DISCONNECT_CONNE\
    CTION_FAILURE\x103\x1a(\xa2\xd4\x18$#GameUI_Disconnect_ConnectionFailure\
    \x12Y\n)NETWORK_DISCONNECT_NO_PEER_GROUP_HANDLERS\x104\x1a*\xa2\xd4\x18&\
    #GameUI_Disconnect_NoPeerGroupHandlers\x12#\n\x1fNETWORK_DISCONNECT_RECO\
    NNECTION\x105\x12H\n\x1fNETWORK_DISCONNECT_LOOPSHUTDOWN\x106\x1a#\xa2\
    \xd4\x18\x1f#GameUI_Disconnect_LoopShutdown\x12L\n!NETWORK_DISCONNECT_LO\
    OPDEACTIVATE\x107\x1a%\xa2\xd4\x18!#GameUI_Disconnect_LoopDeactivate\x12\
    H\n\x1fNETWORK_DISCONNECT_HOST_ENDGAME\x108\x1a#\xa2\xd4\x18\x1f#GameUI_\
    Disconnect_Host_EndGame\x12\\\n*NETWORK_DISCONNECT_LOOP_LEVELLOAD_ACTIVA\
    TE\x109\x1a,\xa2\xd4\x18(#GameUI_Disconnect_LoopLevelLoadActivate\x12V\n\
    'NETWORK_DISCONNECT_CREATE_SERVER_FAILED\x10:\x1a)\xa2\xd4\x18%#GameUI_D\
    isconnect_CreateServerFailed\x12D\n\x1aNETWORK_DISCONNECT_EXITING\x10;\
    \x1a$\xa2\xd4\x18\x20#GameUI_Disconnect_ExitingEngine\x12T\n)NETWORK_DIS\
    CONNECT_REQUEST_HOSTSTATE_IDLE\x10<\x1a%\xa2\xd4\x18!#GameUI_Disconnect_\
    Request_HSIdle\x12\\\n.NETWORK_DISCONNECT_REQUEST_HOSTSTATE_HLTVRELAY\
    \x10=\x1a(\xa2\xd4\x18$#GameUI_Disconnect_Request_HLTVRelay\x12Q\n*NETWO\
    RK_DISCONNECT_CLIENT_CONSISTENCY_FAIL\x10>\x1a!\xa2\xd4\x18\x1d#GameUI_C\
    lientConsistencyFail\x12Q\n+NETWORK_DISCONNECT_CLIENT_UNABLE_TO_CRC_MAP\
    \x10?\x1a\x20\xa2\xd4\x18\x1c#GameUI_ClientUnableToCRCMap\x12=\n\x20NETW\
    ORK_DISCONNECT_CLIENT_NO_MAP\x10@\x1a\x17\xa2\xd4\x18\x13#GameUI_ClientN\
    oMap\x12K\n'NETWORK_DISCONNECT_CLIENT_DIFFERENT_MAP\x10A\x1a\x1e\xa2\xd4\
    \x18\x1a#GameUI_ClientDifferentMap\x12M\n(NETWORK_DISCONNECT_SERVER_REQU\
    IRES_STEAM\x10B\x1a\x1f\xa2\xd4\x18\x1b#GameUI_ServerRequireSteams\x12M\
    \n\"NETWORK_DISCONNECT_STEAM_DENY_MISC\x10C\x1a%\xa2\xd4\x18!#GameUI_Dis\
    connect_SteamDeny_Misc\x12_\n,NETWORK_DISCONNECT_STEAM_DENY_BAD_ANTI_CHE\
    AT\x10D\x1a-\xa2\xd4\x18)#GameUI_Disconnect_SteamDeny_BadAntiCheat\x12M\
    \n\"NETWORK_DISCONNECT_SERVER_SHUTDOWN\x10E\x1a%\xa2\xd4\x18!#GameUI_Dis\
    connect_ServerShutdown\x12b\n,NETWORK_DISCONNECT_SPLITPACKET_SEND_OVERFL\
    OW\x10F\x1a0\xa2\xd4\x18,#GameUI_Disconnect_Splitpacket_Send_Overflow\
    \x12U\n&NETWORK_DISCONNECT_REPLAY_INCOMPATIBLE\x10G\x1a)\xa2\xd4\x18%#Ga\
    meUI_Disconnect_ReplayIncompatible\x12Z\n+NETWORK_DISCONNECT_CONNECT_REQ\
    UEST_TIMEDOUT\x10H\x1a)\xa2\xd4\x18%#GameUI_Disconnect_ConnectionTimedou\
    t\x12U\n&NETWORK_DISCONNECT_SERVER_INCOMPATIBLE\x10I\x1a)\xa2\xd4\x18%#G\
    ameUI_Disconnect_ServerIncompatible\x12^\n*NETWORK_DISCONNECT_LOCALPROBL\
    EM_MANYRELAYS\x10J\x1a.\xa2\xd4\x18*#GameUI_Disconnect_LocalProblem_Many\
    Relays\x12z\n8NETWORK_DISCONNECT_LOCALPROBLEM_HOSTEDSERVERPRIMARYRELAY\
    \x10K\x1a<\xa2\xd4\x188#GameUI_Disconnect_LocalProblem_HostedServerPrima\
    ryRelay\x12d\n-NETWORK_DISCONNECT_LOCALPROBLEM_NETWORKCONFIG\x10L\x1a1\
    \xa2\xd4\x18-#GameUI_Disconnect_LocalProblem_NetworkConfig\x12T\n%NETWOR\
    K_DISCONNECT_LOCALPROBLEM_OTHER\x10M\x1a)\xa2\xd4\x18%#GameUI_Disconnect\
    _LocalProblem_Other\x12S\n!NETWORK_DISCONNECT_REMOTE_TIMEOUT\x10O\x1a,\
    \xa2\xd4\x18(#GameUI_Disconnect_RemoteProblem_Timeout\x12h\n,NETWORK_DIS\
    CONNECT_REMOTE_TIMEOUT_CONNECTING\x10P\x1a6\xa2\xd4\x182#GameUI_Disconne\
    ct_RemoteProblem_TimeoutConnecting\x12O\n\x1fNETWORK_DISCONNECT_REMOTE_O\
    THER\x10Q\x1a*\xa2\xd4\x18&#GameUI_Disconnect_RemoteProblem_Other\x12U\n\
    \"NETWORK_DISCONNECT_REMOTE_BADCRYPT\x10R\x1a-\xa2\xd4\x18)#GameUI_Disco\
    nnect_RemoteProblem_BadCrypt\x12Z\n(NETWORK_DISCONNECT_REMOTE_CERTNOTTRU\
    STED\x10S\x1a,\xa2\xd4\x18(#GameUI_Disconnect_RemoteProblem_BadCert\x12>\
    \n\x1aNETWORK_DISCONNECT_UNUSUAL\x10T\x1a\x1e\xa2\xd4\x18\x1a#GameUI_Dis\
    connect_Unusual\x12K\n!NETWORK_DISCONNECT_INTERNAL_ERROR\x10U\x1a$\xa2\
    \xd4\x18\x20#GameUI_Disconnect_InternalError\x12Q\n&NETWORK_DISCONNECT_R\
    EJECT_BADCHALLENGE\x10\x80\x01\x1a$\xa2\xd4\x18\x20#GameUI_ServerRejectB\
    adChallenge\x12A\n!NETWORK_DISCONNECT_REJECT_NOLOBBY\x10\x81\x01\x1a\x19\
    \xa2\xd4\x18\x15#GameUI_ServerNoLobby\x12O\n(NETWORK_DISCONNECT_REJECT_B\
    ACKGROUND_MAP\x10\x82\x01\x1a\x20\xa2\xd4\x18\x1c#Valve_Reject_Backgroun\
    d_Map\x12M\n'NETWORK_DISCONNECT_REJECT_SINGLE_PLAYER\x10\x83\x01\x1a\x1f\
    \xa2\xd4\x18\x1b#Valve_Reject_Single_Player\x12I\n%NETWORK_DISCONNECT_RE\
    JECT_HIDDEN_GAME\x10\x84\x01\x1a\x1d\xa2\xd4\x18\x19#Valve_Reject_Hidden\
    _Game\x12O\n%NETWORK_DISCONNECT_REJECT_LANRESTRICT\x10\x85\x01\x1a#\xa2\
    \xd4\x18\x1f#GameUI_ServerRejectLANRestrict\x12O\n%NETWORK_DISCONNECT_RE\
    JECT_BADPASSWORD\x10\x86\x01\x1a#\xa2\xd4\x18\x1f#GameUI_ServerRejectBad\
    Password\x12M\n$NETWORK_DISCONNECT_REJECT_SERVERFULL\x10\x87\x01\x1a\"\
    \xa2\xd4\x18\x1e#GameUI_ServerRejectServerFull\x12]\n,NETWORK_DISCONNECT\
    _REJECT_INVALIDRESERVATION\x10\x88\x01\x1a*\xa2\xd4\x18&#GameUI_ServerRe\
    jectInvalidReservation\x12S\n'NETWORK_DISCONNECT_REJECT_FAILEDCHANNEL\
    \x10\x89\x01\x1a%\xa2\xd4\x18!#GameUI_ServerRejectFailedChannel\x12W\n,N\
    ETWORK_DISCONNECT_REJECT_CONNECT_FROM_LOBBY\x10\x8a\x01\x1a$\xa2\xd4\x18\
    \x20#Valve_Reject_Connect_From_Lobby\x12W\n,NETWORK_DISCONNECT_REJECT_RE\
    SERVED_FOR_LOBBY\x10\x8b\x01\x1a$\xa2\xd4\x18\x20#Valve_Reject_Reserved_\
    For_Lobby\x12Z\n*NETWORK_DISCONNECT_REJECT_INVALIDKEYLENGTH\x10\x8c\x01\
    \x1a)\xa2\xd4\x18%#GameUI_ServerReject_InvalidKeyLength\x12O\n%NETWORK_D\
    ISCONNECT_REJECT_OLDPROTOCOL\x10\x8d\x01\x1a#\xa2\xd4\x18\x1f#GameUI_Ser\
    verRejectOldProtocol\x12O\n%NETWORK_DISCONNECT_REJECT_NEWPROTOCOL\x10\
    \x8e\x01\x1a#\xa2\xd4\x18\x1f#GameUI_ServerRejectNewProtocol\x12[\n+NETW\
    ORK_DISCONNECT_REJECT_INVALIDCONNECTION\x10\x8f\x01\x1a)\xa2\xd4\x18%#Ga\
    meUI_ServerRejectInvalidConnection\x12U\n(NETWORK_DISCONNECT_REJECT_INVA\
    LIDCERTLEN\x10\x90\x01\x1a&\xa2\xd4\x18\"#GameUI_ServerRejectInvalidCert\
    Len\x12_\n-NETWORK_DISCONNECT_REJECT_INVALIDSTEAMCERTLEN\x10\x91\x01\x1a\
    +\xa2\xd4\x18'#GameUI_ServerRejectInvalidSteamCertLen\x12C\n\x1fNETWORK_\
    DISCONNECT_REJECT_STEAM\x10\x92\x01\x1a\x1d\xa2\xd4\x18\x19#GameUI_Serve\
    rRejectSteam\x12Q\n,NETWORK_DISCONNECT_REJECT_SERVERAUTHDISABLED\x10\x93\
    \x01\x1a\x1e\xa2\xd4\x18\x1a#GameUI_ServerAuthDisabled\x12Y\n0NETWORK_DI\
    SCONNECT_REJECT_SERVERCDKEYAUTHINVALID\x10\x94\x01\x1a\"\xa2\xd4\x18\x1e\
    #GameUI_ServerCDKeyAuthInvalid\x12E\n\x20NETWORK_DISCONNECT_REJECT_BANNE\
    D\x10\x95\x01\x1a\x1e\xa2\xd4\x18\x1a#GameUI_ServerRejectBanned\x12T\n%N\
    ETWORK_DISCONNECT_KICKED_TEAMKILLING\x10\x96\x01\x1a(\xa2\xd4\x18$#Playe\
    r_DisconnectReason_TeamKilling\x12N\n\"NETWORK_DISCONNECT_KICKED_TK_STAR\
    T\x10\x97\x01\x1a%\xa2\xd4\x18!#Player_DisconnectReason_TK_Start\x12^\n*\
    NETWORK_DISCONNECT_KICKED_UNTRUSTEDACCOUNT\x10\x98\x01\x1a-\xa2\xd4\x18)\
    #Player_DisconnectReason_UntrustedAccount\x12^\n*NETWORK_DISCONNECT_KICK\
    ED_CONVICTEDACCOUNT\x10\x99\x01\x1a-\xa2\xd4\x18)#Player_DisconnectReaso\
    n_ConvictedAccount\x12d\n-NETWORK_DISCONNECT_KICKED_COMPETITIVECOOLDOWN\
    \x10\x9a\x01\x1a0\xa2\xd4\x18,#Player_DisconnectReason_CompetitiveCooldo\
    wn\x12T\n%NETWORK_DISCONNECT_KICKED_TEAMHURTING\x10\x9b\x01\x1a(\xa2\xd4\
    \x18$#Player_DisconnectReason_TeamHurting\x12Z\n(NETWORK_DISCONNECT_KICK\
    ED_HOSTAGEKILLING\x10\x9c\x01\x1a+\xa2\xd4\x18'#Player_DisconnectReason_\
    HostageKilling\x12N\n\"NETWORK_DISCONNECT_KICKED_VOTEDOFF\x10\x9d\x01\
    \x1a%\xa2\xd4\x18!#Player_DisconnectReason_VotedOff\x12F\n\x1eNETWORK_DI\
    SCONNECT_KICKED_IDLE\x10\x9e\x01\x1a!\xa2\xd4\x18\x1d#Player_DisconnectR\
    eason_Idle\x12L\n!NETWORK_DISCONNECT_KICKED_SUICIDE\x10\x9f\x01\x1a$\xa2\
    \xd4\x18\x20#Player_DisconnectReason_Suicide\x12V\n&NETWORK_DISCONNECT_K\
    ICKED_NOSTEAMLOGIN\x10\xa0\x01\x1a)\xa2\xd4\x18%#Player_DisconnectReason\
    _NoSteamLogin\x12X\n'NETWORK_DISCONNECT_KICKED_NOSTEAMTICKET\x10\xa1\x01\
    \x1a*\xa2\xd4\x18&#Player_DisconnectReason_NoSteamTicket:]\n\x18network_\
    connection_token\x18\xc4\x8a\x03\x20\x01(\t\x12!.google.protobuf.EnumVal\
    ueOptionsR\x16networkConnectionTokenJ\xa9C\n\x06\x12\x04\0\0~\x01\n\t\n\
    \x02\x03\0\x12\x03\0\0*\n\t\n\x01\x07\x12\x04\x02\0\x04\x01\n\t\n\x02\
    \x07\0\x12\x03\x03\x089\n\n\n\x03\x07\0\x02\x12\x03\x02\x07(\n\n\n\x03\
    \x07\0\x04\x12\x03\x03\x08\x10\n\n\n\x03\x07\0\x05\x12\x03\x03\x11\x17\n\
    \n\n\x03\x07\0\x01\x12\x03\x03\x180\n\n\n\x03\x07\0\x03\x12\x03\x0338\n\
    \n\n\x02\x05\0\x12\x04\x06\0~\x01\n\n\n\x03\x05\0\x01\x12\x03\x06\x05\
    \x20\n\x0b\n\x04\x05\0\x02\0\x12\x03\x07\x08'\n\x0c\n\x05\x05\0\x02\0\
    \x01\x12\x03\x07\x08\"\n\x0c\n\x05\x05\0\x02\0\x02\x12\x03\x07%&\n\x0b\n\
    \x04\x05\0\x02\x01\x12\x03\x08\x08(\n\x0c\n\x05\x05\0\x02\x01\x01\x12\
    \x03\x08\x08#\n\x0c\n\x05\x05\0\x02\x01\x02\x12\x03\x08&'\n\x0b\n\x04\
    \x05\0\x02\x02\x12\x03\t\x08k\n\x0c\n\x05\x05\0\x02\x02\x01\x12\x03\t\
    \x08-\n\x0c\n\x05\x05\0\x02\x02\x02\x12\x03\t01\n\x0c\n\x05\x05\0\x02\
    \x02\x03\x12\x03\t2j\n\x0f\n\x08\x05\0\x02\x02\x03\xc4\x8a\x03\x12\x03\t\
    3i\n\x0b\n\x04\x05\0\x02\x03\x12\x03\n\x08o\n\x0c\n\x05\x05\0\x02\x03\
    \x01\x12\x03\n\x08/\n\x0c\n\x05\x05\0\x02\x03\x02\x12\x03\n23\n\x0c\n\
    \x05\x05\0\x02\x03\x03\x12\x03\n4n\n\x0f\n\x08\x05\0\x02\x03\x03\xc4\x8a\
    \x03\x12\x03\n5m\n\x0b\n\x04\x05\0\x02\x04\x12\x03\x0b\x08g\n\x0c\n\x05\
    \x05\0\x02\x04\x01\x12\x03\x0b\x08\x1f\n\x0c\n\x05\x05\0\x02\x04\x02\x12\
    \x03\x0b\"#\n\x0c\n\x05\x05\0\x02\x04\x03\x12\x03\x0b$f\n\x0f\n\x08\x05\
    \0\x02\x04\x03\xc4\x8a\x03\x12\x03\x0b%e\n\x0b\n\x04\x05\0\x02\x05\x12\
    \x03\x0c\x08o\n\x0c\n\x05\x05\0\x02\x05\x01\x12\x03\x0c\x08#\n\x0c\n\x05\
    \x05\0\x02\x05\x02\x12\x03\x0c&'\n\x0c\n\x05\x05\0\x02\x05\x03\x12\x03\
    \x0c(n\n\x0f\n\x08\x05\0\x02\x05\x03\xc4\x8a\x03\x12\x03\x0c)m\n\x0b\n\
    \x04\x05\0\x02\x06\x12\x03\r\x08n\n\x0c\n\x05\x05\0\x02\x06\x01\x12\x03\
    \r\x08'\n\x0c\n\x05\x05\0\x02\x06\x02\x12\x03\r*+\n\x0c\n\x05\x05\0\x02\
    \x06\x03\x12\x03\r,m\n\x0f\n\x08\x05\0\x02\x06\x03\xc4\x8a\x03\x12\x03\r\
    -l\n\x0b\n\x04\x05\0\x02\x07\x12\x03\x0e\x08l\n\x0c\n\x05\x05\0\x02\x07\
    \x01\x12\x03\x0e\x08&\n\x0c\n\x05\x05\0\x02\x07\x02\x12\x03\x0e)*\n\x0c\
    \n\x05\x05\0\x02\x07\x03\x12\x03\x0e+k\n\x0f\n\x08\x05\0\x02\x07\x03\xc4\
    \x8a\x03\x12\x03\x0e,j\n\x0b\n\x04\x05\0\x02\x08\x12\x03\x0f\x08l\n\x0c\
    \n\x05\x05\0\x02\x08\x01\x12\x03\x0f\x08'\n\x0c\n\x05\x05\0\x02\x08\x02\
    \x12\x03\x0f*+\n\x0c\n\x05\x05\0\x02\x08\x03\x12\x03\x0f,k\n\x0f\n\x08\
    \x05\0\x02\x08\x03\xc4\x8a\x03\x12\x03\x0f-j\n\x0b\n\x04\x05\0\x02\t\x12\
    \x03\x10\x08j\n\x0c\n\x05\x05\0\x02\t\x01\x12\x03\x10\x08&\n\x0c\n\x05\
    \x05\0\x02\t\x02\x12\x03\x10)*\n\x0c\n\x05\x05\0\x02\t\x03\x12\x03\x10+i\
    \n\x0f\n\x08\x05\0\x02\t\x03\xc4\x8a\x03\x12\x03\x10,h\n\x0b\n\x04\x05\0\
    \x02\n\x12\x03\x11\x08s\n\x0c\n\x05\x05\0\x02\n\x01\x12\x03\x11\x08.\n\
    \x0c\n\x05\x05\0\x02\n\x02\x12\x03\x1113\n\x0c\n\x05\x05\0\x02\n\x03\x12\
    \x03\x114r\n\x0f\n\x08\x05\0\x02\n\x03\xc4\x8a\x03\x12\x03\x115q\n\x0b\n\
    \x04\x05\0\x02\x0b\x12\x03\x12\x08u\n\x0c\n\x05\x05\0\x02\x0b\x01\x12\
    \x03\x12\x080\n\x0c\n\x05\x05\0\x02\x0b\x02\x12\x03\x1235\n\x0c\n\x05\
    \x05\0\x02\x0b\x03\x12\x03\x126t\n\x0f\n\x08\x05\0\x02\x0b\x03\xc4\x8a\
    \x03\x12\x03\x127s\n\x0b\n\x04\x05\0\x02\x0c\x12\x03\x13\x08q\n\x0c\n\
    \x05\x05\0\x02\x0c\x01\x12\x03\x13\x08,\n\x0c\n\x05\x05\0\x02\x0c\x02\
    \x12\x03\x13/1\n\x0c\n\x05\x05\0\x02\x0c\x03\x12\x03\x132p\n\x0f\n\x08\
    \x05\0\x02\x0c\x03\xc4\x8a\x03\x12\x03\x133o\n\x0b\n\x04\x05\0\x02\r\x12\
    \x03\x14\x08o\n\x0c\n\x05\x05\0\x02\r\x01\x12\x03\x14\x08,\n\x0c\n\x05\
    \x05\0\x02\r\x02\x12\x03\x14/1\n\x0c\n\x05\x05\0\x02\r\x03\x12\x03\x142n\
    \n\x0f\n\x08\x05\0\x02\r\x03\xc4\x8a\x03\x12\x03\x143m\n\x0b\n\x04\x05\0\
    \x02\x0e\x12\x03\x15\x08y\n\x0c\n\x05\x05\0\x02\x0e\x01\x12\x03\x15\x084\
    \n\x0c\n\x05\x05\0\x02\x0e\x02\x12\x03\x1579\n\x0c\n\x05\x05\0\x02\x0e\
    \x03\x12\x03\x15:x\n\x0f\n\x08\x05\0\x02\x0e\x03\xc4\x8a\x03\x12\x03\x15\
    ;w\n\x0b\n\x04\x05\0\x02\x0f\x12\x03\x16\x08z\n\x0c\n\x05\x05\0\x02\x0f\
    \x01\x12\x03\x16\x083\n\x0c\n\x05\x05\0\x02\x0f\x02\x12\x03\x1668\n\x0c\
    \n\x05\x05\0\x02\x0f\x03\x12\x03\x169y\n\x0f\n\x08\x05\0\x02\x0f\x03\xc4\
    \x8a\x03\x12\x03\x16:x\n\x0b\n\x04\x05\0\x02\x10\x12\x03\x17\x08o\n\x0c\
    \n\x05\x05\0\x02\x10\x01\x12\x03\x17\x08(\n\x0c\n\x05\x05\0\x02\x10\x02\
    \x12\x03\x17+-\n\x0c\n\x05\x05\0\x02\x10\x03\x12\x03\x17.n\n\x0f\n\x08\
    \x05\0\x02\x10\x03\xc4\x8a\x03\x12\x03\x17/m\n\x0b\n\x04\x05\0\x02\x11\
    \x12\x03\x18\x08s\n\x0c\n\x05\x05\0\x02\x11\x01\x12\x03\x18\x08*\n\x0c\n\
    \x05\x05\0\x02\x11\x02\x12\x03\x18-/\n\x0c\n\x05\x05\0\x02\x11\x03\x12\
    \x03\x180r\n\x0f\n\x08\x05\0\x02\x11\x03\xc4\x8a\x03\x12\x03\x181q\n\x0b\
    \n\x04\x05\0\x02\x12\x12\x03\x19\x08{\n\x0c\n\x05\x05\0\x02\x12\x01\x12\
    \x03\x19\x08.\n\x0c\n\x05\x05\0\x02\x12\x02\x12\x03\x1913\n\x0c\n\x05\
    \x05\0\x02\x12\x03\x12\x03\x194z\n\x0f\n\x08\x05\0\x02\x12\x03\xc4\x8a\
    \x03\x12\x03\x195y\n\x0b\n\x04\x05\0\x02\x13\x12\x03\x1a\x08q\n\x0c\n\
    \x05\x05\0\x02\x13\x01\x12\x03\x1a\x08+\n\x0c\n\x05\x05\0\x02\x13\x02\
    \x12\x03\x1a.0\n\x0c\n\x05\x05\0\x02\x13\x03\x12\x03\x1a1p\n\x0f\n\x08\
    \x05\0\x02\x13\x03\xc4\x8a\x03\x12\x03\x1a2o\n\x0b\n\x04\x05\0\x02\x14\
    \x12\x03\x1b\x08\x7f\n\x0c\n\x05\x05\0\x02\x14\x01\x12\x03\x1b\x082\n\
    \x0c\n\x05\x05\0\x02\x14\x02\x12\x03\x1b57\n\x0c\n\x05\x05\0\x02\x14\x03\
    \x12\x03\x1b8~\n\x0f\n\x08\x05\0\x02\x14\x03\xc4\x8a\x03\x12\x03\x1b9}\n\
    \x0b\n\x04\x05\0\x02\x15\x12\x03\x1c\x08y\n\x0c\n\x05\x05\0\x02\x15\x01\
    \x12\x03\x1c\x08/\n\x0c\n\x05\x05\0\x02\x15\x02\x12\x03\x1c24\n\x0c\n\
    \x05\x05\0\x02\x15\x03\x12\x03\x1c5x\n\x0f\n\x08\x05\0\x02\x15\x03\xc4\
    \x8a\x03\x12\x03\x1c6w\n\x0b\n\x04\x05\0\x02\x16\x12\x03\x1d\x08w\n\x0c\
    \n\x05\x05\0\x02\x16\x01\x12\x03\x1d\x08.\n\x0c\n\x05\x05\0\x02\x16\x02\
    \x12\x03\x1d13\n\x0c\n\x05\x05\0\x02\x16\x03\x12\x03\x1d4v\n\x0f\n\x08\
    \x05\0\x02\x16\x03\xc4\x8a\x03\x12\x03\x1d5u\n\x0b\n\x04\x05\0\x02\x17\
    \x12\x03\x1e\x08u\n\x0c\n\x05\x05\0\x02\x17\x01\x12\x03\x1e\x08-\n\x0c\n\
    \x05\x05\0\x02\x17\x02\x12\x03\x1e02\n\x0c\n\x05\x05\0\x02\x17\x03\x12\
    \x03\x1e3t\n\x0f\n\x08\x05\0\x02\x17\x03\xc4\x8a\x03\x12\x03\x1e4s\n\x0b\
    \n\x04\x05\0\x02\x18\x12\x03\x1f\x08v\n\x0c\n\x05\x05\0\x02\x18\x01\x12\
    \x03\x1f\x08+\n\x0c\n\x05\x05\0\x02\x18\x02\x12\x03\x1f.0\n\x0c\n\x05\
    \x05\0\x02\x18\x03\x12\x03\x1f1u\n\x0f\n\x08\x05\0\x02\x18\x03\xc4\x8a\
    \x03\x12\x03\x1f2t\n\x0b\n\x04\x05\0\x02\x19\x12\x03\x20\x08p\n\x0c\n\
    \x05\x05\0\x02\x19\x01\x12\x03\x20\x08(\n\x0c\n\x05\x05\0\x02\x19\x02\
    \x12\x03\x20+-\n\x0c\n\x05\x05\0\x02\x19\x03\x12\x03\x20.o\n\x0f\n\x08\
    \x05\0\x02\x19\x03\xc4\x8a\x03\x12\x03\x20/n\n\x0b\n\x04\x05\0\x02\x1a\
    \x12\x03!\x08v\n\x0c\n\x05\x05\0\x02\x1a\x01\x12\x03!\x08+\n\x0c\n\x05\
    \x05\0\x02\x1a\x02\x12\x03!.0\n\x0c\n\x05\x05\0\x02\x1a\x03\x12\x03!1u\n\
    \x0f\n\x08\x05\0\x02\x1a\x03\xc4\x8a\x03\x12\x03!2t\n\x0b\n\x04\x05\0\
    \x02\x1b\x12\x03\"\x08t\n\x0c\n\x05\x05\0\x02\x1b\x01\x12\x03\"\x08'\n\
    \x0c\n\x05\x05\0\x02\x1b\x02\x12\x03\"*,\n\x0c\n\x05\x05\0\x02\x1b\x03\
    \x12\x03\"-s\n\x0f\n\x08\x05\0\x02\x1b\x03\xc4\x8a\x03\x12\x03\".r\n\x0b\
    \n\x04\x05\0\x02\x1c\x12\x03#\x08n\n\x0c\n\x05\x05\0\x02\x1c\x01\x12\x03\
    #\x08'\n\x0c\n\x05\x05\0\x02\x1c\x02\x12\x03#*,\n\x0c\n\x05\x05\0\x02\
    \x1c\x03\x12\x03#-m\n\x0f\n\x08\x05\0\x02\x1c\x03\xc4\x8a\x03\x12\x03#.l\
    \n\x0b\n\x04\x05\0\x02\x1d\x12\x03$\x08f\n\x0c\n\x05\x05\0\x02\x1d\x01\
    \x12\x03$\x08#\n\x0c\n\x05\x05\0\x02\x1d\x02\x12\x03$&(\n\x0c\n\x05\x05\
    \0\x02\x1d\x03\x12\x03$)e\n\x0f\n\x08\x05\0\x02\x1d\x03\xc4\x8a\x03\x12\
    \x03$*d\n\x0b\n\x04\x05\0\x02\x1e\x12\x03%\x08n\n\x0c\n\x05\x05\0\x02\
    \x1e\x01\x12\x03%\x08'\n\x0c\n\x05\x05\0\x02\x1e\x02\x12\x03%*,\n\x0c\n\
    \x05\x05\0\x02\x1e\x03\x12\x03%-m\n\x0f\n\x08\x05\0\x02\x1e\x03\xc4\x8a\
    \x03\x12\x03%.l\n\x0b\n\x04\x05\0\x02\x1f\x12\x03&\x08n\n\x0c\n\x05\x05\
    \0\x02\x1f\x01\x12\x03&\x08'\n\x0c\n\x05\x05\0\x02\x1f\x02\x12\x03&*,\n\
    \x0c\n\x05\x05\0\x02\x1f\x03\x12\x03&-m\n\x0f\n\x08\x05\0\x02\x1f\x03\
    \xc4\x8a\x03\x12\x03&.l\n\x0b\n\x04\x05\0\x02\x20\x12\x03'\x08~\n\x0c\n\
    \x05\x05\0\x02\x20\x01\x12\x03'\x08/\n\x0c\n\x05\x05\0\x02\x20\x02\x12\
    \x03'24\n\x0c\n\x05\x05\0\x02\x20\x03\x12\x03'5}\n\x0f\n\x08\x05\0\x02\
    \x20\x03\xc4\x8a\x03\x12\x03'6|\n\x0b\n\x04\x05\0\x02!\x12\x03(\x08v\n\
    \x0c\n\x05\x05\0\x02!\x01\x12\x03(\x08+\n\x0c\n\x05\x05\0\x02!\x02\x12\
    \x03(.0\n\x0c\n\x05\x05\0\x02!\x03\x12\x03(1u\n\x0f\n\x08\x05\0\x02!\x03\
    \xc4\x8a\x03\x12\x03(2t\n\x0b\n\x04\x05\0\x02\"\x12\x03)\x08~\n\x0c\n\
    \x05\x05\0\x02\"\x01\x12\x03)\x08/\n\x0c\n\x05\x05\0\x02\"\x02\x12\x03)2\
    4\n\x0c\n\x05\x05\0\x02\"\x03\x12\x03)5}\n\x0f\n\x08\x05\0\x02\"\x03\xc4\
    \x8a\x03\x12\x03)6|\n\x0b\n\x04\x05\0\x02#\x12\x03*\x08r\n\x0c\n\x05\x05\
    \0\x02#\x01\x12\x03*\x08)\n\x0c\n\x05\x05\0\x02#\x02\x12\x03*,.\n\x0c\n\
    \x05\x05\0\x02#\x03\x12\x03*/q\n\x0f\n\x08\x05\0\x02#\x03\xc4\x8a\x03\
    \x12\x03*0p\n\x0b\n\x04\x05\0\x02$\x12\x03+\x08n\n\x0c\n\x05\x05\0\x02$\
    \x01\x12\x03+\x08'\n\x0c\n\x05\x05\0\x02$\x02\x12\x03+*,\n\x0c\n\x05\x05\
    \0\x02$\x03\x12\x03+-m\n\x0f\n\x08\x05\0\x02$\x03\xc4\x8a\x03\x12\x03+.l\
    \n\x0b\n\x04\x05\0\x02%\x12\x03,\x08t\n\x0c\n\x05\x05\0\x02%\x01\x12\x03\
    ,\x08*\n\x0c\n\x05\x05\0\x02%\x02\x12\x03,-/\n\x0c\n\x05\x05\0\x02%\x03\
    \x12\x03,0s\n\x0f\n\x08\x05\0\x02%\x03\xc4\x8a\x03\x12\x03,1r\n\x0b\n\
    \x04\x05\0\x02&\x12\x03-\x08f\n\x0c\n\x05\x05\0\x02&\x01\x12\x03-\x08#\n\
    \x0c\n\x05\x05\0\x02&\x02\x12\x03-&(\n\x0c\n\x05\x05\0\x02&\x03\x12\x03-\
    )e\n\x0f\n\x08\x05\0\x02&\x03\xc4\x8a\x03\x12\x03-*d\n\x0b\n\x04\x05\0\
    \x02'\x12\x03.\x08b\n\x0c\n\x05\x05\0\x02'\x01\x12\x03.\x08!\n\x0c\n\x05\
    \x05\0\x02'\x02\x12\x03.$&\n\x0c\n\x05\x05\0\x02'\x03\x12\x03.'a\n\x0f\n\
    \x08\x05\0\x02'\x03\xc4\x8a\x03\x12\x03.(`\n\x0b\n\x04\x05\0\x02(\x12\
    \x03/\x08f\n\x0c\n\x05\x05\0\x02(\x01\x12\x03/\x08#\n\x0c\n\x05\x05\0\
    \x02(\x02\x12\x03/&(\n\x0c\n\x05\x05\0\x02(\x03\x12\x03/)e\n\x0f\n\x08\
    \x05\0\x02(\x03\xc4\x8a\x03\x12\x03/*d\n\x0b\n\x04\x05\0\x02)\x12\x030\
    \x08n\n\x0c\n\x05\x05\0\x02)\x01\x12\x030\x08'\n\x0c\n\x05\x05\0\x02)\
    \x02\x12\x030*,\n\x0c\n\x05\x05\0\x02)\x03\x12\x030-m\n\x0f\n\x08\x05\0\
    \x02)\x03\xc4\x8a\x03\x12\x030.l\n\x0b\n\x04\x05\0\x02*\x12\x031\x08j\n\
    \x0c\n\x05\x05\0\x02*\x01\x12\x031\x08%\n\x0c\n\x05\x05\0\x02*\x02\x12\
    \x031(*\n\x0c\n\x05\x05\0\x02*\x03\x12\x031+i\n\x0f\n\x08\x05\0\x02*\x03\
    \xc4\x8a\x03\x12\x031,h\n\x0c\n\x04\x05\0\x02+\x12\x042\x08\x82\x01\n\
    \x0c\n\x05\x05\0\x02+\x01\x12\x032\x081\n\x0c\n\x05\x05\0\x02+\x02\x12\
    \x03246\n\r\n\x05\x05\0\x02+\x03\x12\x0427\x81\x01\n\x10\n\x08\x05\0\x02\
    +\x03\xc4\x8a\x03\x12\x0428\x80\x01\n\x0b\n\x04\x05\0\x02,\x12\x033\x08|\
    \n\x0c\n\x05\x05\0\x02,\x01\x12\x033\x08.\n\x0c\n\x05\x05\0\x02,\x02\x12\
    \x03313\n\x0c\n\x05\x05\0\x02,\x03\x12\x0334{\n\x0f\n\x08\x05\0\x02,\x03\
    \xc4\x8a\x03\x12\x0335z\n\x0b\n\x04\x05\0\x02-\x12\x034\x08d\n\x0c\n\x05\
    \x05\0\x02-\x01\x12\x034\x08\"\n\x0c\n\x05\x05\0\x02-\x02\x12\x034%'\n\
    \x0c\n\x05\x05\0\x02-\x03\x12\x034(c\n\x0f\n\x08\x05\0\x02-\x03\xc4\x8a\
    \x03\x12\x034)b\n\x0b\n\x04\x05\0\x02.\x12\x035\x08t\n\x0c\n\x05\x05\0\
    \x02.\x01\x12\x035\x08+\n\x0c\n\x05\x05\0\x02.\x02\x12\x035.0\n\x0c\n\
    \x05\x05\0\x02.\x03\x12\x0351s\n\x0f\n\x08\x05\0\x02.\x03\xc4\x8a\x03\
    \x12\x0352r\n\x0b\n\x04\x05\0\x02/\x12\x036\x08z\n\x0c\n\x05\x05\0\x02/\
    \x01\x12\x036\x08.\n\x0c\n\x05\x05\0\x02/\x02\x12\x03613\n\x0c\n\x05\x05\
    \0\x02/\x03\x12\x0364y\n\x0f\n\x08\x05\0\x02/\x03\xc4\x8a\x03\x12\x0365x\
    \n\x0b\n\x04\x05\0\x020\x12\x037\x08~\n\x0c\n\x05\x05\0\x020\x01\x12\x03\
    7\x080\n\x0c\n\x05\x05\0\x020\x02\x12\x03735\n\x0c\n\x05\x05\0\x020\x03\
    \x12\x0376}\n\x0f\n\x08\x05\0\x020\x03\xc4\x8a\x03\x12\x0377|\n\x0b\n\
    \x04\x05\0\x021\x12\x038\x08z\n\x0c\n\x05\x05\0\x021\x01\x12\x038\x08.\n\
    \x0c\n\x05\x05\0\x021\x02\x12\x03813\n\x0c\n\x05\x05\0\x021\x03\x12\x038\
    4y\n\x0f\n\x08\x05\0\x021\x03\xc4\x8a\x03\x12\x0385x\n\x0b\n\x04\x05\0\
    \x022\x12\x039\x08;\n\x0c\n\x05\x05\0\x022\x01\x12\x039\x085\n\x0c\n\x05\
    \x05\0\x022\x02\x12\x0398:\n\x0b\n\x04\x05\0\x023\x12\x03:\x08y\n\x0c\n\
    \x05\x05\0\x023\x01\x12\x03:\x08-\n\x0c\n\x05\x05\0\x023\x02\x12\x03:02\
    \n\x0c\n\x05\x05\0\x023\x03\x12\x03:3x\n\x0f\n\x08\x05\0\x023\x03\xc4\
    \x8a\x03\x12\x03:4w\n\x0b\n\x04\x05\0\x024\x12\x03;\x08\x7f\n\x0c\n\x05\
    \x05\0\x024\x01\x12\x03;\x081\n\x0c\n\x05\x05\0\x024\x02\x12\x03;46\n\
    \x0c\n\x05\x05\0\x024\x03\x12\x03;7~\n\x0f\n\x08\x05\0\x024\x03\xc4\x8a\
    \x03\x12\x03;8}\n\x0b\n\x04\x05\0\x025\x12\x03<\x08-\n\x0c\n\x05\x05\0\
    \x025\x01\x12\x03<\x08'\n\x0c\n\x05\x05\0\x025\x02\x12\x03<*,\n\x0b\n\
    \x04\x05\0\x026\x12\x03=\x08n\n\x0c\n\x05\x05\0\x026\x01\x12\x03=\x08'\n\
    \x0c\n\x05\x05\0\x026\x02\x12\x03=*,\n\x0c\n\x05\x05\0\x026\x03\x12\x03=\
    -m\n\x0f\n\x08\x05\0\x026\x03\xc4\x8a\x03\x12\x03=.l\n\x0b\n\x04\x05\0\
    \x027\x12\x03>\x08r\n\x0c\n\x05\x05\0\x027\x01\x12\x03>\x08)\n\x0c\n\x05\
    \x05\0\x027\x02\x12\x03>,.\n\x0c\n\x05\x05\0\x027\x03\x12\x03>/q\n\x0f\n\
    \x08\x05\0\x027\x03\xc4\x8a\x03\x12\x03>0p\n\x0b\n\x04\x05\0\x028\x12\
    \x03?\x08n\n\x0c\n\x05\x05\0\x028\x01\x12\x03?\x08'\n\x0c\n\x05\x05\0\
    \x028\x02\x12\x03?*,\n\x0c\n\x05\x05\0\x028\x03\x12\x03?-m\n\x0f\n\x08\
    \x05\0\x028\x03\xc4\x8a\x03\x12\x03?.l\n\x0c\n\x04\x05\0\x029\x12\x04@\
    \x08\x82\x01\n\x0c\n\x05\x05\0\x029\x01\x12\x03@\x082\n\x0c\n\x05\x05\0\
    \x029\x02\x12\x03@57\n\r\n\x05\x05\0\x029\x03\x12\x04@8\x81\x01\n\x10\n\
    \x08\x05\0\x029\x03\xc4\x8a\x03\x12\x04@9\x80\x01\n\x0b\n\x04\x05\0\x02:\
    \x12\x03A\x08|\n\x0c\n\x05\x05\0\x02:\x01\x12\x03A\x08/\n\x0c\n\x05\x05\
    \0\x02:\x02\x12\x03A24\n\x0c\n\x05\x05\0\x02:\x03\x12\x03A5{\n\x0f\n\x08\
    \x05\0\x02:\x03\xc4\x8a\x03\x12\x03A6z\n\x0b\n\x04\x05\0\x02;\x12\x03B\
    \x08j\n\x0c\n\x05\x05\0\x02;\x01\x12\x03B\x08\"\n\x0c\n\x05\x05\0\x02;\
    \x02\x12\x03B%'\n\x0c\n\x05\x05\0\x02;\x03\x12\x03B(i\n\x0f\n\x08\x05\0\
    \x02;\x03\xc4\x8a\x03\x12\x03B)h\n\x0b\n\x04\x05\0\x02<\x12\x03C\x08z\n\
    \x0c\n\x05\x05\0\x02<\x01\x12\x03C\x081\n\x0c\n\x05\x05\0\x02<\x02\x12\
    \x03C46\n\x0c\n\x05\x05\0\x02<\x03\x12\x03C7y\n\x0f\n\x08\x05\0\x02<\x03\
    \xc4\x8a\x03\x12\x03C8x\n\x0c\n\x04\x05\0\x02=\x12\x04D\x08\x82\x01\n\
    \x0c\n\x05\x05\0\x02=\x01\x12\x03D\x086\n\x0c\n\x05\x05\0\x02=\x02\x12\
    \x03D9;\n\r\n\x05\x05\0\x02=\x03\x12\x04D<\x81\x01\n\x10\n\x08\x05\0\x02\
    =\x03\xc4\x8a\x03\x12\x04D=\x80\x01\n\x0b\n\x04\x05\0\x02>\x12\x03E\x08w\
    \n\x0c\n\x05\x05\0\x02>\x01\x12\x03E\x082\n\x0c\n\x05\x05\0\x02>\x02\x12\
    \x03E57\n\x0c\n\x05\x05\0\x02>\x03\x12\x03E8v\n\x0f\n\x08\x05\0\x02>\x03\
    \xc4\x8a\x03\x12\x03E9u\n\x0b\n\x04\x05\0\x02?\x12\x03F\x08w\n\x0c\n\x05\
    \x05\0\x02?\x01\x12\x03F\x083\n\x0c\n\x05\x05\0\x02?\x02\x12\x03F68\n\
    \x0c\n\x05\x05\0\x02?\x03\x12\x03F9v\n\x0f\n\x08\x05\0\x02?\x03\xc4\x8a\
    \x03\x12\x03F:u\n\x0b\n\x04\x05\0\x02@\x12\x03G\x08c\n\x0c\n\x05\x05\0\
    \x02@\x01\x12\x03G\x08(\n\x0c\n\x05\x05\0\x02@\x02\x12\x03G+-\n\x0c\n\
    \x05\x05\0\x02@\x03\x12\x03G.b\n\x0f\n\x08\x05\0\x02@\x03\xc4\x8a\x03\
    \x12\x03G/a\n\x0b\n\x04\x05\0\x02A\x12\x03H\x08q\n\x0c\n\x05\x05\0\x02A\
    \x01\x12\x03H\x08/\n\x0c\n\x05\x05\0\x02A\x02\x12\x03H24\n\x0c\n\x05\x05\
    \0\x02A\x03\x12\x03H5p\n\x0f\n\x08\x05\0\x02A\x03\xc4\x8a\x03\x12\x03H6o\
    \n\x0b\n\x04\x05\0\x02B\x12\x03I\x08s\n\x0c\n\x05\x05\0\x02B\x01\x12\x03\
    I\x080\n\x0c\n\x05\x05\0\x02B\x02\x12\x03I35\n\x0c\n\x05\x05\0\x02B\x03\
    \x12\x03I6r\n\x0f\n\x08\x05\0\x02B\x03\xc4\x8a\x03\x12\x03I7q\n\x0b\n\
    \x04\x05\0\x02C\x12\x03J\x08s\n\x0c\n\x05\x05\0\x02C\x01\x12\x03J\x08*\n\
    \x0c\n\x05\x05\0\x02C\x02\x12\x03J-/\n\x0c\n\x05\x05\0\x02C\x03\x12\x03J\
    0r\n\x0f\n\x08\x05\0\x02C\x03\xc4\x8a\x03\x12\x03J1q\n\x0c\n\x04\x05\0\
    \x02D\x12\x04K\x08\x85\x01\n\x0c\n\x05\x05\0\x02D\x01\x12\x03K\x084\n\
    \x0c\n\x05\x05\0\x02D\x02\x12\x03K79\n\r\n\x05\x05\0\x02D\x03\x12\x04K:\
    \x84\x01\n\x10\n\x08\x05\0\x02D\x03\xc4\x8a\x03\x12\x04K;\x83\x01\n\x0b\
    \n\x04\x05\0\x02E\x12\x03L\x08s\n\x0c\n\x05\x05\0\x02E\x01\x12\x03L\x08*\
    \n\x0c\n\x05\x05\0\x02E\x02\x12\x03L-/\n\x0c\n\x05\x05\0\x02E\x03\x12\
    \x03L0r\n\x0f\n\x08\x05\0\x02E\x03\xc4\x8a\x03\x12\x03L1q\n\x0c\n\x04\
    \x05\0\x02F\x12\x04M\x08\x88\x01\n\x0c\n\x05\x05\0\x02F\x01\x12\x03M\x08\
    4\n\x0c\n\x05\x05\0\x02F\x02\x12\x03M79\n\r\n\x05\x05\0\x02F\x03\x12\x04\
    M:\x87\x01\n\x10\n\x08\x05\0\x02F\x03\xc4\x8a\x03\x12\x04M;\x86\x01\n\
    \x0b\n\x04\x05\0\x02G\x12\x03N\x08{\n\x0c\n\x05\x05\0\x02G\x01\x12\x03N\
    \x08.\n\x0c\n\x05\x05\0\x02G\x02\x12\x03N13\n\x0c\n\x05\x05\0\x02G\x03\
    \x12\x03N4z\n\x0f\n\x08\x05\0\x02G\x03\xc4\x8a\x03\x12\x03N5y\n\x0c\n\
    \x04\x05\0\x02H\x12\x04O\x08\x80\x01\n\x0c\n\x05\x05\0\x02H\x01\x12\x03O\
    \x083\n\x0c\n\x05\x05\0\x02H\x02\x12\x03O68\n\x0c\n\x05\x05\0\x02H\x03\
    \x12\x03O9\x7f\n\x0f\n\x08\x05\0\x02H\x03\xc4\x8a\x03\x12\x03O:~\n\x0b\n\
    \x04\x05\0\x02I\x12\x03P\x08{\n\x0c\n\x05\x05\0\x02I\x01\x12\x03P\x08.\n\
    \x0c\n\x05\x05\0\x02I\x02\x12\x03P13\n\x0c\n\x05\x05\0\x02I\x03\x12\x03P\
    4z\n\x0f\n\x08\x05\0\x02I\x03\xc4\x8a\x03\x12\x03P5y\n\x0c\n\x04\x05\0\
    \x02J\x12\x04Q\x08\x84\x01\n\x0c\n\x05\x05\0\x02J\x01\x12\x03Q\x082\n\
    \x0c\n\x05\x05\0\x02J\x02\x12\x03Q57\n\r\n\x05\x05\0\x02J\x03\x12\x04Q8\
    \x83\x01\n\x10\n\x08\x05\0\x02J\x03\xc4\x8a\x03\x12\x04Q9\x82\x01\n\x0c\
    \n\x04\x05\0\x02K\x12\x04R\x08\xa0\x01\n\x0c\n\x05\x05\0\x02K\x01\x12\
    \x03R\x08@\n\x0c\n\x05\x05\0\x02K\x02\x12\x03RCE\n\r\n\x05\x05\0\x02K\
    \x03\x12\x04RF\x9f\x01\n\x10\n\x08\x05\0\x02K\x03\xc4\x8a\x03\x12\x04RG\
    \x9e\x01\n\x0c\n\x04\x05\0\x02L\x12\x04S\x08\x8a\x01\n\x0c\n\x05\x05\0\
    \x02L\x01\x12\x03S\x085\n\x0c\n\x05\x05\0\x02L\x02\x12\x03S8:\n\r\n\x05\
    \x05\0\x02L\x03\x12\x04S;\x89\x01\n\x10\n\x08\x05\0\x02L\x03\xc4\x8a\x03\
    \x12\x04S<\x88\x01\n\x0b\n\x04\x05\0\x02M\x12\x03T\x08z\n\x0c\n\x05\x05\
    \0\x02M\x01\x12\x03T\x08-\n\x0c\n\x05\x05\0\x02M\x02\x12\x03T02\n\x0c\n\
    \x05\x05\0\x02M\x03\x12\x03T3y\n\x0f\n\x08\x05\0\x02M\x03\xc4\x8a\x03\
    \x12\x03T4x\n\x0b\n\x04\x05\0\x02N\x12\x03U\x08y\n\x0c\n\x05\x05\0\x02N\
    \x01\x12\x03U\x08)\n\x0c\n\x05\x05\0\x02N\x02\x12\x03U,.\n\x0c\n\x05\x05\
    \0\x02N\x03\x12\x03U/x\n\x0f\n\x08\x05\0\x02N\x03\xc4\x8a\x03\x12\x03U0w\
    \n\x0c\n\x04\x05\0\x02O\x12\x04V\x08\x8e\x01\n\x0c\n\x05\x05\0\x02O\x01\
    \x12\x03V\x084\n\x0c\n\x05\x05\0\x02O\x02\x12\x03V79\n\r\n\x05\x05\0\x02\
    O\x03\x12\x04V:\x8d\x01\n\x10\n\x08\x05\0\x02O\x03\xc4\x8a\x03\x12\x04V;\
    \x8c\x01\n\x0b\n\x04\x05\0\x02P\x12\x03W\x08u\n\x0c\n\x05\x05\0\x02P\x01\
    \x12\x03W\x08'\n\x0c\n\x05\x05\0\x02P\x02\x12\x03W*,\n\x0c\n\x05\x05\0\
    \x02P\x03\x12\x03W-t\n\x0f\n\x08\x05\0\x02P\x03\xc4\x8a\x03\x12\x03W.s\n\
    \x0b\n\x04\x05\0\x02Q\x12\x03X\x08{\n\x0c\n\x05\x05\0\x02Q\x01\x12\x03X\
    \x08*\n\x0c\n\x05\x05\0\x02Q\x02\x12\x03X-/\n\x0c\n\x05\x05\0\x02Q\x03\
    \x12\x03X0z\n\x0f\n\x08\x05\0\x02Q\x03\xc4\x8a\x03\x12\x03X1y\n\x0c\n\
    \x04\x05\0\x02R\x12\x04Y\x08\x80\x01\n\x0c\n\x05\x05\0\x02R\x01\x12\x03Y\
    \x080\n\x0c\n\x05\x05\0\x02R\x02\x12\x03Y35\n\x0c\n\x05\x05\0\x02R\x03\
    \x12\x03Y6\x7f\n\x0f\n\x08\x05\0\x02R\x03\xc4\x8a\x03\x12\x03Y7~\n\x0b\n\
    \x04\x05\0\x02S\x12\x03Z\x08d\n\x0c\n\x05\x05\0\x02S\x01\x12\x03Z\x08\"\
    \n\x0c\n\x05\x05\0\x02S\x02\x12\x03Z%'\n\x0c\n\x05\x05\0\x02S\x03\x12\
    \x03Z(c\n\x0f\n\x08\x05\0\x02S\x03\xc4\x8a\x03\x12\x03Z)b\n\x0b\n\x04\
    \x05\0\x02T\x12\x03[\x08q\n\x0c\n\x05\x05\0\x02T\x01\x12\x03[\x08)\n\x0c\
    \n\x05\x05\0\x02T\x02\x12\x03[,.\n\x0c\n\x05\x05\0\x02T\x03\x12\x03[/p\n\
    \x0f\n\x08\x05\0\x02T\x03\xc4\x8a\x03\x12\x03[0o\n\x0b\n\x04\x05\0\x02U\
    \x12\x03\\\x08w\n\x0c\n\x05\x05\0\x02U\x01\x12\x03\\\x08.\n\x0c\n\x05\
    \x05\0\x02U\x02\x12\x03\\14\n\x0c\n\x05\x05\0\x02U\x03\x12\x03\\5v\n\x0f\
    \n\x08\x05\0\x02U\x03\xc4\x8a\x03\x12\x03\\6u\n\x0b\n\x04\x05\0\x02V\x12\
    \x03]\x08g\n\x0c\n\x05\x05\0\x02V\x01\x12\x03]\x08)\n\x0c\n\x05\x05\0\
    \x02V\x02\x12\x03],/\n\x0c\n\x05\x05\0\x02V\x03\x12\x03]0f\n\x0f\n\x08\
    \x05\0\x02V\x03\xc4\x8a\x03\x12\x03]1e\n\x0b\n\x04\x05\0\x02W\x12\x03^\
    \x08u\n\x0c\n\x05\x05\0\x02W\x01\x12\x03^\x080\n\x0c\n\x05\x05\0\x02W\
    \x02\x12\x03^36\n\x0c\n\x05\x05\0\x02W\x03\x12\x03^7t\n\x0f\n\x08\x05\0\
    \x02W\x03\xc4\x8a\x03\x12\x03^8s\n\x0b\n\x04\x05\0\x02X\x12\x03_\x08s\n\
    \x0c\n\x05\x05\0\x02X\x01\x12\x03_\x08/\n\x0c\n\x05\x05\0\x02X\x02\x12\
    \x03_25\n\x0c\n\x05\x05\0\x02X\x03\x12\x03_6r\n\x0f\n\x08\x05\0\x02X\x03\
    \xc4\x8a\x03\x12\x03_7q\n\x0b\n\x04\x05\0\x02Y\x12\x03`\x08o\n\x0c\n\x05\
    \x05\0\x02Y\x01\x12\x03`\x08-\n\x0c\n\x05\x05\0\x02Y\x02\x12\x03`03\n\
    \x0c\n\x05\x05\0\x02Y\x03\x12\x03`4n\n\x0f\n\x08\x05\0\x02Y\x03\xc4\x8a\
    \x03\x12\x03`5m\n\x0b\n\x04\x05\0\x02Z\x12\x03a\x08u\n\x0c\n\x05\x05\0\
    \x02Z\x01\x12\x03a\x08-\n\x0c\n\x05\x05\0\x02Z\x02\x12\x03a03\n\x0c\n\
    \x05\x05\0\x02Z\x03\x12\x03a4t\n\x0f\n\x08\x05\0\x02Z\x03\xc4\x8a\x03\
    \x12\x03a5s\n\x0b\n\x04\x05\0\x02[\x12\x03b\x08u\n\x0c\n\x05\x05\0\x02[\
    \x01\x12\x03b\x08-\n\x0c\n\x05\x05\0\x02[\x02\x12\x03b03\n\x0c\n\x05\x05\
    \0\x02[\x03\x12\x03b4t\n\x0f\n\x08\x05\0\x02[\x03\xc4\x8a\x03\x12\x03b5s\
    \n\x0b\n\x04\x05\0\x02\\\x12\x03c\x08s\n\x0c\n\x05\x05\0\x02\\\x01\x12\
    \x03c\x08,\n\x0c\n\x05\x05\0\x02\\\x02\x12\x03c/2\n\x0c\n\x05\x05\0\x02\
    \\\x03\x12\x03c3r\n\x0f\n\x08\x05\0\x02\\\x03\xc4\x8a\x03\x12\x03c4q\n\
    \x0c\n\x04\x05\0\x02]\x12\x04d\x08\x83\x01\n\x0c\n\x05\x05\0\x02]\x01\
    \x12\x03d\x084\n\x0c\n\x05\x05\0\x02]\x02\x12\x03d7:\n\r\n\x05\x05\0\x02\
    ]\x03\x12\x04d;\x82\x01\n\x10\n\x08\x05\0\x02]\x03\xc4\x8a\x03\x12\x04d<\
    \x81\x01\n\x0b\n\x04\x05\0\x02^\x12\x03e\x08y\n\x0c\n\x05\x05\0\x02^\x01\
    \x12\x03e\x08/\n\x0c\n\x05\x05\0\x02^\x02\x12\x03e25\n\x0c\n\x05\x05\0\
    \x02^\x03\x12\x03e6x\n\x0f\n\x08\x05\0\x02^\x03\xc4\x8a\x03\x12\x03e7w\n\
    \x0b\n\x04\x05\0\x02_\x12\x03f\x08}\n\x0c\n\x05\x05\0\x02_\x01\x12\x03f\
    \x084\n\x0c\n\x05\x05\0\x02_\x02\x12\x03f7:\n\x0c\n\x05\x05\0\x02_\x03\
    \x12\x03f;|\n\x0f\n\x08\x05\0\x02_\x03\xc4\x8a\x03\x12\x03f<{\n\x0b\n\
    \x04\x05\0\x02`\x12\x03g\x08}\n\x0c\n\x05\x05\0\x02`\x01\x12\x03g\x084\n\
    \x0c\n\x05\x05\0\x02`\x02\x12\x03g7:\n\x0c\n\x05\x05\0\x02`\x03\x12\x03g\
    ;|\n\x0f\n\x08\x05\0\x02`\x03\xc4\x8a\x03\x12\x03g<{\n\x0c\n\x04\x05\0\
    \x02a\x12\x04h\x08\x80\x01\n\x0c\n\x05\x05\0\x02a\x01\x12\x03h\x082\n\
    \x0c\n\x05\x05\0\x02a\x02\x12\x03h58\n\x0c\n\x05\x05\0\x02a\x03\x12\x03h\
    9\x7f\n\x0f\n\x08\x05\0\x02a\x03\xc4\x8a\x03\x12\x03h:~\n\x0b\n\x04\x05\
    \0\x02b\x12\x03i\x08u\n\x0c\n\x05\x05\0\x02b\x01\x12\x03i\x08-\n\x0c\n\
    \x05\x05\0\x02b\x02\x12\x03i03\n\x0c\n\x05\x05\0\x02b\x03\x12\x03i4t\n\
    \x0f\n\x08\x05\0\x02b\x03\xc4\x8a\x03\x12\x03i5s\n\x0b\n\x04\x05\0\x02c\
    \x12\x03j\x08u\n\x0c\n\x05\x05\0\x02c\x01\x12\x03j\x08-\n\x0c\n\x05\x05\
    \0\x02c\x02\x12\x03j03\n\x0c\n\x05\x05\0\x02c\x03\x12\x03j4t\n\x0f\n\x08\
    \x05\0\x02c\x03\xc4\x8a\x03\x12\x03j5s\n\x0c\n\x04\x05\0\x02d\x12\x04k\
    \x08\x81\x01\n\x0c\n\x05\x05\0\x02d\x01\x12\x03k\x083\n\x0c\n\x05\x05\0\
    \x02d\x02\x12\x03k69\n\r\n\x05\x05\0\x02d\x03\x12\x04k:\x80\x01\n\x0f\n\
    \x08\x05\0\x02d\x03\xc4\x8a\x03\x12\x03k;\x7f\n\x0b\n\x04\x05\0\x02e\x12\
    \x03l\x08{\n\x0c\n\x05\x05\0\x02e\x01\x12\x03l\x080\n\x0c\n\x05\x05\0\
    \x02e\x02\x12\x03l36\n\x0c\n\x05\x05\0\x02e\x03\x12\x03l7z\n\x0f\n\x08\
    \x05\0\x02e\x03\xc4\x8a\x03\x12\x03l8y\n\x0c\n\x04\x05\0\x02f\x12\x04m\
    \x08\x85\x01\n\x0c\n\x05\x05\0\x02f\x01\x12\x03m\x085\n\x0c\n\x05\x05\0\
    \x02f\x02\x12\x03m8;\n\r\n\x05\x05\0\x02f\x03\x12\x04m<\x84\x01\n\x10\n\
    \x08\x05\0\x02f\x03\xc4\x8a\x03\x12\x04m=\x83\x01\n\x0b\n\x04\x05\0\x02g\
    \x12\x03n\x08i\n\x0c\n\x05\x05\0\x02g\x01\x12\x03n\x08'\n\x0c\n\x05\x05\
    \0\x02g\x02\x12\x03n*-\n\x0c\n\x05\x05\0\x02g\x03\x12\x03n.h\n\x0f\n\x08\
    \x05\0\x02g\x03\xc4\x8a\x03\x12\x03n/g\n\x0b\n\x04\x05\0\x02h\x12\x03o\
    \x08w\n\x0c\n\x05\x05\0\x02h\x01\x12\x03o\x084\n\x0c\n\x05\x05\0\x02h\
    \x02\x12\x03o7:\n\x0c\n\x05\x05\0\x02h\x03\x12\x03o;v\n\x0f\n\x08\x05\0\
    \x02h\x03\xc4\x8a\x03\x12\x03o<u\n\x0b\n\x04\x05\0\x02i\x12\x03p\x08\x7f\
    \n\x0c\n\x05\x05\0\x02i\x01\x12\x03p\x088\n\x0c\n\x05\x05\0\x02i\x02\x12\
    \x03p;>\n\x0c\n\x05\x05\0\x02i\x03\x12\x03p?~\n\x0f\n\x08\x05\0\x02i\x03\
    \xc4\x8a\x03\x12\x03p@}\n\x0b\n\x04\x05\0\x02j\x12\x03q\x08k\n\x0c\n\x05\
    \x05\0\x02j\x01\x12\x03q\x08(\n\x0c\n\x05\x05\0\x02j\x02\x12\x03q+.\n\
    \x0c\n\x05\x05\0\x02j\x03\x12\x03q/j\n\x0f\n\x08\x05\0\x02j\x03\xc4\x8a\
    \x03\x12\x03q0i\n\x0b\n\x04\x05\0\x02k\x12\x03r\x08z\n\x0c\n\x05\x05\0\
    \x02k\x01\x12\x03r\x08-\n\x0c\n\x05\x05\0\x02k\x02\x12\x03r03\n\x0c\n\
    \x05\x05\0\x02k\x03\x12\x03r4y\n\x0f\n\x08\x05\0\x02k\x03\xc4\x8a\x03\
    \x12\x03r5x\n\x0b\n\x04\x05\0\x02l\x12\x03s\x08t\n\x0c\n\x05\x05\0\x02l\
    \x01\x12\x03s\x08*\n\x0c\n\x05\x05\0\x02l\x02\x12\x03s-0\n\x0c\n\x05\x05\
    \0\x02l\x03\x12\x03s1s\n\x0f\n\x08\x05\0\x02l\x03\xc4\x8a\x03\x12\x03s2r\
    \n\x0c\n\x04\x05\0\x02m\x12\x04t\x08\x84\x01\n\x0c\n\x05\x05\0\x02m\x01\
    \x12\x03t\x082\n\x0c\n\x05\x05\0\x02m\x02\x12\x03t58\n\r\n\x05\x05\0\x02\
    m\x03\x12\x04t9\x83\x01\n\x10\n\x08\x05\0\x02m\x03\xc4\x8a\x03\x12\x04t:\
    \x82\x01\n\x0c\n\x04\x05\0\x02n\x12\x04u\x08\x84\x01\n\x0c\n\x05\x05\0\
    \x02n\x01\x12\x03u\x082\n\x0c\n\x05\x05\0\x02n\x02\x12\x03u58\n\r\n\x05\
    \x05\0\x02n\x03\x12\x04u9\x83\x01\n\x10\n\x08\x05\0\x02n\x03\xc4\x8a\x03\
    \x12\x04u:\x82\x01\n\x0c\n\x04\x05\0\x02o\x12\x04v\x08\x8a\x01\n\x0c\n\
    \x05\x05\0\x02o\x01\x12\x03v\x085\n\x0c\n\x05\x05\0\x02o\x02\x12\x03v8;\
    \n\r\n\x05\x05\0\x02o\x03\x12\x04v<\x89\x01\n\x10\n\x08\x05\0\x02o\x03\
    \xc4\x8a\x03\x12\x04v=\x88\x01\n\x0b\n\x04\x05\0\x02p\x12\x03w\x08z\n\
    \x0c\n\x05\x05\0\x02p\x01\x12\x03w\x08-\n\x0c\n\x05\x05\0\x02p\x02\x12\
    \x03w03\n\x0c\n\x05\x05\0\x02p\x03\x12\x03w4y\n\x0f\n\x08\x05\0\x02p\x03\
    \xc4\x8a\x03\x12\x03w5x\n\x0c\n\x04\x05\0\x02q\x12\x04x\x08\x80\x01\n\
    \x0c\n\x05\x05\0\x02q\x01\x12\x03x\x080\n\x0c\n\x05\x05\0\x02q\x02\x12\
    \x03x36\n\x0c\n\x05\x05\0\x02q\x03\x12\x03x7\x7f\n\x0f\n\x08\x05\0\x02q\
    \x03\xc4\x8a\x03\x12\x03x8~\n\x0b\n\x04\x05\0\x02r\x12\x03y\x08t\n\x0c\n\
    \x05\x05\0\x02r\x01\x12\x03y\x08*\n\x0c\n\x05\x05\0\x02r\x02\x12\x03y-0\
    \n\x0c\n\x05\x05\0\x02r\x03\x12\x03y1s\n\x0f\n\x08\x05\0\x02r\x03\xc4\
    \x8a\x03\x12\x03y2r\n\x0b\n\x04\x05\0\x02s\x12\x03z\x08l\n\x0c\n\x05\x05\
    \0\x02s\x01\x12\x03z\x08&\n\x0c\n\x05\x05\0\x02s\x02\x12\x03z),\n\x0c\n\
    \x05\x05\0\x02s\x03\x12\x03z-k\n\x0f\n\x08\x05\0\x02s\x03\xc4\x8a\x03\
    \x12\x03z.j\n\x0b\n\x04\x05\0\x02t\x12\x03{\x08r\n\x0c\n\x05\x05\0\x02t\
    \x01\x12\x03{\x08)\n\x0c\n\x05\x05\0\x02t\x02\x12\x03{,/\n\x0c\n\x05\x05\
    \0\x02t\x03\x12\x03{0q\n\x0f\n\x08\x05\0\x02t\x03\xc4\x8a\x03\x12\x03{1p\
    \n\x0b\n\x04\x05\0\x02u\x12\x03|\x08|\n\x0c\n\x05\x05\0\x02u\x01\x12\x03\
    |\x08.\n\x0c\n\x05\x05\0\x02u\x02\x12\x03|14\n\x0c\n\x05\x05\0\x02u\x03\
    \x12\x03|5{\n\x0f\n\x08\x05\0\x02u\x03\xc4\x8a\x03\x12\x03|6z\n\x0b\n\
    \x04\x05\0\x02v\x12\x03}\x08~\n\x0c\n\x05\x05\0\x02v\x01\x12\x03}\x08/\n\
    \x0c\n\x05\x05\0\x02v\x02\x12\x03}25\n\x0c\n\x05\x05\0\x02v\x03\x12\x03}\
    6}\n\x0f\n\x08\x05\0\x02v\x03\xc4\x8a\x03\x12\x03}7|\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(1);
            deps.push(::protobuf::descriptor::file_descriptor().clone());
            let mut messages = ::std::vec::Vec::with_capacity(0);
            let mut enums = ::std::vec::Vec::with_capacity(1);
            enums.push(ENetworkDisconnectionReason::generated_enum_descriptor_data());
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
