// This file is generated by rust-protobuf 3.3.0. Do not edit
// .proto file is parsed by protoc 3.19.1
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `network_connection.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_3_0;

#[derive(Clone,Copy,PartialEq,Eq,Debug,Hash)]
// @@protoc_insertion_point(enum:ENetworkDisconnectionReason)
pub enum ENetworkDisconnectionReason {
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_INVALID)
    NETWORK_DISCONNECT_INVALID = 0,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_SHUTDOWN)
    NETWORK_DISCONNECT_SHUTDOWN = 1,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_DISCONNECT_BY_USER)
    NETWORK_DISCONNECT_DISCONNECT_BY_USER = 2,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_DISCONNECT_BY_SERVER)
    NETWORK_DISCONNECT_DISCONNECT_BY_SERVER = 3,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_LOST)
    NETWORK_DISCONNECT_LOST = 4,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_OVERFLOW)
    NETWORK_DISCONNECT_OVERFLOW = 5,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_STEAM_BANNED)
    NETWORK_DISCONNECT_STEAM_BANNED = 6,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_STEAM_INUSE)
    NETWORK_DISCONNECT_STEAM_INUSE = 7,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_STEAM_TICKET)
    NETWORK_DISCONNECT_STEAM_TICKET = 8,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_STEAM_LOGON)
    NETWORK_DISCONNECT_STEAM_LOGON = 9,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_STEAM_AUTHCANCELLED)
    NETWORK_DISCONNECT_STEAM_AUTHCANCELLED = 10,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_STEAM_AUTHALREADYUSED)
    NETWORK_DISCONNECT_STEAM_AUTHALREADYUSED = 11,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_STEAM_AUTHINVALID)
    NETWORK_DISCONNECT_STEAM_AUTHINVALID = 12,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_STEAM_VACBANSTATE)
    NETWORK_DISCONNECT_STEAM_VACBANSTATE = 13,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_STEAM_LOGGED_IN_ELSEWHERE)
    NETWORK_DISCONNECT_STEAM_LOGGED_IN_ELSEWHERE = 14,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_STEAM_VAC_CHECK_TIMEDOUT)
    NETWORK_DISCONNECT_STEAM_VAC_CHECK_TIMEDOUT = 15,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_STEAM_DROPPED)
    NETWORK_DISCONNECT_STEAM_DROPPED = 16,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_STEAM_OWNERSHIP)
    NETWORK_DISCONNECT_STEAM_OWNERSHIP = 17,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_SERVERINFO_OVERFLOW)
    NETWORK_DISCONNECT_SERVERINFO_OVERFLOW = 18,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_TICKMSG_OVERFLOW)
    NETWORK_DISCONNECT_TICKMSG_OVERFLOW = 19,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_STRINGTABLEMSG_OVERFLOW)
    NETWORK_DISCONNECT_STRINGTABLEMSG_OVERFLOW = 20,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_DELTAENTMSG_OVERFLOW)
    NETWORK_DISCONNECT_DELTAENTMSG_OVERFLOW = 21,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_TEMPENTMSG_OVERFLOW)
    NETWORK_DISCONNECT_TEMPENTMSG_OVERFLOW = 22,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_SOUNDSMSG_OVERFLOW)
    NETWORK_DISCONNECT_SOUNDSMSG_OVERFLOW = 23,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_SNAPSHOTOVERFLOW)
    NETWORK_DISCONNECT_SNAPSHOTOVERFLOW = 24,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_SNAPSHOTERROR)
    NETWORK_DISCONNECT_SNAPSHOTERROR = 25,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_RELIABLEOVERFLOW)
    NETWORK_DISCONNECT_RELIABLEOVERFLOW = 26,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_BADDELTATICK)
    NETWORK_DISCONNECT_BADDELTATICK = 27,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_NOMORESPLITS)
    NETWORK_DISCONNECT_NOMORESPLITS = 28,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_TIMEDOUT)
    NETWORK_DISCONNECT_TIMEDOUT = 29,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_DISCONNECTED)
    NETWORK_DISCONNECT_DISCONNECTED = 30,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_LEAVINGSPLIT)
    NETWORK_DISCONNECT_LEAVINGSPLIT = 31,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_DIFFERENTCLASSTABLES)
    NETWORK_DISCONNECT_DIFFERENTCLASSTABLES = 32,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_BADRELAYPASSWORD)
    NETWORK_DISCONNECT_BADRELAYPASSWORD = 33,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_BADSPECTATORPASSWORD)
    NETWORK_DISCONNECT_BADSPECTATORPASSWORD = 34,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_HLTVRESTRICTED)
    NETWORK_DISCONNECT_HLTVRESTRICTED = 35,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_NOSPECTATORS)
    NETWORK_DISCONNECT_NOSPECTATORS = 36,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_HLTVUNAVAILABLE)
    NETWORK_DISCONNECT_HLTVUNAVAILABLE = 37,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_HLTVSTOP)
    NETWORK_DISCONNECT_HLTVSTOP = 38,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_KICKED)
    NETWORK_DISCONNECT_KICKED = 39,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_BANADDED)
    NETWORK_DISCONNECT_BANADDED = 40,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_KICKBANADDED)
    NETWORK_DISCONNECT_KICKBANADDED = 41,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_HLTVDIRECT)
    NETWORK_DISCONNECT_HLTVDIRECT = 42,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_PURESERVER_CLIENTEXTRA)
    NETWORK_DISCONNECT_PURESERVER_CLIENTEXTRA = 43,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_PURESERVER_MISMATCH)
    NETWORK_DISCONNECT_PURESERVER_MISMATCH = 44,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_USERCMD)
    NETWORK_DISCONNECT_USERCMD = 45,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_REJECTED_BY_GAME)
    NETWORK_DISCONNECT_REJECTED_BY_GAME = 46,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_MESSAGE_PARSE_ERROR)
    NETWORK_DISCONNECT_MESSAGE_PARSE_ERROR = 47,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_INVALID_MESSAGE_ERROR)
    NETWORK_DISCONNECT_INVALID_MESSAGE_ERROR = 48,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_BAD_SERVER_PASSWORD)
    NETWORK_DISCONNECT_BAD_SERVER_PASSWORD = 49,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_DIRECT_CONNECT_RESERVATION)
    NETWORK_DISCONNECT_DIRECT_CONNECT_RESERVATION = 50,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_CONNECTION_FAILURE)
    NETWORK_DISCONNECT_CONNECTION_FAILURE = 51,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_NO_PEER_GROUP_HANDLERS)
    NETWORK_DISCONNECT_NO_PEER_GROUP_HANDLERS = 52,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_RECONNECTION)
    NETWORK_DISCONNECT_RECONNECTION = 53,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_LOOPSHUTDOWN)
    NETWORK_DISCONNECT_LOOPSHUTDOWN = 54,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_LOOPDEACTIVATE)
    NETWORK_DISCONNECT_LOOPDEACTIVATE = 55,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_HOST_ENDGAME)
    NETWORK_DISCONNECT_HOST_ENDGAME = 56,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_LOOP_LEVELLOAD_ACTIVATE)
    NETWORK_DISCONNECT_LOOP_LEVELLOAD_ACTIVATE = 57,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_CREATE_SERVER_FAILED)
    NETWORK_DISCONNECT_CREATE_SERVER_FAILED = 58,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_EXITING)
    NETWORK_DISCONNECT_EXITING = 59,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_REQUEST_HOSTSTATE_IDLE)
    NETWORK_DISCONNECT_REQUEST_HOSTSTATE_IDLE = 60,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_REQUEST_HOSTSTATE_HLTVRELAY)
    NETWORK_DISCONNECT_REQUEST_HOSTSTATE_HLTVRELAY = 61,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_CLIENT_CONSISTENCY_FAIL)
    NETWORK_DISCONNECT_CLIENT_CONSISTENCY_FAIL = 62,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_CLIENT_UNABLE_TO_CRC_MAP)
    NETWORK_DISCONNECT_CLIENT_UNABLE_TO_CRC_MAP = 63,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_CLIENT_NO_MAP)
    NETWORK_DISCONNECT_CLIENT_NO_MAP = 64,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_CLIENT_DIFFERENT_MAP)
    NETWORK_DISCONNECT_CLIENT_DIFFERENT_MAP = 65,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_SERVER_REQUIRES_STEAM)
    NETWORK_DISCONNECT_SERVER_REQUIRES_STEAM = 66,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_STEAM_DENY_MISC)
    NETWORK_DISCONNECT_STEAM_DENY_MISC = 67,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_STEAM_DENY_BAD_ANTI_CHEAT)
    NETWORK_DISCONNECT_STEAM_DENY_BAD_ANTI_CHEAT = 68,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_SERVER_SHUTDOWN)
    NETWORK_DISCONNECT_SERVER_SHUTDOWN = 69,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_REPLAY_INCOMPATIBLE)
    NETWORK_DISCONNECT_REPLAY_INCOMPATIBLE = 71,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_CONNECT_REQUEST_TIMEDOUT)
    NETWORK_DISCONNECT_CONNECT_REQUEST_TIMEDOUT = 72,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_SERVER_INCOMPATIBLE)
    NETWORK_DISCONNECT_SERVER_INCOMPATIBLE = 73,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_LOCALPROBLEM_MANYRELAYS)
    NETWORK_DISCONNECT_LOCALPROBLEM_MANYRELAYS = 74,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_LOCALPROBLEM_HOSTEDSERVERPRIMARYRELAY)
    NETWORK_DISCONNECT_LOCALPROBLEM_HOSTEDSERVERPRIMARYRELAY = 75,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_LOCALPROBLEM_NETWORKCONFIG)
    NETWORK_DISCONNECT_LOCALPROBLEM_NETWORKCONFIG = 76,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_LOCALPROBLEM_OTHER)
    NETWORK_DISCONNECT_LOCALPROBLEM_OTHER = 77,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_REMOTE_TIMEOUT)
    NETWORK_DISCONNECT_REMOTE_TIMEOUT = 79,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_REMOTE_TIMEOUT_CONNECTING)
    NETWORK_DISCONNECT_REMOTE_TIMEOUT_CONNECTING = 80,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_REMOTE_OTHER)
    NETWORK_DISCONNECT_REMOTE_OTHER = 81,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_REMOTE_BADCRYPT)
    NETWORK_DISCONNECT_REMOTE_BADCRYPT = 82,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_REMOTE_CERTNOTTRUSTED)
    NETWORK_DISCONNECT_REMOTE_CERTNOTTRUSTED = 83,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_UNUSUAL)
    NETWORK_DISCONNECT_UNUSUAL = 84,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_INTERNAL_ERROR)
    NETWORK_DISCONNECT_INTERNAL_ERROR = 85,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_REJECT_BADCHALLENGE)
    NETWORK_DISCONNECT_REJECT_BADCHALLENGE = 128,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_REJECT_NOLOBBY)
    NETWORK_DISCONNECT_REJECT_NOLOBBY = 129,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_REJECT_BACKGROUND_MAP)
    NETWORK_DISCONNECT_REJECT_BACKGROUND_MAP = 130,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_REJECT_SINGLE_PLAYER)
    NETWORK_DISCONNECT_REJECT_SINGLE_PLAYER = 131,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_REJECT_HIDDEN_GAME)
    NETWORK_DISCONNECT_REJECT_HIDDEN_GAME = 132,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_REJECT_LANRESTRICT)
    NETWORK_DISCONNECT_REJECT_LANRESTRICT = 133,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_REJECT_BADPASSWORD)
    NETWORK_DISCONNECT_REJECT_BADPASSWORD = 134,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_REJECT_SERVERFULL)
    NETWORK_DISCONNECT_REJECT_SERVERFULL = 135,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_REJECT_INVALIDRESERVATION)
    NETWORK_DISCONNECT_REJECT_INVALIDRESERVATION = 136,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_REJECT_FAILEDCHANNEL)
    NETWORK_DISCONNECT_REJECT_FAILEDCHANNEL = 137,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_REJECT_CONNECT_FROM_LOBBY)
    NETWORK_DISCONNECT_REJECT_CONNECT_FROM_LOBBY = 138,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_REJECT_RESERVED_FOR_LOBBY)
    NETWORK_DISCONNECT_REJECT_RESERVED_FOR_LOBBY = 139,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_REJECT_INVALIDKEYLENGTH)
    NETWORK_DISCONNECT_REJECT_INVALIDKEYLENGTH = 140,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_REJECT_OLDPROTOCOL)
    NETWORK_DISCONNECT_REJECT_OLDPROTOCOL = 141,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_REJECT_NEWPROTOCOL)
    NETWORK_DISCONNECT_REJECT_NEWPROTOCOL = 142,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_REJECT_INVALIDCONNECTION)
    NETWORK_DISCONNECT_REJECT_INVALIDCONNECTION = 143,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_REJECT_INVALIDCERTLEN)
    NETWORK_DISCONNECT_REJECT_INVALIDCERTLEN = 144,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_REJECT_INVALIDSTEAMCERTLEN)
    NETWORK_DISCONNECT_REJECT_INVALIDSTEAMCERTLEN = 145,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_REJECT_STEAM)
    NETWORK_DISCONNECT_REJECT_STEAM = 146,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_REJECT_SERVERAUTHDISABLED)
    NETWORK_DISCONNECT_REJECT_SERVERAUTHDISABLED = 147,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_REJECT_SERVERCDKEYAUTHINVALID)
    NETWORK_DISCONNECT_REJECT_SERVERCDKEYAUTHINVALID = 148,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_REJECT_BANNED)
    NETWORK_DISCONNECT_REJECT_BANNED = 149,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_KICKED_TEAMKILLING)
    NETWORK_DISCONNECT_KICKED_TEAMKILLING = 150,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_KICKED_TK_START)
    NETWORK_DISCONNECT_KICKED_TK_START = 151,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_KICKED_UNTRUSTEDACCOUNT)
    NETWORK_DISCONNECT_KICKED_UNTRUSTEDACCOUNT = 152,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_KICKED_CONVICTEDACCOUNT)
    NETWORK_DISCONNECT_KICKED_CONVICTEDACCOUNT = 153,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_KICKED_COMPETITIVECOOLDOWN)
    NETWORK_DISCONNECT_KICKED_COMPETITIVECOOLDOWN = 154,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_KICKED_TEAMHURTING)
    NETWORK_DISCONNECT_KICKED_TEAMHURTING = 155,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_KICKED_HOSTAGEKILLING)
    NETWORK_DISCONNECT_KICKED_HOSTAGEKILLING = 156,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_KICKED_VOTEDOFF)
    NETWORK_DISCONNECT_KICKED_VOTEDOFF = 157,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_KICKED_IDLE)
    NETWORK_DISCONNECT_KICKED_IDLE = 158,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_KICKED_SUICIDE)
    NETWORK_DISCONNECT_KICKED_SUICIDE = 159,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_KICKED_NOSTEAMLOGIN)
    NETWORK_DISCONNECT_KICKED_NOSTEAMLOGIN = 160,
    // @@protoc_insertion_point(enum_value:ENetworkDisconnectionReason.NETWORK_DISCONNECT_KICKED_NOSTEAMTICKET)
    NETWORK_DISCONNECT_KICKED_NOSTEAMTICKET = 161,
}

impl ::protobuf::Enum for ENetworkDisconnectionReason {
    const NAME: &'static str = "ENetworkDisconnectionReason";

    fn value(&self) -> i32 {
        *self as i32
    }

    fn from_i32(value: i32) -> ::std::option::Option<ENetworkDisconnectionReason> {
        match value {
            0 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_INVALID),
            1 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_SHUTDOWN),
            2 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_DISCONNECT_BY_USER),
            3 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_DISCONNECT_BY_SERVER),
            4 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_LOST),
            5 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_OVERFLOW),
            6 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_STEAM_BANNED),
            7 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_STEAM_INUSE),
            8 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_STEAM_TICKET),
            9 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_STEAM_LOGON),
            10 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_STEAM_AUTHCANCELLED),
            11 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_STEAM_AUTHALREADYUSED),
            12 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_STEAM_AUTHINVALID),
            13 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_STEAM_VACBANSTATE),
            14 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_STEAM_LOGGED_IN_ELSEWHERE),
            15 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_STEAM_VAC_CHECK_TIMEDOUT),
            16 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_STEAM_DROPPED),
            17 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_STEAM_OWNERSHIP),
            18 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_SERVERINFO_OVERFLOW),
            19 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_TICKMSG_OVERFLOW),
            20 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_STRINGTABLEMSG_OVERFLOW),
            21 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_DELTAENTMSG_OVERFLOW),
            22 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_TEMPENTMSG_OVERFLOW),
            23 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_SOUNDSMSG_OVERFLOW),
            24 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_SNAPSHOTOVERFLOW),
            25 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_SNAPSHOTERROR),
            26 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_RELIABLEOVERFLOW),
            27 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_BADDELTATICK),
            28 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_NOMORESPLITS),
            29 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_TIMEDOUT),
            30 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_DISCONNECTED),
            31 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_LEAVINGSPLIT),
            32 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_DIFFERENTCLASSTABLES),
            33 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_BADRELAYPASSWORD),
            34 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_BADSPECTATORPASSWORD),
            35 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_HLTVRESTRICTED),
            36 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_NOSPECTATORS),
            37 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_HLTVUNAVAILABLE),
            38 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_HLTVSTOP),
            39 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_KICKED),
            40 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_BANADDED),
            41 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_KICKBANADDED),
            42 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_HLTVDIRECT),
            43 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_PURESERVER_CLIENTEXTRA),
            44 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_PURESERVER_MISMATCH),
            45 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_USERCMD),
            46 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECTED_BY_GAME),
            47 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_MESSAGE_PARSE_ERROR),
            48 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_INVALID_MESSAGE_ERROR),
            49 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_BAD_SERVER_PASSWORD),
            50 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_DIRECT_CONNECT_RESERVATION),
            51 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_CONNECTION_FAILURE),
            52 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_NO_PEER_GROUP_HANDLERS),
            53 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_RECONNECTION),
            54 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_LOOPSHUTDOWN),
            55 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_LOOPDEACTIVATE),
            56 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_HOST_ENDGAME),
            57 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_LOOP_LEVELLOAD_ACTIVATE),
            58 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_CREATE_SERVER_FAILED),
            59 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_EXITING),
            60 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_REQUEST_HOSTSTATE_IDLE),
            61 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_REQUEST_HOSTSTATE_HLTVRELAY),
            62 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_CLIENT_CONSISTENCY_FAIL),
            63 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_CLIENT_UNABLE_TO_CRC_MAP),
            64 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_CLIENT_NO_MAP),
            65 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_CLIENT_DIFFERENT_MAP),
            66 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_SERVER_REQUIRES_STEAM),
            67 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_STEAM_DENY_MISC),
            68 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_STEAM_DENY_BAD_ANTI_CHEAT),
            69 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_SERVER_SHUTDOWN),
            71 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_REPLAY_INCOMPATIBLE),
            72 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_CONNECT_REQUEST_TIMEDOUT),
            73 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_SERVER_INCOMPATIBLE),
            74 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_LOCALPROBLEM_MANYRELAYS),
            75 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_LOCALPROBLEM_HOSTEDSERVERPRIMARYRELAY),
            76 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_LOCALPROBLEM_NETWORKCONFIG),
            77 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_LOCALPROBLEM_OTHER),
            79 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_REMOTE_TIMEOUT),
            80 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_REMOTE_TIMEOUT_CONNECTING),
            81 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_REMOTE_OTHER),
            82 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_REMOTE_BADCRYPT),
            83 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_REMOTE_CERTNOTTRUSTED),
            84 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_UNUSUAL),
            85 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_INTERNAL_ERROR),
            128 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_BADCHALLENGE),
            129 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_NOLOBBY),
            130 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_BACKGROUND_MAP),
            131 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_SINGLE_PLAYER),
            132 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_HIDDEN_GAME),
            133 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_LANRESTRICT),
            134 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_BADPASSWORD),
            135 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_SERVERFULL),
            136 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_INVALIDRESERVATION),
            137 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_FAILEDCHANNEL),
            138 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_CONNECT_FROM_LOBBY),
            139 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_RESERVED_FOR_LOBBY),
            140 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_INVALIDKEYLENGTH),
            141 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_OLDPROTOCOL),
            142 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_NEWPROTOCOL),
            143 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_INVALIDCONNECTION),
            144 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_INVALIDCERTLEN),
            145 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_INVALIDSTEAMCERTLEN),
            146 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_STEAM),
            147 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_SERVERAUTHDISABLED),
            148 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_SERVERCDKEYAUTHINVALID),
            149 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_BANNED),
            150 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_KICKED_TEAMKILLING),
            151 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_KICKED_TK_START),
            152 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_KICKED_UNTRUSTEDACCOUNT),
            153 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_KICKED_CONVICTEDACCOUNT),
            154 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_KICKED_COMPETITIVECOOLDOWN),
            155 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_KICKED_TEAMHURTING),
            156 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_KICKED_HOSTAGEKILLING),
            157 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_KICKED_VOTEDOFF),
            158 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_KICKED_IDLE),
            159 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_KICKED_SUICIDE),
            160 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_KICKED_NOSTEAMLOGIN),
            161 => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_KICKED_NOSTEAMTICKET),
            _ => ::std::option::Option::None
        }
    }

    fn from_str(str: &str) -> ::std::option::Option<ENetworkDisconnectionReason> {
        match str {
            "NETWORK_DISCONNECT_INVALID" => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_INVALID),
            "NETWORK_DISCONNECT_SHUTDOWN" => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_SHUTDOWN),
            "NETWORK_DISCONNECT_DISCONNECT_BY_USER" => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_DISCONNECT_BY_USER),
            "NETWORK_DISCONNECT_DISCONNECT_BY_SERVER" => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_DISCONNECT_BY_SERVER),
            "NETWORK_DISCONNECT_LOST" => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_LOST),
            "NETWORK_DISCONNECT_OVERFLOW" => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_OVERFLOW),
            "NETWORK_DISCONNECT_STEAM_BANNED" => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_STEAM_BANNED),
            "NETWORK_DISCONNECT_STEAM_INUSE" => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_STEAM_INUSE),
            "NETWORK_DISCONNECT_STEAM_TICKET" => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_STEAM_TICKET),
            "NETWORK_DISCONNECT_STEAM_LOGON" => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_STEAM_LOGON),
            "NETWORK_DISCONNECT_STEAM_AUTHCANCELLED" => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_STEAM_AUTHCANCELLED),
            "NETWORK_DISCONNECT_STEAM_AUTHALREADYUSED" => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_STEAM_AUTHALREADYUSED),
            "NETWORK_DISCONNECT_STEAM_AUTHINVALID" => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_STEAM_AUTHINVALID),
            "NETWORK_DISCONNECT_STEAM_VACBANSTATE" => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_STEAM_VACBANSTATE),
            "NETWORK_DISCONNECT_STEAM_LOGGED_IN_ELSEWHERE" => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_STEAM_LOGGED_IN_ELSEWHERE),
            "NETWORK_DISCONNECT_STEAM_VAC_CHECK_TIMEDOUT" => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_STEAM_VAC_CHECK_TIMEDOUT),
            "NETWORK_DISCONNECT_STEAM_DROPPED" => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_STEAM_DROPPED),
            "NETWORK_DISCONNECT_STEAM_OWNERSHIP" => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_STEAM_OWNERSHIP),
            "NETWORK_DISCONNECT_SERVERINFO_OVERFLOW" => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_SERVERINFO_OVERFLOW),
            "NETWORK_DISCONNECT_TICKMSG_OVERFLOW" => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_TICKMSG_OVERFLOW),
            "NETWORK_DISCONNECT_STRINGTABLEMSG_OVERFLOW" => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_STRINGTABLEMSG_OVERFLOW),
            "NETWORK_DISCONNECT_DELTAENTMSG_OVERFLOW" => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_DELTAENTMSG_OVERFLOW),
            "NETWORK_DISCONNECT_TEMPENTMSG_OVERFLOW" => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_TEMPENTMSG_OVERFLOW),
            "NETWORK_DISCONNECT_SOUNDSMSG_OVERFLOW" => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_SOUNDSMSG_OVERFLOW),
            "NETWORK_DISCONNECT_SNAPSHOTOVERFLOW" => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_SNAPSHOTOVERFLOW),
            "NETWORK_DISCONNECT_SNAPSHOTERROR" => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_SNAPSHOTERROR),
            "NETWORK_DISCONNECT_RELIABLEOVERFLOW" => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_RELIABLEOVERFLOW),
            "NETWORK_DISCONNECT_BADDELTATICK" => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_BADDELTATICK),
            "NETWORK_DISCONNECT_NOMORESPLITS" => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_NOMORESPLITS),
            "NETWORK_DISCONNECT_TIMEDOUT" => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_TIMEDOUT),
            "NETWORK_DISCONNECT_DISCONNECTED" => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_DISCONNECTED),
            "NETWORK_DISCONNECT_LEAVINGSPLIT" => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_LEAVINGSPLIT),
            "NETWORK_DISCONNECT_DIFFERENTCLASSTABLES" => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_DIFFERENTCLASSTABLES),
            "NETWORK_DISCONNECT_BADRELAYPASSWORD" => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_BADRELAYPASSWORD),
            "NETWORK_DISCONNECT_BADSPECTATORPASSWORD" => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_BADSPECTATORPASSWORD),
            "NETWORK_DISCONNECT_HLTVRESTRICTED" => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_HLTVRESTRICTED),
            "NETWORK_DISCONNECT_NOSPECTATORS" => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_NOSPECTATORS),
            "NETWORK_DISCONNECT_HLTVUNAVAILABLE" => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_HLTVUNAVAILABLE),
            "NETWORK_DISCONNECT_HLTVSTOP" => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_HLTVSTOP),
            "NETWORK_DISCONNECT_KICKED" => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_KICKED),
            "NETWORK_DISCONNECT_BANADDED" => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_BANADDED),
            "NETWORK_DISCONNECT_KICKBANADDED" => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_KICKBANADDED),
            "NETWORK_DISCONNECT_HLTVDIRECT" => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_HLTVDIRECT),
            "NETWORK_DISCONNECT_PURESERVER_CLIENTEXTRA" => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_PURESERVER_CLIENTEXTRA),
            "NETWORK_DISCONNECT_PURESERVER_MISMATCH" => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_PURESERVER_MISMATCH),
            "NETWORK_DISCONNECT_USERCMD" => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_USERCMD),
            "NETWORK_DISCONNECT_REJECTED_BY_GAME" => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECTED_BY_GAME),
            "NETWORK_DISCONNECT_MESSAGE_PARSE_ERROR" => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_MESSAGE_PARSE_ERROR),
            "NETWORK_DISCONNECT_INVALID_MESSAGE_ERROR" => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_INVALID_MESSAGE_ERROR),
            "NETWORK_DISCONNECT_BAD_SERVER_PASSWORD" => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_BAD_SERVER_PASSWORD),
            "NETWORK_DISCONNECT_DIRECT_CONNECT_RESERVATION" => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_DIRECT_CONNECT_RESERVATION),
            "NETWORK_DISCONNECT_CONNECTION_FAILURE" => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_CONNECTION_FAILURE),
            "NETWORK_DISCONNECT_NO_PEER_GROUP_HANDLERS" => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_NO_PEER_GROUP_HANDLERS),
            "NETWORK_DISCONNECT_RECONNECTION" => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_RECONNECTION),
            "NETWORK_DISCONNECT_LOOPSHUTDOWN" => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_LOOPSHUTDOWN),
            "NETWORK_DISCONNECT_LOOPDEACTIVATE" => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_LOOPDEACTIVATE),
            "NETWORK_DISCONNECT_HOST_ENDGAME" => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_HOST_ENDGAME),
            "NETWORK_DISCONNECT_LOOP_LEVELLOAD_ACTIVATE" => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_LOOP_LEVELLOAD_ACTIVATE),
            "NETWORK_DISCONNECT_CREATE_SERVER_FAILED" => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_CREATE_SERVER_FAILED),
            "NETWORK_DISCONNECT_EXITING" => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_EXITING),
            "NETWORK_DISCONNECT_REQUEST_HOSTSTATE_IDLE" => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_REQUEST_HOSTSTATE_IDLE),
            "NETWORK_DISCONNECT_REQUEST_HOSTSTATE_HLTVRELAY" => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_REQUEST_HOSTSTATE_HLTVRELAY),
            "NETWORK_DISCONNECT_CLIENT_CONSISTENCY_FAIL" => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_CLIENT_CONSISTENCY_FAIL),
            "NETWORK_DISCONNECT_CLIENT_UNABLE_TO_CRC_MAP" => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_CLIENT_UNABLE_TO_CRC_MAP),
            "NETWORK_DISCONNECT_CLIENT_NO_MAP" => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_CLIENT_NO_MAP),
            "NETWORK_DISCONNECT_CLIENT_DIFFERENT_MAP" => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_CLIENT_DIFFERENT_MAP),
            "NETWORK_DISCONNECT_SERVER_REQUIRES_STEAM" => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_SERVER_REQUIRES_STEAM),
            "NETWORK_DISCONNECT_STEAM_DENY_MISC" => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_STEAM_DENY_MISC),
            "NETWORK_DISCONNECT_STEAM_DENY_BAD_ANTI_CHEAT" => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_STEAM_DENY_BAD_ANTI_CHEAT),
            "NETWORK_DISCONNECT_SERVER_SHUTDOWN" => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_SERVER_SHUTDOWN),
            "NETWORK_DISCONNECT_REPLAY_INCOMPATIBLE" => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_REPLAY_INCOMPATIBLE),
            "NETWORK_DISCONNECT_CONNECT_REQUEST_TIMEDOUT" => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_CONNECT_REQUEST_TIMEDOUT),
            "NETWORK_DISCONNECT_SERVER_INCOMPATIBLE" => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_SERVER_INCOMPATIBLE),
            "NETWORK_DISCONNECT_LOCALPROBLEM_MANYRELAYS" => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_LOCALPROBLEM_MANYRELAYS),
            "NETWORK_DISCONNECT_LOCALPROBLEM_HOSTEDSERVERPRIMARYRELAY" => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_LOCALPROBLEM_HOSTEDSERVERPRIMARYRELAY),
            "NETWORK_DISCONNECT_LOCALPROBLEM_NETWORKCONFIG" => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_LOCALPROBLEM_NETWORKCONFIG),
            "NETWORK_DISCONNECT_LOCALPROBLEM_OTHER" => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_LOCALPROBLEM_OTHER),
            "NETWORK_DISCONNECT_REMOTE_TIMEOUT" => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_REMOTE_TIMEOUT),
            "NETWORK_DISCONNECT_REMOTE_TIMEOUT_CONNECTING" => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_REMOTE_TIMEOUT_CONNECTING),
            "NETWORK_DISCONNECT_REMOTE_OTHER" => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_REMOTE_OTHER),
            "NETWORK_DISCONNECT_REMOTE_BADCRYPT" => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_REMOTE_BADCRYPT),
            "NETWORK_DISCONNECT_REMOTE_CERTNOTTRUSTED" => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_REMOTE_CERTNOTTRUSTED),
            "NETWORK_DISCONNECT_UNUSUAL" => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_UNUSUAL),
            "NETWORK_DISCONNECT_INTERNAL_ERROR" => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_INTERNAL_ERROR),
            "NETWORK_DISCONNECT_REJECT_BADCHALLENGE" => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_BADCHALLENGE),
            "NETWORK_DISCONNECT_REJECT_NOLOBBY" => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_NOLOBBY),
            "NETWORK_DISCONNECT_REJECT_BACKGROUND_MAP" => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_BACKGROUND_MAP),
            "NETWORK_DISCONNECT_REJECT_SINGLE_PLAYER" => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_SINGLE_PLAYER),
            "NETWORK_DISCONNECT_REJECT_HIDDEN_GAME" => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_HIDDEN_GAME),
            "NETWORK_DISCONNECT_REJECT_LANRESTRICT" => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_LANRESTRICT),
            "NETWORK_DISCONNECT_REJECT_BADPASSWORD" => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_BADPASSWORD),
            "NETWORK_DISCONNECT_REJECT_SERVERFULL" => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_SERVERFULL),
            "NETWORK_DISCONNECT_REJECT_INVALIDRESERVATION" => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_INVALIDRESERVATION),
            "NETWORK_DISCONNECT_REJECT_FAILEDCHANNEL" => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_FAILEDCHANNEL),
            "NETWORK_DISCONNECT_REJECT_CONNECT_FROM_LOBBY" => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_CONNECT_FROM_LOBBY),
            "NETWORK_DISCONNECT_REJECT_RESERVED_FOR_LOBBY" => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_RESERVED_FOR_LOBBY),
            "NETWORK_DISCONNECT_REJECT_INVALIDKEYLENGTH" => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_INVALIDKEYLENGTH),
            "NETWORK_DISCONNECT_REJECT_OLDPROTOCOL" => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_OLDPROTOCOL),
            "NETWORK_DISCONNECT_REJECT_NEWPROTOCOL" => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_NEWPROTOCOL),
            "NETWORK_DISCONNECT_REJECT_INVALIDCONNECTION" => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_INVALIDCONNECTION),
            "NETWORK_DISCONNECT_REJECT_INVALIDCERTLEN" => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_INVALIDCERTLEN),
            "NETWORK_DISCONNECT_REJECT_INVALIDSTEAMCERTLEN" => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_INVALIDSTEAMCERTLEN),
            "NETWORK_DISCONNECT_REJECT_STEAM" => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_STEAM),
            "NETWORK_DISCONNECT_REJECT_SERVERAUTHDISABLED" => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_SERVERAUTHDISABLED),
            "NETWORK_DISCONNECT_REJECT_SERVERCDKEYAUTHINVALID" => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_SERVERCDKEYAUTHINVALID),
            "NETWORK_DISCONNECT_REJECT_BANNED" => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_BANNED),
            "NETWORK_DISCONNECT_KICKED_TEAMKILLING" => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_KICKED_TEAMKILLING),
            "NETWORK_DISCONNECT_KICKED_TK_START" => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_KICKED_TK_START),
            "NETWORK_DISCONNECT_KICKED_UNTRUSTEDACCOUNT" => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_KICKED_UNTRUSTEDACCOUNT),
            "NETWORK_DISCONNECT_KICKED_CONVICTEDACCOUNT" => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_KICKED_CONVICTEDACCOUNT),
            "NETWORK_DISCONNECT_KICKED_COMPETITIVECOOLDOWN" => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_KICKED_COMPETITIVECOOLDOWN),
            "NETWORK_DISCONNECT_KICKED_TEAMHURTING" => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_KICKED_TEAMHURTING),
            "NETWORK_DISCONNECT_KICKED_HOSTAGEKILLING" => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_KICKED_HOSTAGEKILLING),
            "NETWORK_DISCONNECT_KICKED_VOTEDOFF" => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_KICKED_VOTEDOFF),
            "NETWORK_DISCONNECT_KICKED_IDLE" => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_KICKED_IDLE),
            "NETWORK_DISCONNECT_KICKED_SUICIDE" => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_KICKED_SUICIDE),
            "NETWORK_DISCONNECT_KICKED_NOSTEAMLOGIN" => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_KICKED_NOSTEAMLOGIN),
            "NETWORK_DISCONNECT_KICKED_NOSTEAMTICKET" => ::std::option::Option::Some(ENetworkDisconnectionReason::NETWORK_DISCONNECT_KICKED_NOSTEAMTICKET),
            _ => ::std::option::Option::None
        }
    }

    const VALUES: &'static [ENetworkDisconnectionReason] = &[
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_INVALID,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_SHUTDOWN,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_DISCONNECT_BY_USER,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_DISCONNECT_BY_SERVER,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_LOST,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_OVERFLOW,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_STEAM_BANNED,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_STEAM_INUSE,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_STEAM_TICKET,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_STEAM_LOGON,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_STEAM_AUTHCANCELLED,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_STEAM_AUTHALREADYUSED,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_STEAM_AUTHINVALID,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_STEAM_VACBANSTATE,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_STEAM_LOGGED_IN_ELSEWHERE,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_STEAM_VAC_CHECK_TIMEDOUT,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_STEAM_DROPPED,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_STEAM_OWNERSHIP,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_SERVERINFO_OVERFLOW,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_TICKMSG_OVERFLOW,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_STRINGTABLEMSG_OVERFLOW,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_DELTAENTMSG_OVERFLOW,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_TEMPENTMSG_OVERFLOW,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_SOUNDSMSG_OVERFLOW,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_SNAPSHOTOVERFLOW,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_SNAPSHOTERROR,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_RELIABLEOVERFLOW,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_BADDELTATICK,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_NOMORESPLITS,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_TIMEDOUT,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_DISCONNECTED,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_LEAVINGSPLIT,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_DIFFERENTCLASSTABLES,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_BADRELAYPASSWORD,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_BADSPECTATORPASSWORD,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_HLTVRESTRICTED,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_NOSPECTATORS,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_HLTVUNAVAILABLE,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_HLTVSTOP,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_KICKED,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_BANADDED,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_KICKBANADDED,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_HLTVDIRECT,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_PURESERVER_CLIENTEXTRA,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_PURESERVER_MISMATCH,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_USERCMD,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECTED_BY_GAME,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_MESSAGE_PARSE_ERROR,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_INVALID_MESSAGE_ERROR,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_BAD_SERVER_PASSWORD,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_DIRECT_CONNECT_RESERVATION,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_CONNECTION_FAILURE,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_NO_PEER_GROUP_HANDLERS,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_RECONNECTION,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_LOOPSHUTDOWN,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_LOOPDEACTIVATE,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_HOST_ENDGAME,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_LOOP_LEVELLOAD_ACTIVATE,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_CREATE_SERVER_FAILED,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_EXITING,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_REQUEST_HOSTSTATE_IDLE,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_REQUEST_HOSTSTATE_HLTVRELAY,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_CLIENT_CONSISTENCY_FAIL,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_CLIENT_UNABLE_TO_CRC_MAP,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_CLIENT_NO_MAP,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_CLIENT_DIFFERENT_MAP,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_SERVER_REQUIRES_STEAM,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_STEAM_DENY_MISC,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_STEAM_DENY_BAD_ANTI_CHEAT,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_SERVER_SHUTDOWN,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_REPLAY_INCOMPATIBLE,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_CONNECT_REQUEST_TIMEDOUT,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_SERVER_INCOMPATIBLE,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_LOCALPROBLEM_MANYRELAYS,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_LOCALPROBLEM_HOSTEDSERVERPRIMARYRELAY,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_LOCALPROBLEM_NETWORKCONFIG,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_LOCALPROBLEM_OTHER,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_REMOTE_TIMEOUT,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_REMOTE_TIMEOUT_CONNECTING,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_REMOTE_OTHER,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_REMOTE_BADCRYPT,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_REMOTE_CERTNOTTRUSTED,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_UNUSUAL,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_INTERNAL_ERROR,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_BADCHALLENGE,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_NOLOBBY,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_BACKGROUND_MAP,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_SINGLE_PLAYER,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_HIDDEN_GAME,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_LANRESTRICT,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_BADPASSWORD,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_SERVERFULL,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_INVALIDRESERVATION,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_FAILEDCHANNEL,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_CONNECT_FROM_LOBBY,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_RESERVED_FOR_LOBBY,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_INVALIDKEYLENGTH,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_OLDPROTOCOL,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_NEWPROTOCOL,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_INVALIDCONNECTION,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_INVALIDCERTLEN,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_INVALIDSTEAMCERTLEN,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_STEAM,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_SERVERAUTHDISABLED,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_SERVERCDKEYAUTHINVALID,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_BANNED,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_KICKED_TEAMKILLING,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_KICKED_TK_START,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_KICKED_UNTRUSTEDACCOUNT,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_KICKED_CONVICTEDACCOUNT,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_KICKED_COMPETITIVECOOLDOWN,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_KICKED_TEAMHURTING,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_KICKED_HOSTAGEKILLING,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_KICKED_VOTEDOFF,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_KICKED_IDLE,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_KICKED_SUICIDE,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_KICKED_NOSTEAMLOGIN,
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_KICKED_NOSTEAMTICKET,
    ];
}

impl ::protobuf::EnumFull for ENetworkDisconnectionReason {
    fn enum_descriptor() -> ::protobuf::reflect::EnumDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::EnumDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().enum_by_package_relative_name("ENetworkDisconnectionReason").unwrap()).clone()
    }

    fn descriptor(&self) -> ::protobuf::reflect::EnumValueDescriptor {
        let index = match self {
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_INVALID => 0,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_SHUTDOWN => 1,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_DISCONNECT_BY_USER => 2,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_DISCONNECT_BY_SERVER => 3,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_LOST => 4,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_OVERFLOW => 5,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_STEAM_BANNED => 6,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_STEAM_INUSE => 7,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_STEAM_TICKET => 8,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_STEAM_LOGON => 9,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_STEAM_AUTHCANCELLED => 10,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_STEAM_AUTHALREADYUSED => 11,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_STEAM_AUTHINVALID => 12,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_STEAM_VACBANSTATE => 13,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_STEAM_LOGGED_IN_ELSEWHERE => 14,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_STEAM_VAC_CHECK_TIMEDOUT => 15,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_STEAM_DROPPED => 16,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_STEAM_OWNERSHIP => 17,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_SERVERINFO_OVERFLOW => 18,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_TICKMSG_OVERFLOW => 19,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_STRINGTABLEMSG_OVERFLOW => 20,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_DELTAENTMSG_OVERFLOW => 21,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_TEMPENTMSG_OVERFLOW => 22,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_SOUNDSMSG_OVERFLOW => 23,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_SNAPSHOTOVERFLOW => 24,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_SNAPSHOTERROR => 25,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_RELIABLEOVERFLOW => 26,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_BADDELTATICK => 27,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_NOMORESPLITS => 28,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_TIMEDOUT => 29,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_DISCONNECTED => 30,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_LEAVINGSPLIT => 31,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_DIFFERENTCLASSTABLES => 32,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_BADRELAYPASSWORD => 33,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_BADSPECTATORPASSWORD => 34,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_HLTVRESTRICTED => 35,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_NOSPECTATORS => 36,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_HLTVUNAVAILABLE => 37,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_HLTVSTOP => 38,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_KICKED => 39,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_BANADDED => 40,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_KICKBANADDED => 41,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_HLTVDIRECT => 42,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_PURESERVER_CLIENTEXTRA => 43,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_PURESERVER_MISMATCH => 44,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_USERCMD => 45,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECTED_BY_GAME => 46,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_MESSAGE_PARSE_ERROR => 47,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_INVALID_MESSAGE_ERROR => 48,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_BAD_SERVER_PASSWORD => 49,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_DIRECT_CONNECT_RESERVATION => 50,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_CONNECTION_FAILURE => 51,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_NO_PEER_GROUP_HANDLERS => 52,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_RECONNECTION => 53,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_LOOPSHUTDOWN => 54,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_LOOPDEACTIVATE => 55,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_HOST_ENDGAME => 56,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_LOOP_LEVELLOAD_ACTIVATE => 57,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_CREATE_SERVER_FAILED => 58,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_EXITING => 59,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_REQUEST_HOSTSTATE_IDLE => 60,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_REQUEST_HOSTSTATE_HLTVRELAY => 61,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_CLIENT_CONSISTENCY_FAIL => 62,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_CLIENT_UNABLE_TO_CRC_MAP => 63,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_CLIENT_NO_MAP => 64,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_CLIENT_DIFFERENT_MAP => 65,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_SERVER_REQUIRES_STEAM => 66,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_STEAM_DENY_MISC => 67,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_STEAM_DENY_BAD_ANTI_CHEAT => 68,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_SERVER_SHUTDOWN => 69,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_REPLAY_INCOMPATIBLE => 70,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_CONNECT_REQUEST_TIMEDOUT => 71,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_SERVER_INCOMPATIBLE => 72,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_LOCALPROBLEM_MANYRELAYS => 73,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_LOCALPROBLEM_HOSTEDSERVERPRIMARYRELAY => 74,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_LOCALPROBLEM_NETWORKCONFIG => 75,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_LOCALPROBLEM_OTHER => 76,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_REMOTE_TIMEOUT => 77,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_REMOTE_TIMEOUT_CONNECTING => 78,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_REMOTE_OTHER => 79,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_REMOTE_BADCRYPT => 80,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_REMOTE_CERTNOTTRUSTED => 81,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_UNUSUAL => 82,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_INTERNAL_ERROR => 83,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_BADCHALLENGE => 84,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_NOLOBBY => 85,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_BACKGROUND_MAP => 86,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_SINGLE_PLAYER => 87,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_HIDDEN_GAME => 88,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_LANRESTRICT => 89,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_BADPASSWORD => 90,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_SERVERFULL => 91,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_INVALIDRESERVATION => 92,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_FAILEDCHANNEL => 93,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_CONNECT_FROM_LOBBY => 94,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_RESERVED_FOR_LOBBY => 95,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_INVALIDKEYLENGTH => 96,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_OLDPROTOCOL => 97,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_NEWPROTOCOL => 98,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_INVALIDCONNECTION => 99,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_INVALIDCERTLEN => 100,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_INVALIDSTEAMCERTLEN => 101,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_STEAM => 102,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_SERVERAUTHDISABLED => 103,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_SERVERCDKEYAUTHINVALID => 104,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_REJECT_BANNED => 105,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_KICKED_TEAMKILLING => 106,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_KICKED_TK_START => 107,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_KICKED_UNTRUSTEDACCOUNT => 108,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_KICKED_CONVICTEDACCOUNT => 109,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_KICKED_COMPETITIVECOOLDOWN => 110,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_KICKED_TEAMHURTING => 111,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_KICKED_HOSTAGEKILLING => 112,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_KICKED_VOTEDOFF => 113,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_KICKED_IDLE => 114,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_KICKED_SUICIDE => 115,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_KICKED_NOSTEAMLOGIN => 116,
            ENetworkDisconnectionReason::NETWORK_DISCONNECT_KICKED_NOSTEAMTICKET => 117,
        };
        Self::enum_descriptor().value_by_index(index)
    }
}

impl ::std::default::Default for ENetworkDisconnectionReason {
    fn default() -> Self {
        ENetworkDisconnectionReason::NETWORK_DISCONNECT_INVALID
    }
}

impl ENetworkDisconnectionReason {
    fn generated_enum_descriptor_data() -> ::protobuf::reflect::GeneratedEnumDescriptorData {
        ::protobuf::reflect::GeneratedEnumDescriptorData::new::<ENetworkDisconnectionReason>("ENetworkDisconnectionReason")
    }
}

/// Extension fields
pub mod exts {

    pub const network_connection_token: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::EnumValueOptions, ::std::string::String> = ::protobuf::ext::ExtFieldOptional::new(50500, ::protobuf::descriptor::field_descriptor_proto::Type::TYPE_STRING);
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x18network_connection.proto\x1a\x20google/protobuf/descriptor.proto*\
    \xceJ\n\x1bENetworkDisconnectionReason\x12\x1e\n\x1aNETWORK_DISCONNECT_I\
    NVALID\x10\0\x12\x1f\n\x1bNETWORK_DISCONNECT_SHUTDOWN\x10\x01\x12F\n%NET\
    WORK_DISCONNECT_DISCONNECT_BY_USER\x10\x02\x1a\x1b\xa2\xd4\x18\x17#GameU\
    I_Disconnect_User\x12J\n'NETWORK_DISCONNECT_DISCONNECT_BY_SERVER\x10\x03\
    \x1a\x1d\xa2\xd4\x18\x19#GameUI_Disconnect_Server\x12B\n\x17NETWORK_DISC\
    ONNECT_LOST\x10\x04\x1a%\xa2\xd4\x18!#GameUI_Disconnect_ConnectionLost\
    \x12J\n\x1bNETWORK_DISCONNECT_OVERFLOW\x10\x05\x1a)\xa2\xd4\x18%#GameUI_\
    Disconnect_ConnectionOverflow\x12I\n\x1fNETWORK_DISCONNECT_STEAM_BANNED\
    \x10\x06\x1a$\xa2\xd4\x18\x20#GameUI_Disconnect_SteamIDBanned\x12G\n\x1e\
    NETWORK_DISCONNECT_STEAM_INUSE\x10\x07\x1a#\xa2\xd4\x18\x1f#GameUI_Disco\
    nnect_SteamIDInUse\x12G\n\x1fNETWORK_DISCONNECT_STEAM_TICKET\x10\x08\x1a\
    \"\xa2\xd4\x18\x1e#GameUI_Disconnect_SteamTicket\x12E\n\x1eNETWORK_DISCO\
    NNECT_STEAM_LOGON\x10\t\x1a!\xa2\xd4\x18\x1d#GameUI_Disconnect_SteamLogo\
    n\x12M\n&NETWORK_DISCONNECT_STEAM_AUTHCANCELLED\x10\n\x1a!\xa2\xd4\x18\
    \x1d#GameUI_Disconnect_SteamLogon\x12O\n(NETWORK_DISCONNECT_STEAM_AUTHAL\
    READYUSED\x10\x0b\x1a!\xa2\xd4\x18\x1d#GameUI_Disconnect_SteamLogon\x12K\
    \n$NETWORK_DISCONNECT_STEAM_AUTHINVALID\x10\x0c\x1a!\xa2\xd4\x18\x1d#Gam\
    eUI_Disconnect_SteamLogon\x12I\n$NETWORK_DISCONNECT_STEAM_VACBANSTATE\
    \x10\r\x1a\x1f\xa2\xd4\x18\x1b#GameUI_Disconnect_SteamVAC\x12S\n,NETWORK\
    _DISCONNECT_STEAM_LOGGED_IN_ELSEWHERE\x10\x0e\x1a!\xa2\xd4\x18\x1d#GameU\
    I_Disconnect_SteamInUse\x12T\n+NETWORK_DISCONNECT_STEAM_VAC_CHECK_TIMEDO\
    UT\x10\x0f\x1a#\xa2\xd4\x18\x1f#GameUI_Disconnect_SteamTimeOut\x12I\n\
    \x20NETWORK_DISCONNECT_STEAM_DROPPED\x10\x10\x1a#\xa2\xd4\x18\x1f#GameUI\
    _Disconnect_SteamDropped\x12M\n\"NETWORK_DISCONNECT_STEAM_OWNERSHIP\x10\
    \x11\x1a%\xa2\xd4\x18!#GameUI_Disconnect_SteamOwnership\x12U\n&NETWORK_D\
    ISCONNECT_SERVERINFO_OVERFLOW\x10\x12\x1a)\xa2\xd4\x18%#GameUI_Disconnec\
    t_ServerInfoOverflow\x12K\n#NETWORK_DISCONNECT_TICKMSG_OVERFLOW\x10\x13\
    \x1a\"\xa2\xd4\x18\x1e#GameUI_Disconnect_TickMessage\x12Y\n*NETWORK_DISC\
    ONNECT_STRINGTABLEMSG_OVERFLOW\x10\x14\x1a)\xa2\xd4\x18%#GameUI_Disconne\
    ct_StringTableMessage\x12S\n'NETWORK_DISCONNECT_DELTAENTMSG_OVERFLOW\x10\
    \x15\x1a&\xa2\xd4\x18\"#GameUI_Disconnect_DeltaEntMessage\x12Q\n&NETWORK\
    _DISCONNECT_TEMPENTMSG_OVERFLOW\x10\x16\x1a%\xa2\xd4\x18!#GameUI_Disconn\
    ect_TempEntMessage\x12O\n%NETWORK_DISCONNECT_SOUNDSMSG_OVERFLOW\x10\x17\
    \x1a$\xa2\xd4\x18\x20#GameUI_Disconnect_SoundsMessage\x12P\n#NETWORK_DIS\
    CONNECT_SNAPSHOTOVERFLOW\x10\x18\x1a'\xa2\xd4\x18##GameUI_Disconnect_Sna\
    pshotOverflow\x12J\n\x20NETWORK_DISCONNECT_SNAPSHOTERROR\x10\x19\x1a$\
    \xa2\xd4\x18\x20#GameUI_Disconnect_SnapshotError\x12P\n#NETWORK_DISCONNE\
    CT_RELIABLEOVERFLOW\x10\x1a\x1a'\xa2\xd4\x18##GameUI_Disconnect_Reliable\
    Overflow\x12N\n\x1fNETWORK_DISCONNECT_BADDELTATICK\x10\x1b\x1a)\xa2\xd4\
    \x18%#GameUI_Disconnect_BadClientDeltaTick\x12H\n\x1fNETWORK_DISCONNECT_\
    NOMORESPLITS\x10\x1c\x1a#\xa2\xd4\x18\x1f#GameUI_Disconnect_NoMoreSplits\
    \x12@\n\x1bNETWORK_DISCONNECT_TIMEDOUT\x10\x1d\x1a\x1f\xa2\xd4\x18\x1b#G\
    ameUI_Disconnect_TimedOut\x12H\n\x1fNETWORK_DISCONNECT_DISCONNECTED\x10\
    \x1e\x1a#\xa2\xd4\x18\x1f#GameUI_Disconnect_Disconnected\x12H\n\x1fNETWO\
    RK_DISCONNECT_LEAVINGSPLIT\x10\x1f\x1a#\xa2\xd4\x18\x1f#GameUI_Disconnec\
    t_LeavingSplit\x12X\n'NETWORK_DISCONNECT_DIFFERENTCLASSTABLES\x10\x20\
    \x1a+\xa2\xd4\x18'#GameUI_Disconnect_DifferentClassTables\x12P\n#NETWORK\
    _DISCONNECT_BADRELAYPASSWORD\x10!\x1a'\xa2\xd4\x18##GameUI_Disconnect_Ba\
    dRelayPassword\x12X\n'NETWORK_DISCONNECT_BADSPECTATORPASSWORD\x10\"\x1a+\
    \xa2\xd4\x18'#GameUI_Disconnect_BadSpectatorPassword\x12L\n!NETWORK_DISC\
    ONNECT_HLTVRESTRICTED\x10#\x1a%\xa2\xd4\x18!#GameUI_Disconnect_HLTVRestr\
    icted\x12H\n\x1fNETWORK_DISCONNECT_NOSPECTATORS\x10$\x1a#\xa2\xd4\x18\
    \x1f#GameUI_Disconnect_NoSpectators\x12N\n\"NETWORK_DISCONNECT_HLTVUNAVA\
    ILABLE\x10%\x1a&\xa2\xd4\x18\"#GameUI_Disconnect_HLTVUnavailable\x12@\n\
    \x1bNETWORK_DISCONNECT_HLTVSTOP\x10&\x1a\x1f\xa2\xd4\x18\x1b#GameUI_Disc\
    onnect_HLTVStop\x12<\n\x19NETWORK_DISCONNECT_KICKED\x10'\x1a\x1d\xa2\xd4\
    \x18\x19#GameUI_Disconnect_Kicked\x12@\n\x1bNETWORK_DISCONNECT_BANADDED\
    \x10(\x1a\x1f\xa2\xd4\x18\x1b#GameUI_Disconnect_BanAdded\x12H\n\x1fNETWO\
    RK_DISCONNECT_KICKBANADDED\x10)\x1a#\xa2\xd4\x18\x1f#GameUI_Disconnect_K\
    ickBanAdded\x12D\n\x1dNETWORK_DISCONNECT_HLTVDIRECT\x10*\x1a!\xa2\xd4\
    \x18\x1d#GameUI_Disconnect_HLTVDirect\x12\\\n)NETWORK_DISCONNECT_PURESER\
    VER_CLIENTEXTRA\x10+\x1a-\xa2\xd4\x18)#GameUI_Disconnect_PureServer_Clie\
    ntExtra\x12V\n&NETWORK_DISCONNECT_PURESERVER_MISMATCH\x10,\x1a*\xa2\xd4\
    \x18&#GameUI_Disconnect_PureServer_Mismatch\x12>\n\x1aNETWORK_DISCONNECT\
    _USERCMD\x10-\x1a\x1e\xa2\xd4\x18\x1a#GameUI_Disconnect_UserCmd\x12N\n#N\
    ETWORK_DISCONNECT_REJECTED_BY_GAME\x10.\x1a%\xa2\xd4\x18!#GameUI_Disconn\
    ect_RejectedByGame\x12T\n&NETWORK_DISCONNECT_MESSAGE_PARSE_ERROR\x10/\
    \x1a(\xa2\xd4\x18$#GameUI_Disconnect_MessageParseError\x12X\n(NETWORK_DI\
    SCONNECT_INVALID_MESSAGE_ERROR\x100\x1a*\xa2\xd4\x18&#GameUI_Disconnect_\
    InvalidMessageError\x12T\n&NETWORK_DISCONNECT_BAD_SERVER_PASSWORD\x101\
    \x1a(\xa2\xd4\x18$#GameUI_Disconnect_BadServerPassword\x121\n-NETWORK_DI\
    SCONNECT_DIRECT_CONNECT_RESERVATION\x102\x12S\n%NETWORK_DISCONNECT_CONNE\
    CTION_FAILURE\x103\x1a(\xa2\xd4\x18$#GameUI_Disconnect_ConnectionFailure\
    \x12Y\n)NETWORK_DISCONNECT_NO_PEER_GROUP_HANDLERS\x104\x1a*\xa2\xd4\x18&\
    #GameUI_Disconnect_NoPeerGroupHandlers\x12#\n\x1fNETWORK_DISCONNECT_RECO\
    NNECTION\x105\x12H\n\x1fNETWORK_DISCONNECT_LOOPSHUTDOWN\x106\x1a#\xa2\
    \xd4\x18\x1f#GameUI_Disconnect_LoopShutdown\x12L\n!NETWORK_DISCONNECT_LO\
    OPDEACTIVATE\x107\x1a%\xa2\xd4\x18!#GameUI_Disconnect_LoopDeactivate\x12\
    H\n\x1fNETWORK_DISCONNECT_HOST_ENDGAME\x108\x1a#\xa2\xd4\x18\x1f#GameUI_\
    Disconnect_Host_EndGame\x12\\\n*NETWORK_DISCONNECT_LOOP_LEVELLOAD_ACTIVA\
    TE\x109\x1a,\xa2\xd4\x18(#GameUI_Disconnect_LoopLevelLoadActivate\x12V\n\
    'NETWORK_DISCONNECT_CREATE_SERVER_FAILED\x10:\x1a)\xa2\xd4\x18%#GameUI_D\
    isconnect_CreateServerFailed\x12D\n\x1aNETWORK_DISCONNECT_EXITING\x10;\
    \x1a$\xa2\xd4\x18\x20#GameUI_Disconnect_ExitingEngine\x12T\n)NETWORK_DIS\
    CONNECT_REQUEST_HOSTSTATE_IDLE\x10<\x1a%\xa2\xd4\x18!#GameUI_Disconnect_\
    Request_HSIdle\x12\\\n.NETWORK_DISCONNECT_REQUEST_HOSTSTATE_HLTVRELAY\
    \x10=\x1a(\xa2\xd4\x18$#GameUI_Disconnect_Request_HLTVRelay\x12Q\n*NETWO\
    RK_DISCONNECT_CLIENT_CONSISTENCY_FAIL\x10>\x1a!\xa2\xd4\x18\x1d#GameUI_C\
    lientConsistencyFail\x12Q\n+NETWORK_DISCONNECT_CLIENT_UNABLE_TO_CRC_MAP\
    \x10?\x1a\x20\xa2\xd4\x18\x1c#GameUI_ClientUnableToCRCMap\x12=\n\x20NETW\
    ORK_DISCONNECT_CLIENT_NO_MAP\x10@\x1a\x17\xa2\xd4\x18\x13#GameUI_ClientN\
    oMap\x12K\n'NETWORK_DISCONNECT_CLIENT_DIFFERENT_MAP\x10A\x1a\x1e\xa2\xd4\
    \x18\x1a#GameUI_ClientDifferentMap\x12M\n(NETWORK_DISCONNECT_SERVER_REQU\
    IRES_STEAM\x10B\x1a\x1f\xa2\xd4\x18\x1b#GameUI_ServerRequireSteams\x12M\
    \n\"NETWORK_DISCONNECT_STEAM_DENY_MISC\x10C\x1a%\xa2\xd4\x18!#GameUI_Dis\
    connect_SteamDeny_Misc\x12_\n,NETWORK_DISCONNECT_STEAM_DENY_BAD_ANTI_CHE\
    AT\x10D\x1a-\xa2\xd4\x18)#GameUI_Disconnect_SteamDeny_BadAntiCheat\x12M\
    \n\"NETWORK_DISCONNECT_SERVER_SHUTDOWN\x10E\x1a%\xa2\xd4\x18!#GameUI_Dis\
    connect_ServerShutdown\x12U\n&NETWORK_DISCONNECT_REPLAY_INCOMPATIBLE\x10\
    G\x1a)\xa2\xd4\x18%#GameUI_Disconnect_ReplayIncompatible\x12Z\n+NETWORK_\
    DISCONNECT_CONNECT_REQUEST_TIMEDOUT\x10H\x1a)\xa2\xd4\x18%#GameUI_Discon\
    nect_ConnectionTimedout\x12U\n&NETWORK_DISCONNECT_SERVER_INCOMPATIBLE\
    \x10I\x1a)\xa2\xd4\x18%#GameUI_Disconnect_ServerIncompatible\x12^\n*NETW\
    ORK_DISCONNECT_LOCALPROBLEM_MANYRELAYS\x10J\x1a.\xa2\xd4\x18*#GameUI_Dis\
    connect_LocalProblem_ManyRelays\x12z\n8NETWORK_DISCONNECT_LOCALPROBLEM_H\
    OSTEDSERVERPRIMARYRELAY\x10K\x1a<\xa2\xd4\x188#GameUI_Disconnect_LocalPr\
    oblem_HostedServerPrimaryRelay\x12d\n-NETWORK_DISCONNECT_LOCALPROBLEM_NE\
    TWORKCONFIG\x10L\x1a1\xa2\xd4\x18-#GameUI_Disconnect_LocalProblem_Networ\
    kConfig\x12T\n%NETWORK_DISCONNECT_LOCALPROBLEM_OTHER\x10M\x1a)\xa2\xd4\
    \x18%#GameUI_Disconnect_LocalProblem_Other\x12S\n!NETWORK_DISCONNECT_REM\
    OTE_TIMEOUT\x10O\x1a,\xa2\xd4\x18(#GameUI_Disconnect_RemoteProblem_Timeo\
    ut\x12h\n,NETWORK_DISCONNECT_REMOTE_TIMEOUT_CONNECTING\x10P\x1a6\xa2\xd4\
    \x182#GameUI_Disconnect_RemoteProblem_TimeoutConnecting\x12O\n\x1fNETWOR\
    K_DISCONNECT_REMOTE_OTHER\x10Q\x1a*\xa2\xd4\x18&#GameUI_Disconnect_Remot\
    eProblem_Other\x12U\n\"NETWORK_DISCONNECT_REMOTE_BADCRYPT\x10R\x1a-\xa2\
    \xd4\x18)#GameUI_Disconnect_RemoteProblem_BadCrypt\x12Z\n(NETWORK_DISCON\
    NECT_REMOTE_CERTNOTTRUSTED\x10S\x1a,\xa2\xd4\x18(#GameUI_Disconnect_Remo\
    teProblem_BadCert\x12>\n\x1aNETWORK_DISCONNECT_UNUSUAL\x10T\x1a\x1e\xa2\
    \xd4\x18\x1a#GameUI_Disconnect_Unusual\x12K\n!NETWORK_DISCONNECT_INTERNA\
    L_ERROR\x10U\x1a$\xa2\xd4\x18\x20#GameUI_Disconnect_InternalError\x12Q\n\
    &NETWORK_DISCONNECT_REJECT_BADCHALLENGE\x10\x80\x01\x1a$\xa2\xd4\x18\x20\
    #GameUI_ServerRejectBadChallenge\x12A\n!NETWORK_DISCONNECT_REJECT_NOLOBB\
    Y\x10\x81\x01\x1a\x19\xa2\xd4\x18\x15#GameUI_ServerNoLobby\x12O\n(NETWOR\
    K_DISCONNECT_REJECT_BACKGROUND_MAP\x10\x82\x01\x1a\x20\xa2\xd4\x18\x1c#V\
    alve_Reject_Background_Map\x12M\n'NETWORK_DISCONNECT_REJECT_SINGLE_PLAYE\
    R\x10\x83\x01\x1a\x1f\xa2\xd4\x18\x1b#Valve_Reject_Single_Player\x12I\n%\
    NETWORK_DISCONNECT_REJECT_HIDDEN_GAME\x10\x84\x01\x1a\x1d\xa2\xd4\x18\
    \x19#Valve_Reject_Hidden_Game\x12O\n%NETWORK_DISCONNECT_REJECT_LANRESTRI\
    CT\x10\x85\x01\x1a#\xa2\xd4\x18\x1f#GameUI_ServerRejectLANRestrict\x12O\
    \n%NETWORK_DISCONNECT_REJECT_BADPASSWORD\x10\x86\x01\x1a#\xa2\xd4\x18\
    \x1f#GameUI_ServerRejectBadPassword\x12M\n$NETWORK_DISCONNECT_REJECT_SER\
    VERFULL\x10\x87\x01\x1a\"\xa2\xd4\x18\x1e#GameUI_ServerRejectServerFull\
    \x12]\n,NETWORK_DISCONNECT_REJECT_INVALIDRESERVATION\x10\x88\x01\x1a*\
    \xa2\xd4\x18&#GameUI_ServerRejectInvalidReservation\x12S\n'NETWORK_DISCO\
    NNECT_REJECT_FAILEDCHANNEL\x10\x89\x01\x1a%\xa2\xd4\x18!#GameUI_ServerRe\
    jectFailedChannel\x12W\n,NETWORK_DISCONNECT_REJECT_CONNECT_FROM_LOBBY\
    \x10\x8a\x01\x1a$\xa2\xd4\x18\x20#Valve_Reject_Connect_From_Lobby\x12W\n\
    ,NETWORK_DISCONNECT_REJECT_RESERVED_FOR_LOBBY\x10\x8b\x01\x1a$\xa2\xd4\
    \x18\x20#Valve_Reject_Reserved_For_Lobby\x12Z\n*NETWORK_DISCONNECT_REJEC\
    T_INVALIDKEYLENGTH\x10\x8c\x01\x1a)\xa2\xd4\x18%#GameUI_ServerReject_Inv\
    alidKeyLength\x12O\n%NETWORK_DISCONNECT_REJECT_OLDPROTOCOL\x10\x8d\x01\
    \x1a#\xa2\xd4\x18\x1f#GameUI_ServerRejectOldProtocol\x12O\n%NETWORK_DISC\
    ONNECT_REJECT_NEWPROTOCOL\x10\x8e\x01\x1a#\xa2\xd4\x18\x1f#GameUI_Server\
    RejectNewProtocol\x12[\n+NETWORK_DISCONNECT_REJECT_INVALIDCONNECTION\x10\
    \x8f\x01\x1a)\xa2\xd4\x18%#GameUI_ServerRejectInvalidConnection\x12U\n(N\
    ETWORK_DISCONNECT_REJECT_INVALIDCERTLEN\x10\x90\x01\x1a&\xa2\xd4\x18\"#G\
    ameUI_ServerRejectInvalidCertLen\x12_\n-NETWORK_DISCONNECT_REJECT_INVALI\
    DSTEAMCERTLEN\x10\x91\x01\x1a+\xa2\xd4\x18'#GameUI_ServerRejectInvalidSt\
    eamCertLen\x12C\n\x1fNETWORK_DISCONNECT_REJECT_STEAM\x10\x92\x01\x1a\x1d\
    \xa2\xd4\x18\x19#GameUI_ServerRejectSteam\x12Q\n,NETWORK_DISCONNECT_REJE\
    CT_SERVERAUTHDISABLED\x10\x93\x01\x1a\x1e\xa2\xd4\x18\x1a#GameUI_ServerA\
    uthDisabled\x12Y\n0NETWORK_DISCONNECT_REJECT_SERVERCDKEYAUTHINVALID\x10\
    \x94\x01\x1a\"\xa2\xd4\x18\x1e#GameUI_ServerCDKeyAuthInvalid\x12E\n\x20N\
    ETWORK_DISCONNECT_REJECT_BANNED\x10\x95\x01\x1a\x1e\xa2\xd4\x18\x1a#Game\
    UI_ServerRejectBanned\x12T\n%NETWORK_DISCONNECT_KICKED_TEAMKILLING\x10\
    \x96\x01\x1a(\xa2\xd4\x18$#Player_DisconnectReason_TeamKilling\x12N\n\"N\
    ETWORK_DISCONNECT_KICKED_TK_START\x10\x97\x01\x1a%\xa2\xd4\x18!#Player_D\
    isconnectReason_TK_Start\x12^\n*NETWORK_DISCONNECT_KICKED_UNTRUSTEDACCOU\
    NT\x10\x98\x01\x1a-\xa2\xd4\x18)#Player_DisconnectReason_UntrustedAccoun\
    t\x12^\n*NETWORK_DISCONNECT_KICKED_CONVICTEDACCOUNT\x10\x99\x01\x1a-\xa2\
    \xd4\x18)#Player_DisconnectReason_ConvictedAccount\x12d\n-NETWORK_DISCON\
    NECT_KICKED_COMPETITIVECOOLDOWN\x10\x9a\x01\x1a0\xa2\xd4\x18,#Player_Dis\
    connectReason_CompetitiveCooldown\x12T\n%NETWORK_DISCONNECT_KICKED_TEAMH\
    URTING\x10\x9b\x01\x1a(\xa2\xd4\x18$#Player_DisconnectReason_TeamHurting\
    \x12Z\n(NETWORK_DISCONNECT_KICKED_HOSTAGEKILLING\x10\x9c\x01\x1a+\xa2\
    \xd4\x18'#Player_DisconnectReason_HostageKilling\x12N\n\"NETWORK_DISCONN\
    ECT_KICKED_VOTEDOFF\x10\x9d\x01\x1a%\xa2\xd4\x18!#Player_DisconnectReaso\
    n_VotedOff\x12F\n\x1eNETWORK_DISCONNECT_KICKED_IDLE\x10\x9e\x01\x1a!\xa2\
    \xd4\x18\x1d#Player_DisconnectReason_Idle\x12L\n!NETWORK_DISCONNECT_KICK\
    ED_SUICIDE\x10\x9f\x01\x1a$\xa2\xd4\x18\x20#Player_DisconnectReason_Suic\
    ide\x12V\n&NETWORK_DISCONNECT_KICKED_NOSTEAMLOGIN\x10\xa0\x01\x1a)\xa2\
    \xd4\x18%#Player_DisconnectReason_NoSteamLogin\x12X\n'NETWORK_DISCONNECT\
    _KICKED_NOSTEAMTICKET\x10\xa1\x01\x1a*\xa2\xd4\x18&#Player_DisconnectRea\
    son_NoSteamTicket:]\n\x18network_connection_token\x18\xc4\x8a\x03\x20\
    \x01(\t\x12!.google.protobuf.EnumValueOptionsR\x16networkConnectionToken\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(1);
            deps.push(::protobuf::descriptor::file_descriptor().clone());
            let mut messages = ::std::vec::Vec::with_capacity(0);
            let mut enums = ::std::vec::Vec::with_capacity(1);
            enums.push(ENetworkDisconnectionReason::generated_enum_descriptor_data());
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
