name: Test

on:
  pull_request_target:
    branches:
      - main

jobs:
  test-py:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Setup Python and Run Tests
        working-directory: ./src/python
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          pip install pytest maturin patchelf

          unzip tests/test_demo.zip
          maturin develop --release
          python3 test_perf.py
